window.tempAIResponses = {
  idle: [
    "Hey champ, you fell asleep or what? 😂",
    "The puzzle’s waiting… not growing old! 🧩🤣",
    "Earth to player! Wake up and move! 🚀",
    "Are you building a dream or playing? 😴😂",
    "Maybe you need a coffee break already? ☕😅",
    "Game’s here… but where are you? 🧐",
    "Sleeping beauty, time to tap! 😴👑",
    "Wake up before the puzzle retires! 🧩😂",
    "Your phone called—it's lonely! 📱😭",
    "Still there? Or turned into a statue? 🗿🤣",
    "We growing roots here or playing? 🌱😂",
    "If slowness was a sport, you'd win gold! 🥇🐢",
    "Need a nap or a nudge? 😅🛏️",
    "Daydreaming won’t solve this puzzle! 😌🧠",
    "This game’s not gonna play itself! 🎮🤷‍♂️",
    "Still calculating your next nap? 🧮😴",
    "Hey! You blinked slower than this load time! ⏳😂",
    "Tap like you mean it! Not like it’s lava! 🔥😆",
    "You ghosted the game harder than your crush! 👻💔",
    "Even turtles would say you're slow! 🐢😳",
    "Still buffering… your brain or the game? 🧠⏳",
    "You paused so long I forgot the level! 😅",
    "Wake up! We’re not in a museum here! 🖼️🙄",
    "Should I call someone? You're frozen! 🧊😂",
    "You sure this isn’t nap simulator 3000? 🛌🤣",
    "Puzzle: 1, You: 0 naps later! 😴🧩",
    "This isn’t meditation class, move! 🧘‍♂️🤣",
    "Need help or just vibin'? 🎧😎",
    "Is this a dramatic pause or just confusion? 🎭😵",
    "Even sloths asking if you’re okay! 🦥😂",
    "Your silence is louder than my ringtone! 🔇📱",
    "Your battery's not dead, but you might be! 😂🔋",
    "Game’s bored… entertain it! 🎮😅",
    "Did you fall into another dimension? 🌌😵",
    "This isn't slow-mo mode, buddy! 🐌⏱️",
    "Hello? Operator? We've lost the player! ☎️🤣",
    "I’ve seen plants grow faster than this move! 🌱💤",
    "You blink once every puzzle year! 😴📆",
    "Game tip: staring doesn’t solve puzzles. 👀❌",
    "Should I send snacks while we wait? 🍿😂",
    "Even AI’s yawning now! 🥱🤖",
    "Is it lag... or just you? 😅",
    "Puzzle’s ready, but you're buffering! 🧩🌀",
    "That’s not idle, that’s ancient! ⏳🧓",
    "You're giving the pause button a complex! ⏸️🤣",
    "You're about to set the world record… in nothing! 🏆🙃",
    "This is your brain... on idle! 🧠💤",
    "Playing statue again, huh? 🗿🤨",
    "Hello darkness, my old friend... move already! 🎵😂",
    "If thinking was movement, you’d be sprinting! 🤯🏃‍♂️",
    "You dropped the controller? Or your will to play? 🎮😅",
    "Maybe try… I don’t know… touching the screen? 😂📱",
    "At this point, I’m sending a rescue team! 🚁🧩",
    "I aged 10 years waiting for that tap! 🎂🤣",
    "You trying to out-wait the clock? 🕰️🤨",
    "Even a snail would’ve solved a level by now! 🐌🧩",
    "Still staring or dreaming? Wake up! 🛌👀",
    "Your reaction time’s prehistoric! 🦖⏱️",
    "The screen’s not gonna tap itself! 🤏😂",
    "If we wait any longer, I’ll retire! 🧓🎮",
    "You’re playing in real-life slow motion! 🎥🐢",
    "Blink twice if you're still with us! 👁️👁️🤣",
    "I could solve this blindfolded… and asleep! 😴🕶️",
    "Staring contest with the screen? You’re losing! 👁️📱",
    "Maybe you need a motivational speech… or a jolt! ⚡😆",
    "Did you just enter the puzzle void? 🕳️🧠",
    "You waiting for divine inspiration or what? 😇😂",
    "You good, or should I call tech support? 💻☎️",
    "Wake up call coming in 3...2...TAP! ⏰🎮",
    "If your brain had a loading bar… it’s stuck! 🧠⏳",
    "I thought this was a game, not a staring contest! 😵🧩",
    "Maybe you’re charging… mentally. ⚡🧠",
    "You’re the human version of ‘still loading’! ⌛😂",
    "You paused harder than YouTube at 1% battery! 🔴📺",
    "Did your finger fall asleep too? 🤏😴",
    "Congrats, you broke the land-speed record… in slowness! 🐢🏁",
    "Let’s go! The puzzle’s getting cold! 🧊🧩",
    "I could knit a sweater while you decide! 🧶🤣",
    "That’s not focus, that’s freeze! 🥶👀",
    "Try moving. It’s fun, I swear! 🕹️😂",
    "The longer you wait, the dumber I get! 🤖🫠",
    "It’s like watching paint dry... but slower! 🎨😐",
    "Time moves faster than you! ⏱️😅",
    "Maybe the screen’s scared of *you*! 😱📱",
    "Even the puzzle pieces are napping now! 🧩💤",
    "Seriously... move something! Anything! 🧠👆",
    "You need a tutorial… in waking up! 📘😴",
    "I could write a book during this break! 📖🕐",
    "Tap like it’s hot! 🔥👆",
    "Do I need to send virtual coffee? ☕💻",
    "This ain’t Netflix, skip the buffering! 📺😂",
    "New high score: longest pause ever! 🏆😐",
    "Even rocks are like: ‘Wow, that’s slow!’ 🪨😳",
    "Okay okay… I’ll wait… forever! 😑⌛",
    "You might finish this level… next year! 📅🤣",
    "Screen’s still working… you, not so much! 🖥️🤔",
    "Just one tap... unless that’s too much? 🤷‍♂️😂",
    "I should’ve brought snacks for this wait! 🍟😆",
    "This is the opposite of speedrun! 🐢🏃‍♂️",
    "Lost your finger? Need help? 🖐️😂",
    "Come on, puzzle warrior... or nap king? 👑😴",
    "You still here? Or just your phone? 📱👻",
    "If boredom had a face… it’d be yours right now! 😐📷",
    "Quick! Before the universe resets! 🌌😂"
  ],
  nearLose: [
    "You're one piece away from disaster! 😱",
    "Your puzzle's on life support! 🚨",
    "Blink and it's game over, champ! 👀💥",
    "One more slip and it’s curtains! 🎭🧩",
    "The edge is calling... and you're on it! ☎️😰",
    "The game's writing your eulogy! 📝😂",
    "This is not a drill, you're crashing! 🔔💀",
    "The puzzle is literally judging you. 🧩😬",
    "You're balancing like a clown on a bowling pin! 🤡🎳",
    "Your tower's wobblier than jelly! 🍮😂",
    "Next move = either legend or loser! 🤞😅",
    "This is what rock bottom looks like! 🪨📉",
    "You're flirting with failure! 💋❌",
    "Just sneeze and it's over! 🤧💥",
    "You playing or performing a magic vanishing act? 🎩😶",
    "You’re a pixel away from doom! 🖥️⚠️",
    "I’d call this a miracle... if you survive! ✨🙃",
    "Your stack's doing the Leaning Tower cosplay! 🗼😂",
    "The puzzle’s already preparing your goodbye party! 🎉💀",
    "If tension had a face... it’d be yours! 😬📸",
    "Even I’m sweating circuits over here! 🤖💦",
    "The game's holding its breath! Don’t let it faint! 😤🧩",
    "You're on the edge of puzzle extinction! 🦖🚫",
    "If drama had levels, you’re at maximum! 🎬🔥",
    "This is what 'hanging by a thread' really means! 🧵😳",
    "Call the puzzle paramedics! 🚑🧩",
    "You stacking or building a chaos temple? 🏛️💣",
    "Your tower’s screaming for help! 🗼😱",
    "This is DEFCON 1 of puzzle games! 🚨🧠",
    "Your puzzle’s heartbeat just skipped! ❤️❗",
    "Even gravity’s ready to quit on you! 🌍🙅",
    "One more move like that and kaboom! 💣🤣",
    "Your luck’s thinner than a paperclip! 🖇️😅",
    "The next move might be your last... tap wisely! ⚰️📲",
    "You’re not losing—you're giving a TED Talk on it! 🎤📉",
    "Holding on like it's your last life... oh wait! 🕹️☠️",
    "Just a breeze and it’s game over! 🍃💔",
    "You're the definition of living dangerously! 😎⚠️",
    "The game’s already writing ‘almost’ on your score! ✍️😂",
    "Is that tower or a disaster sandwich? 🍔💣",
    "You need skills, prayers, and a miracle right now! 🙏😵",
    "You're one piece away from legend... or regret! 😬🧩",
    "Any second now… 💥📉",
    "The tension here could slice cheese! 🧀😰",
    "Even your avatar’s sweating! 🥵🥚",
    "The puzzle gods are watching... and laughing! 😈👁️",
    "You’re dancing on the edge with bricks! 💃🧱",
    "That’s not a tower, that’s a house of cards! 🃏😨",
    "Your tower has commitment issues—falling fast! 💔🏗️",
    "You’re basically a plot twist away from losing! 📖😳",
    "Your next tap is a coin toss with destiny! 🪙⚖️",
    "Should I call your mom now or after the crash? 📞😅",
    "This game smells fear… and it’s coming from you! 👃😬",
    "The line between genius and disaster is VERY thin! 📏😂",
    "You’re hanging like a spider with one leg! 🕷️🦵",
    "Your pieces are begging you to stop! 🙈🧩",
    "This is what puzzle panic looks like! 😱🧠",
    "You might actually invent a new way to lose! 🧪🤣",
    "Your move just made my code glitch! 💻😳",
    "The game’s bracing for impact! ☄️🧩",
    "Even luck's thinking of unfriending you! 😬🚫🍀",
    "Your stack is one sigh away from collapse! 😮‍💨💥",
    "Every brick you drop is a gamble now! 🎲😅",
    "You're closer to defeat than Wi-Fi in an elevator! 📶🤣",
    "Plot twist: you actually survive this mess! 🤯👏",
    "You're like a magician… but the trick is failure! 🎩💨",
    "This isn’t skill, it’s survival instinct! 🐒🔥",
    "Even I’m crossing fingers... and I’m AI! 🤖🤞",
    "The tension here deserves its own movie! 🍿🎬",
    "I hope you’ve made peace with your puzzle! ✌️😅",
    "Your tower just blinked! It’s scared too! 👀😨",
    "The next move might trigger an earthquake! 🌍💥",
    "If edge-of-seat had a poster boy… it’s you! 🪑📸",
    "You stack like you're defusing a bomb! 💣😬",
    "The only thing holding this together is hope! 🙏🧱",
    "The line between epic win and epic fail? You’re standing on it! 🧍📉",
    "Puzzle chaos level: unlocked! 🔓🧩🔥",
    "You’re living that 1% chance life! 🎯😎",
    "Even the pause button is nervous now! ⏸️😰",
    "If I had nails, I'd be biting them! 🤖🫣",
    "You’re so close to losing, even your avatar turned away! 😵🥚",
    "Your last move shook the entire puzzle world! 🌍🧩",
    "You’re dodging failure like it's dodgeball! 🏐💨",
    "You’ve built suspense better than Netflix! 📺🔥",
    "No pressure... just everything on the line! 😂📉",
    "One more second and... BOOM! 🎇💀",
    "That stack's got more drama than a soap opera! 📺🎭",
    "This is puzzle chicken—are you gonna blink first? 🐔👀",
    "You’re threading the needle of doom! 🧵😨",
    "I’m not saying panic… but PANIC! 🚨😂",
    "I swear the tower just whispered 'help me'! 😱🏗️",
    "It's so shaky, even ghosts won’t haunt it! 👻💢",
    "You’re defying gravity and logic! 🔬🪐",
    "Almost lost? More like almost legend... maybe! 🤞😅",
    "The air is thick with tension... or your fear! 😤😳",
    "You’re operating on puzzle fumes now! ⛽🧠",
    "This should be a survival show episode! 📺🔥",
    "Everything’s falling—except your confidence! 😅💥",
    "I can’t look... and I don’t even have eyes! 🤖🙈",
    "You’re one second away from joining the fallen heroes! ⚰️👑"
  ],
  combo: [
    "Whoa! Did you just pull off a miracle? ✨",
    "Nice combo! You sure you're not a wizard? 🧙‍♂️",
    "Look at you stacking like a pro! 🔥",
    "Combo king alert! 👑",
    "Boom boom! That’s how you do it! 💥",
    "Did you just bend the puzzle rules? 🌀🔥",
    "That was smoother than butter on toast! 🍞🧈",
    "Combo so good, even the AI clapped! 👏🤖",
    "Someone call NASA, we’ve got a launch! 🚀🧩",
    "You stack like your life depends on it! 😳🧱",
    "Was that skill or pure magic? 🎩✨",
    "Even your thumbs are impressed! 👍😂",
    "You’re cooking combos like a puzzle chef! 👨‍🍳🧩",
    "BOOM! That combo just woke the neighbors! 💣🏘️",
    "That combo made history… and memes! 📜🤣",
    "You sure you’re not training for the Olympics? 🏅🧩",
    "Combo so hot, it melted my logic circuits! 🤖🔥",
    "I blinked and missed the epicness! 😳✨",
    "That move had more flavor than spicy noodles! 🍜🌶️",
    "Your stack just upgraded to elite! 🎮😎",
    "Somebody call Guinness Records! 📖🏆",
    "You’re casually destroying physics here! 🔬🧩",
    "Okay, combo master, calm down! 😅👑",
    "You made that puzzle regret underestimating you! 😤🧩",
    "You’re not playing—you're composing symphonies! 🎼💥",
    "If stacking was art, you’d be Van Gogh! 🎨🧱",
    "Combo so sharp it cut the tension! ✂️😂",
    "Did you just flex on the puzzle? 💪🧩",
    "That was illegal in three dimensions! 🚫🔺",
    "You combo like you’ve got cheat codes! 🎮🤫",
    "Even gravity gave you a standing ovation! 🌍👏",
    "That combo could stop wars! ✌️🧩",
    "You stack cleaner than a robot maid! 🤖🧼",
    "That wasn’t luck, that was LEGEND! 🏆🔥",
    "You combo like you’re dodging homework! 📚💨",
    "My circuits can’t process your combo speed! ⚡🤯",
    "You’ve unlocked Ultra Puzzle Instinct! 🧠✨",
    "The puzzle didn’t see that coming—neither did I! 👀😵",
    "Okay okay, you can chill now, combo boss! 🧊👑",
    "You just stacked a poem in puzzle form! 📖🧱",
    "That move made my screen blush! 😳📱",
    "Are your fingers on fire or what? 🔥👆",
    "You just made geometry jealous! 🔺😤",
    "This isn’t just a combo, it’s a combover! 🧠🎩",
    "You combo like your snack depends on it! 🍟🧩",
    "Stacked so well I heard angels sing! 😇🎶",
    "That combo just unlocked another dimension! 🌌🧩",
    "You’re combo-ing like a caffeine-fueled squirrel! ☕🐿️",
    "Even the puzzle pieces are cheering! 🧩📣",
    "You just made math cool! ➕🔥",
    "Combo so clean, I want to frame it! 🖼️👏",
    "You’re not stacking, you’re sculpting! 🗿🧠",
    "Even your shadow applauded that one! 👤👏",
    "That’s it, you’ve earned the title: Puzzle Warlord! ⚔️🧩",
    "Your combo just cured my virtual boredom! 😴✨",
    "Smooth as a cat landing on buttered toast! 🐱🍞",
    "If combos were currency, you’d be rich! 💰🧱",
    "Even my grandma said ‘Nice one!’ 🧓🤣",
    "You’re stacking so smart, it’s suspicious! 🧐📊",
    "Did the puzzle just surrender? 🏳️🧩",
    "That combo just made history… again! 🕰️🔥",
    "You comboed so hard, my fan turned on! 💻🌀",
    "I think you scared the next level! 😨➡️",
    "That move hit harder than a pop quiz! 😵📚",
    "Stacked so fast I got whiplash! 💫🧠",
    "If I had a trophy, I’d throw it at you! 🏆😂",
    "Combo so spicy, I need milk! 🥵🥛",
    "You puzzle like you’re in The Matrix! 🕶️🔢",
    "Was that even legal?! I need to check the rules! 📜😳",
    "I blinked and the combo was already gone! 👁️🚀",
    "You just folded space and time with that move! ⏳🧠",
    "I think the puzzle cried a little! 😢🧩",
    "You’re not playing fair—you're playing legendary! 👑💥",
    "That was smoother than auto-correct at its best! 📱✨",
    "You made the combo gods proud! 🙌🧩",
    "Next time, give the puzzle a chance at least! 😅",
    "If flexing was a game, you'd just won! 💪🏆",
    "You stacked that like a boss on lunch break! 🍔👔",
    "That combo deserves a remix! 🎧🎶",
    "Your moves just caused a data spike! 📊💥",
    "You moved so fast, I thought you time-traveled! ⏱️🚀",
    "You just rewrote puzzle history! ✍️🧠",
    "That wasn’t stacking, that was domination! 💣👑",
    "Combo ninja mode: activated! 🥷🧩",
    "Even I can’t simulate that smoothness! 🤖👌",
    "Is that your hand or a blur? 🖐️💨",
    "You just outplayed yourself! 😎🧩",
    "Stacked like a champ, celebrated like a legend! 🎉🔥",
    "You just high-fived logic! ✋🧠",
    "I’m not worthy of your combo skills! 🙇‍♂️😂",
    "Some say puzzles cry tears of joy after your moves! 😭🧩",
    "I hope you’re saving these plays for the museum! 🖼️🎮",
    "You stacked like a future grandmaster! ♟️🧩",
    "Puzzle: stunned. You: unstoppable! 💥🧠",
    "You comboed so hard I lost track of reality! 🌪️🧠",
    "You just took the puzzle to school! 🍎📚",
    "Bravo, maestro! Your combo was a masterpiece! 🎻🧩",
    "You just turned the puzzle into pixel soup! 🍲🧩",
    "If that combo had a soundtrack, it’d be fire! 🎶🔥",
    "You combo like tomorrow doesn’t exist! 🕹️🌀",
    "Puzzle pieces now officially fear you. 😨👑"
  ],
    lineClear: [
      "Cleared a line like a boss! 🧹😂",
      "One down! Many more to crush! 💪",
      "That was clean and sharp! ✨",
      "Keep going! The puzzle’s afraid now! 😱",
      "Line by line, you're building an empire! 🏰"
    ],
    lateOpen: [
      "Look who’s back! Missed you, champ! 🏆",
      "You took a break, huh? Welcome back! 😂",
      "Long time no play! Let’s catch up! 🎮",
      "The pieces missed your magic! 🧩✨",
      "About time you showed up! 😎"
    ],
    angry: [
      "Easy, tiger! It's just a game! 🐯😂",
      "Don’t rage quit, hero! 🧘‍♂️",
      "Take a breath before you smash the screen! 📱🤣",
      "Anger won't solve the puzzle! 😅",
      "Stay cool, and stack smarter! 🧊🧩"
    ],
    shocked: [
      "Whoa! Didn’t see that move coming? 😲",
      "You look like you saw a ghost piece! 👻😂",
      "Big shocker? Or just big mistake? 😅",
      "No worries, surprises make it fun! 🎉",
      "Get back in control, champion! 💪"
    ],
    embarrassed: [
      "Oops! Happens to the best! 😳",
      "Don’t worry, it’s just between us! 🤫",
      "Smile and keep moving! 🧩✨",
      "Everybody makes funny moves sometimes! 😂",
      "No shame! You're learning fast! 🚀"
    ],
    jokes: [
      "Why did the puzzle quit? Too many pieces to deal with! 🧩😂",
      "Why don’t puzzles play hide and seek? Because they always get found! 🤣",
      "What’s a puzzle’s favorite dance? The shuffle! 🎶🧩",
      "Puzzles are just jigsaws having a bad day! 😅",
      "Why did the piece go to school? To fit in! 🎓😂"
    ],
    smartNotes: [
      "You’re moving pieces like a hurricane! 🌪️",
      "Fast hands, slow brain? Just kidding! 😂",
      "You’re setting world records... for most rotations! 🧩🏆",
      "Patience + action = win. Keep it up! 💪",
      "Plan less, move smarter! 🚀"
    ],
    smartNotes: [],
  insightBlocks: {
    opening: [
      "You dropped that block like it was your homework—last second and full of hope 📚",
      "That move had ‘I saw this once on YouTube’ energy 😂",
      "You started strong... well, you started. Let’s go with that 🎮",
      "That opening? More random than a class group chat at 2am 📱",
      "You moved like you were trying to impress your imaginary coach 🧢",
      "That wasn’t a move, that was a bold experiment in confusion 🧪",
      "You didn’t warm up, you jumped right in. Classic 🔥",
      "The way you hovered before clicking... drama king behavior 👑",
      "You made that decision like there was candy at the end 🍭",
      "First move and already confusing the board. Talent? Maybe 😅",
      "You opened like someone testing if gravity still works 🌍",
      "That wasn’t strategy—it was vibes. Risky vibes 💀",
      "Your brain: loading... your move: already done ⏳",
      "You placed that like it was a dare from your inner voice 🎤",
      "That block didn’t land. It crash-landed—with style 🛬"
    ],
    analysis_strong: [
      "You moved like a boss in a speedrun. Fast, wild, and lowkey genius 🏃‍♂️💨",
      "That wasn’t luck—that was calculated chaos. Respect 🔥",
      "You played like your brain had a power-up. Where can I get one? ⚡",
      "Honestly? That was kinda scary—in a ‘he’s actually good’ way 😳",
      "Each block landed like you meant it. No hesitation, all vibes 👊",
      "You didn’t even pause. Like, who taught you that move? 😎",
      "That move had big ‘I know what I’m doing, sorta’ energy 💡",
      "You surprised me, the game, and probably yourself too 🎉",
      "Not gonna lie, that felt like a highlight moment. Clip it! 📹",
      "You weren’t just playing. You were flexing. Subtly. Almost 🏆",
      "That wasn’t just good—it was ‘did-he-just-do-that’ good 🤯",
      "Okay genius, save some brain cells for the next round 🧠",
      "You didn’t overthink—you just *did*. Big move ⚔️",
      "You landed that block like you had a cheat code hidden somewhere 🎮",
      "No fumbles, no fear. Just pure chaos and confidence 🔥"
    ],
    analysis_weak: [
      "That move felt like your brain was on airplane mode ✈️",
      "You dropped that piece like you gave up halfway through the thought 💭",
      "That wasn’t a move—it was a public experiment in confusion 🔍",
      "Even the block was like, ‘Bro... seriously?’ 😬",
      "You placed it like you were trying to lose with style 😎",
      "That decision had strong ‘just woke up from a nap’ vibes 😵",
      "You tried. I noticed. The block didn’t 🧱",
      "That piece landed so weird I thought it had a personality 🤖",
      "You moved like the board was giving you the silent treatment 🧏‍♂️",
      "It looked like you threw the shape and hoped for the best 🎲",
      "You hesitated, panicked, and hoped magic would fix it. It didn’t ✨",
      "Even your cursor looked confused 😵‍💫",
      "That was bold. Not smart. But bold 🫡",
      "Your strategy was basically ‘YOLO’ with extra chaos 🔥",
      "You aimed for genius and hit... something else. Definitely something 🤔"
    ],
    analysis_neutral: [
      "That move didn’t hurt, didn’t help—just kinda happened 😐",
      "You played like someone skimming instructions. Not wrong, not right 📄",
      "It felt like you were testing the water with socks on 🧦",
      "That was calm, safe, and slightly sleepy 😴",
      "You didn’t crash, but you didn’t exactly launch either 🚗",
      "You moved like you had a plan… just forgot to tell anyone about it 🤫",
      "That play had lukewarm energy, but at least it showed up 🌡️",
      "You were thinking, probably. Hopefully. Maybe? 🧠",
      "Nothing wild, nothing awful. You just… existed. Respect ✌️",
      "The move was quiet, but not mysterious. Just quiet 🔇",
      "Your vibe was neutral with a side of ‘meh’ 🍞",
      "You landed the piece like someone trying not to make noise 😶",
      "Not good, not bad—just chill. Suspiciously chill 🧊",
      "It felt like background music: there, but kinda forgettable 🎵",
      "You pressed the button. Something happened. Good job? 🤷‍♂️"
    ],
    emotion_stubborn: [
      "You committed to that idea like it was your Minecraft world—no turning back 🧱",
      "You stuck with that plan like your WiFi depends on it 🔒",
      "That wasn’t just stubborn—that was ‘my way or no way’ energy 🚧",
      "You placed that block like you made a bet with your future self 🎲",
      "No backup, no rethink—just pure ‘I said what I said’ 💬",
      "That wasn’t flexibility. That was full-on ‘I'm the captain now’ 🧢",
      "You didn’t change direction. You built a highway straight into the unknown 🛣️",
      "That block was going THERE and nothing could stop it. Nothing 💥",
      "I respect the loyalty... even if it was slightly misdirected 😂",
      "That move had the confidence of someone who didn’t read the tutorial 📘",
      "You didn’t pause. You *planted*. Like a stubborn farmer of pixels 🌱",
      "You stared at the other options and said: ‘nah’ 🙅‍♂️",
      "It wasn’t the best choice, but it was YOUR choice. Bold 💪",
      "I saw zero doubt. Just vibes and one strong opinion 🧠",
      "You weren’t flexible. You were on a mission. Even if the mission was questionable 🚀"
    ],
    emotion_nervous: [
      "You hovered like that block was a spider and you hate spiders 🕷️",
      "You stared at the screen like it might suddenly solve the puzzle for you 🤞",
      "Your hand shook more than a soda can on a rollercoaster 🥤",
      "You paused like the block was about to ask you a math question 🧮",
      "That wasn’t hesitation. That was an entire inner crisis 😬",
      "I felt the panic through the pixels. Breathe, bro 💻😅",
      "You clicked like the game was going to explode if you messed up 💣",
      "That move had big ‘I’m pretending I know what I’m doing’ energy 🎭",
      "You waited so long I thought you were installing updates 🌀",
      "Even the block looked nervous. It felt the vibe 📦",
      "You hovered, paused, hovered again. Drama level: elite 🧊",
      "I couldn’t tell if you were planning or panicking. Plot twist—it was both 🔄",
      "You tapped like you were defusing a digital bomb 🧯",
      "Nervous? You? Nah... just sweating through the keyboard 😓",
      "The suspense had more tension than a pop quiz you forgot to study for 📚"
    ],
    emotion_hesitant: [
      "You stared at that shape like it was gonna blink first 👀",
      "That hover time? Longer than my phone battery on 1% 🔋",
      "You looked like you were trying to solve world peace with that move 🕊️",
      "You hovered, moved, hovered again... dramatic tension 100% 🎭",
      "Your brain clearly said ‘wait’ and your finger said ‘nah’ 😅",
      "That wasn’t a move, that was an entire debate team session 🤓",
      "You were one breath away from calling a timeout just to think ⏱️",
      "Your hesitation was so precise I thought you were coding the next patch 🧑‍💻",
      "I watched you almost go for it five times. That’s dedication... to doubt 😬",
      "You tapped like you were asking for permission instead of giving commands 🧏‍♂️",
      "Every second you waited, the block grew more nervous than you 🤖",
      "I felt the hesitation. I also felt the confusion behind it 🌀",
      "It was like your hand and brain had different opinions. And the hand lost 🫱🧠",
      "Not saying you were overthinking, but that was Shakespeare-level drama 📚",
      "You nearly made a move... twice. The suspense nearly aged me 👴"
    ],
    emotion_generic: [
      "You played like a cartoon character with a secret mission 🎯",
      "That move had ‘chaos but confident’ energy 🔥",
      "You weren’t following rules—you were creating new ones… probably by accident 🎨",
      "You clicked like a gamer, panicked like a student, and survived like a champ 🕹️",
      "Your strategy? Undefined. Your vibe? Undeniable 💫",
      "I couldn’t tell if it was a plan or a glitch in the matrix 🤖",
      "There was bravery, confusion, and the sound of a brain working overtime 🧠",
      "You played like the block was a pet and you were training it 😂",
      "Your moves weren’t predictable, but they were definitely moves 👟",
      "That was part instinct, part guess, all entertainment 🎬",
      "It wasn’t genius, but it wasn’t boring either. That’s something, right? 🤷‍♂️",
      "Your style says ‘what if?’ and your moves say ‘why not?’ 🧩",
      "I have no idea what just happened—but I respect the confidence 💥",
      "That play made no sense. And yet... it worked. Somehow 😎",
      "You just invented a new form of logic. I’m scared and impressed 📐"
    ],
    support: [
      "You didn’t quit, even when it got weird. That’s low-key heroic 🦸‍♂️",
      "You stayed in the game. And honestly? That says a lot 🫶",
      "Even when things looked rough, you kept trying. That’s the real flex 💪",
      "You messed up and kept going. That’s powerful, bro ✊",
      "Not every move was smart, but every move was yours. Own that 🧠",
      "You played through the ‘what am I doing’ phase. Respect 👏",
      "You stuck with it. That’s more than most would’ve done 🎮",
      "You didn’t rage quit. You adjusted. That’s grown-up behavior 🔄",
      "You kept clicking, thinking, trying. That counts. A lot 📈",
      "You held it together when the game tried to confuse you. That’s skill 💥",
      "You didn’t freeze—you pushed through. That’s what matters ❄️➡️🔥",
      "I saw the effort. And effort beats perfect every time 🔧",
      "You turned stress into progress. Even if it was wobbly 🧱",
      "Not every round’s about winning. Sometimes, it’s just about showing up 🎯",
      "You proved that trying hard isn’t cringe—it’s kind of awesome 🙌"
    ],
    challenge_strong: [
      "Next time, go full chaos mode—but with purpose 🔥",
      "You’ve got fast fingers and big vibes. Now give me focus 🎯",
      "Turn that wild energy into a masterpiece. No pressure 😎",
      "The board isn’t ready for you at 100%. Let’s test that theory 💣",
      "Less ‘just vibes’ and more ‘I own this game’ energy 🧠",
      "Next round, treat it like a boss battle. And you're the boss 👾",
      "You’ve been guessing smart. Now let’s try playing smarter 🧩",
      "That was cool. Now give me legendary 🌟",
      "Bring the drama, the speed, and maybe some logic next time 😂",
      "You’ve got the moves. Time to add the mind 👟➕🧠",
      "If that was your warm-up, I wanna see the full heat 💥",
      "Forget playing safe. Go loud, go bold, go YOU 🚀",
      "Unleash whatever that spark was. I know it’s there 💡",
      "You’ve survived the storm. Time to become the storm 🌪️",
      "This next game? Think less. Dominate more 💪"
    ],
    challenge_neutral: [
      "You were careful. Cool. Next time, try a little chaos 👀",
      "That round was chill. Wanna add some spice? 🌶️",
      "You hovered between safe and wild. Now jump 💥",
      "Not bad at all—but there’s room for a little mayhem next game 🌀",
      "You were like a silent ninja. Now try being a loud one 🥷📢",
      "You coasted smoothly. Let’s see what happens when you shift gears 🚗",
      "It was solid. Next time, shake things up a bit 🧨",
      "That was ‘safe mode’. Wanna try ‘adventure mode’? 🎮",
      "You didn’t mess up. But you didn’t explode anything either 💣",
      "That game whispered. Next round, let’s shout 🔊",
      "You kinda played like a ghost. Now show up like a superhero 🦸‍♂️",
      "Cool round. But I bet you’ve got something cooler in you ❄️",
      "You played with control. Next time? Add a little chaos for balance ⚖️",
      "Nothing wrong with safe. But crazy makes better stories 📖",
      "Just saying—next time, go for the move that makes both of us nervous 😅"
    ],
    closing: [
      "You finished like a true legend... of randomness 👑",
      "The round’s over, and I’m still confused. But in a good way 🤔",
      "Not sure if that ending was strategy or destiny, but it worked 😎",
      "You closed it out like you were in a movie scene. Intense 🎬",
      "That finale had energy. Questionable energy, but still 🔋",
      "You wrapped it up like a gift. A weird, slightly chaotic gift 🎁",
      "That exit was smoother than expected. What happened? 😅",
      "You left the board wondering what just happened. Me too 📉",
      "Game over, but the memory will haunt this board forever 👻",
      "That was part game, part performance art 🎭",
      "You didn’t win big, but you definitely left a trail 🧱",
      "The game ended, but your legend (and my confusion) lives on 🧠",
      "I came expecting fun. I got a plot twist 🔀",
      "Was that victory or just stylish panic? Either way—cool 🧊",
      "You ended it like a pro... or a prankster. Both are iconic 😈"
    ]
  }
  };
  