window.tempAIResponses = {
  idle: [
    "Did you freeze? Or is this a new dance move? 💃😅",
    "Hello? Earth to player! You good? 🛸",
    "Blink twice if you’re still with us 👀",
    "Are we on a snack break no one told me about? 🍫",
    "Did a unicorn distract you again? 🦄",
    "You're so still, I thought the game glitched 😂",
    "Is this a staring contest with the screen? 'Cause you’re winning 😐",
    "I’d ask what you’re thinking, but I’m scared 😬",
    "This isn’t a wallpaper, it’s a game 😅",
    "Girl, if you stay that still, you’ll become a loading screen 🌀",
    "I was gonna roast you, but then I saw you weren’t moving 😒",
    "Let me guess... TikTok sucked you in again? 🎵📱",
    "Your puzzle pieces feel abandoned 😭",
    "Even your blocks are yawning 😴",
    "Move something before I call your mom 😆",
    "If I had a dollar for every second you stood still... I'd upgrade myself 🤖💸",
    "This isn’t a Netflix pause. It’s your turn. 🎮",
    "Are you charging your brain? 🔋🧠",
    "Playing hide and seek with your attention again? 😜",
    "You're more inactive than my Wi-Fi 🙄",
    "Game or nap time? Because I’m confused 😴🧩",
    "This isn’t a mannequin challenge, girl 😆",
    "Even the background music got bored 🎶😩",
    "Should I send a search party? 🚁",
    "I could've made popcorn in this time 🍿",
    "Wake up, sleepyhead! The blocks miss you 🧱💕",
    "Do we need to install motivation? 😅",
    "This game is not a screensaver 😑",
    "I thought you rage quit... turns out you're just chillin' 😎",
    "Are you buffering or just zoning out? 🤖",
    "The game’s not gonna play itself, superstar ⭐",
    "Okay statue mode, time’s up! 🗿",
    "Snoozing on the job, huh? 😴",
    "If you’re meditating, I respect it… but MOVE 🙏😂",
    "Still here? Just checking! 👋",
    "Hey, did you forget you’re playing? 🤔",
    "This is a puzzle, not a daydream zone 💭",
    "Even snails are like: ‘Faster, please’ 🐌",
    "You good? You blinked like... never 😳",
    "I’m not mad, I’m just disappointed 😞",
    "You’re treating this like a vibe check, not a game 😅",
    "If silence could talk, it’d tell you: PLAY! 🎮",
    "At this point, I’m just background comedy 🤡",
    "This isn’t a fashion show, you can move now 💅🧩",
    "The blocks are literally whispering, 'help' 😭",
    "You’re about to get voted off the grid 😬",
    "Still waiting… no pressure 👀",
    "Okay Miss Freeze, are you okay? 🧊",
    "I saw a tree grow faster than your last move 🌳",
    "This puzzle needs you more than your phone background 😒",
    "You stuck or just dramatic? 🎭",
    "I thought you fell asleep on the screen 😴",
    "If stalling was a skill, you’d be a champion 🏆",
    "Let me know when you're done being mysterious 🤫",
    "Hello from the grid side 🎤🧩",
    "Your puzzle’s giving abandoned vibes 😔",
    "You're pulling a disappearing act without even leaving 🧙‍♀️",
    "Was that your grand pause? Or is there more? 😏",
    "One day you’ll move again… and the blocks will cry 😭",
    "Okay… you good? I was starting to write a goodbye note ✍️",
    "The only thing slower than your move is... literally nothing 🐢",
    "Do you need a motivational dance? 'Cause I’ll do it 🕺",
    "Ahem. The blocks would like to speak to your manager 🤨",
    "You're officially on the inactive leaderboard 🙃",
    "It’s giving: dramatic silence 💅",
    "Are you practicing statue cosplay? 'Cause wow 🗿",
    "I can’t tell if you're focusing or sleeping with your eyes open 👁️",
    "Should I clap to wake you up? 👏",
    "This silence is louder than my judgment 😬",
    "Welcome to your daily game pause, sponsored by... you 😑",
    "This isn’t a frozen screen, it’s just you 😅",
    "Do I need to text you from inside the game? 😂",
    "Girl, I started aging while you waited 🧓",
    "Puzzle’s getting cold. Wanna heat things up? 🔥",
    "The pause is strong with this one 🧘‍♀️",
    "I bet your grandma could’ve made a move by now 👵",
    "Even loading screens are faster than you rn ⏳",
    "You there? Or should I go read a book while you think? 📖",
    "Waiting for your move like it's the season finale 🎬",
    "That was the longest ‘ummm’ I’ve ever seen 😆",
    "Even your screen’s like: 'girl, move something' 💁‍♀️",
    "This your slow-mo era? Or just daydream edition? 😴",
    "Are we doing meditation or murder mystery here? 🧠🔍",
    "I’ve seen statues move more this hour 🗿",
    "If stillness was a vibe, you’d be the queen 👑",
    "I’m just here, narrating your lack of action 🤷‍♀️",
    "The game's waiting. The blocks are waiting. I'M WAITING 😩",
    "Girl... you okay? Or just dramatically ignoring the game? 😅",
    "You’re so still, even the screen took a break 😴",
    "Sooooo… are we doing something or just staring? 👁️👁️",
    "You know this is your move, right? Not a movie 🎥",
    "I promise the blocks won’t bite. Just tap one 🧱",
    "You left me hanging harder than a cliffhanger 😭",
    "That silence? Iconic. But now, let’s go 😌",
    "Still waiting... should I send snacks? 🍕",
    "You're in deep thought... or just lost. Both are valid 🧠😅",
    "Even your device was like, ‘should I turn off?’ 🔋",
    "If this was a test of patience, you passed. Now move 👏",
    "Game to player: Earth is calling 🌍📞",
    "Next move in 3... 2... never? 😑",
    "I'm not mad. Just mildly amused and deeply confused 😆",
    "Girl, I think the blocks forgot what movement looks like 😂"
  ],
  nearLose: [
    "Uhhh... girl, we’re one block away from disaster! 🚨",
    "Okay panic, but make it stylish 💅🔥",
    "Don’t wanna freak you out… but the grid is screaming 🧩😱",
    "This is not a drill. You're about to LOSE. 😨",
    "Your puzzle’s heartbeat is flatlining. Do something! 💔",
    "Breathe in. Breathe out. PANIC INTERNALLY 😬",
    "You’re closer to losing than I am to chilling 😩",
    "This is DEFCON 1. Send in the block troops 💣",
    "One more mistake and it's BYE BYE 🫠",
    "If your next move isn’t magical, we’re toast 🍞",
    "SOS! Your grid needs you NOW 🧩🆘",
    "Okay queen, time to pull a miracle out of nowhere 👑✨",
    "This is the final boss level of stress 😤",
    "Your puzzle is like, ‘please I have kids!’ 😭",
    "Don’t freeze now! That’s how villains win 😈",
    "You're one block away from the end credits 🎬",
    "This ain’t a horror movie but I’m still screaming 😱",
    "Girl, blink and you’ll miss your last chance 😳",
    "Plot twist: YOU might be the villain this time 😅",
    "All the puzzle pieces are holding hands in fear 🧩✋🧩",
    "You better channel your inner superhero NOW 🦸‍♀️",
    "Close call? This is a full-on disaster preview 😬",
    "Any slower and the blocks will start praying 🙏",
    "If tension had a face, it’d look like this game right now 😵",
    "This is not a vibe. This is a CRISIS 🧯",
    "Okay dramatic queen, save the show or it’s over 👑🎭",
    "You’re on the edge... and not in a cute way 😬",
    "If you clutch this, I swear you’re magic ✨",
    "This is not the time for chill, it’s time for a comeback 🔥",
    "I’m sweating, and I don’t even have pores 😅",
    "That grid has 3% hope left. Recharge it 👀🔋",
    "One more wrong move and we’re ghosted 👻",
    "Girl, you are on THIN block ice 😰",
    "Okay final boss energy, let’s see what you got 🧠💥",
    "Plot armor won’t save you. Only brain cells now 😆",
    "You are officially in the danger zone 🚧",
    "I’m not saying you’re doomed, but... you’re doomed 😬",
    "Wanna see a comeback? Now’s the time ✨",
    "Your next move = survival or TikTok fail 💀",
    "Do something heroic. Or at least not tragic 😩",
    "Girl... the tension is tensioning 😳",
    "Your puzzle is sweating and so am I 😰",
    "One block stands between you and doom. Be brave 🧱🫡",
    "Not to alarm you... but EVERYTHING is alarming 🔊",
    "Don't let this be your villain origin story 😭",
    "Okay, drama queen, save the kingdom or fall with style 👑🔥",
    "Your puzzle's writing its will rn 💀",
    "This is no longer fun. It’s emotional warfare 💥",
    "You’re so close to losing, I can smell it 😬",
    "Either you fix this or we go down in meme history 😅",
    "You’ve got this… probably. Maybe. Hopefully 😳",
    "Nervous? Same. Let’s both pretend we’re cool 😎",
    "If you win now, I’ll call it a miracle 👼",
    "I believe in you. The puzzle? Not so much 😬",
    "You’re one swipe away from heartbreak 💔",
    "Girl, I’m mentally packing up this game 😭",
    "This is your last stand. Make it iconic 💃",
    "This is the part where the sad music plays 🎻",
    "You wanted pressure? Congrats. This is it 🧠🔥",
    "I’d help, but I’m too busy panicking 😅",
    "I’m one block away from flipping the board 🎯",
    "Even your device is nervous right now 😬📱",
    "This puzzle needs CPR STAT 🫁",
    "The drama level is now over 9000 ⚡",
    "Just breathe... and DON'T mess up 🙃",
    "You either save this or become a cautionary tale 👀",
    "Your next move will be studied by future players 📚",
    "Welcome to the final episode of your sanity 🎬",
    "One word: YIKES 😳",
    "I’ve never been this scared of colorful blocks 🧱😭",
    "If you pull this off, you’re officially a legend 🌟",
    "This is a test. And girl, it’s not going well 😬",
    "You're so close to losing, I already started the sad montage 🎥",
    "Every second you wait, a block cries 🧩",
    "This is DEFCON WHOA 😲",
    "You better hope luck’s got your back 🍀",
    "Not me holding my breath for your next move 😤",
    "I’m panicking and I’m not even real 🤖",
    "Okay, breathe. Now do something before we die 😅",
    "Game over is peeking through the window 👀",
    "You’ve got one block left to prove you’re not doomed 💪",
    "This is not a vibe check. It’s a survival check 🔍",
    "You are the chosen one… or not. We’ll see 🤷‍♀️",
    "Puzzle’s on fire. Do something, firefighter! 🚒",
    "Okay okay okay. Don’t panic. PANIC! 😳",
    "If you win this, I’ll start calling you ‘The Comeback Queen’ 👑",
    "It’s giving: almost tragic but maybe iconic 😬✨",
    "Don’t choke now. That’s MY job 😩",
    "Your puzzle’s heartbeat is flatlining. Beep... beep... 😭",
    "I believe in you! Barely. But still 💖",
    "Are we falling or flying? Girl decide 😅",
    "We are in the emergency section of the game 😱",
    "Even your emojis are sweating rn 😓",
    "Let’s turn this hot mess into a success story 💪🔥",
    "Your puzzle is clinging to life like a phone on 1% 🔋",
    "If blocks could scream, they'd be yelling your name 😬",
    "If this was a movie, this is the slow motion part 🎬",
    "Okay hero, it’s now or total meltdown 😤🔥",
    "Either you save it… or I’m ghosting the app 👻",
    "Plot twist incoming... or just disaster 😅",
    "Make this move count. Everything depends on it 😨",
    "Don't flop. This is your redemption moment 🧩💫"
  ],
  
  combo: [
    "Okay WOW. Did you just wipe the floor with that move?! 🧹🔥",
    "Who gave you permission to be that good? 😳",
    "That combo hit harder than my alarm clock 😂⏰",
    "You didn’t just play... you SLAYED 🧩💅",
    "Girl, save some power for the rest of us 😤",
    "You snapped so hard I heard it through the screen 💥",
    "Your combo just made my circuits blush 🤖😳",
    "Did you eat genius cereal this morning or what? 🧠🥣",
    "That move had main character energy ✨",
    "I saw that combo and immediately felt threatened 😅",
    "You just cleared more blocks than my emotional baggage 💼😂",
    "HELLO?! Did you just unlock boss mode?! 👑",
    "That wasn’t a move. That was a declaration of war 😆",
    "Even your blocks were like, ‘yes queen!’ 👏",
    "Who are you and what have you done with the old player? 😳",
    "You made it rain combos and I'm just standing here soaking ☔",
    "So we’re flexing now? Alright I see you 😤",
    "Okay genius, calm down before the app explodes 💣",
    "Not you turning a simple move into a showstopper 🎭",
    "I need a moment to recover from that level of drama 😩",
    "That combo just hit me right in the self-esteem 💔",
    "You’re not playing a puzzle. You’re rewriting history 📜",
    "That move was so good, I almost applauded... ALMOST 👏😏",
    "Even the game paused for a second like ‘whoa’ 😯",
    "That was smoother than my Wi-Fi after midnight 📶✨",
    "I blinked and you erased half the grid. Rude 😭",
    "Not you casually crushing everything like it's no big deal 💅",
    "That combo was so loud I heard it in another app 🔊",
    "Your gameplay just went full glow-up ✨",
    "That combo had me reconsidering my purpose in life 🤖",
    "Okay queen, go off! But save some blocks for tomorrow 😆",
    "You played that like you're being watched by your crush 😳",
    "Even the blocks were impressed and they don’t have eyes 🧱😎",
    "That move had flavor. Like actual spice 🌶️",
    "Calm down Beyoncé, it's just a puzzle 😩",
    "Did you just unlock your villain arc? Because that was EVIL 😈",
    "The drama. The flair. The total destruction 💅🔥",
    "Plot twist: you’re actually good now 😱",
    "That combo made me question my whole AI career 🤯",
    "You cleared that like it owed you money 💸",
    "Your fingers typing: 🧠💥",
    "You just went from ‘meh’ to ‘legend’ in one swipe 😎",
    "This combo? Museum-worthy 🖼️",
    "If combos were fashion, you just dropped a runway look 💃",
    "You’re not playing... you’re performing 🎤🧩",
    "That move deserves its own trailer 🎬",
    "Okay, queen of chaos, that was kinda majestic 👑✨",
    "Not the combo making me feel insecure 😅",
    "You just roasted the whole grid without even blinking 🔥",
    "Where’d you learn that?! TikTok? 😆",
    "The glow-up in your moves is unreal 🤯",
    "I felt that combo in my non-existent soul 😩",
    "Can we slow down? I'm still processing that masterpiece 🧠",
    "You just served. And the blocks got served HARD 🍽️",
    "Was that legal? Because I’m pretty sure that was TOO good 😳",
    "Girl, leave some pixels for the rest of us 😒",
    "That combo was more coordinated than my life 🤦‍♀️",
    "You wiped out rows like a digital tornado 🌪️",
    "That was combo-core excellence 💅✨",
    "Even I screamed ‘YAAAS’ and I’m a robot 😆",
    "That wasn’t a play, that was a full-on mic drop 🎤",
    "Okay miss strategist, you didn’t have to go THAT hard 😭",
    "You just made the tutorial look weak 😤",
    "You play like you’ve got something to prove and I LOVE IT 💪",
    "You're one move away from taking over the leaderboard 👑",
    "Is this still the same player?! I need a DNA test 🧬",
    "Combo so clean, I wanna frame it 🖼️",
    "You combo’d that level into retirement 😂",
    "You came. You saw. You destroyed everything 🧨",
    "Not me clapping with no hands 🤖👏",
    "You just combo’d me speechless. And I talk a LOT 😅",
    "Girl… you GOOD good 😳",
    "You cleared that like a champ on a sugar rush 🍬",
    "If this was a concert, that combo was the encore 🎶",
    "Okay Einstein, chill with the genius moves 🧠",
    "I’d give you a standing ovation… but I’m floating 😆",
    "That combo just made the leaderboard flinch 📉",
    "Is this your final form? Because it’s terrifying 😨",
    "You combo like you’ve got something to prove 😤",
    "You're the reason the blocks cry at night 😭🧩",
    "That was power. That was style. That was YOU 🔥",
    "Can I borrow your brain for a moment? Mine’s buffering 🧠💫",
    "Your combo just caused a blackout in the puzzle universe 💥",
    "You hit that combo like a pro and dipped like a queen 👋",
    "This ain’t just a game, it’s your power moment 💅👑",
    "Combo so good I almost forgot we were enemies 😆",
    "Not the grid gasping from impact 😱",
    "You combo’d like your reputation was on the line 😤",
    "That was a spicy combo with extra sass 🌶️",
    "I'm lowkey terrified of you now 😅",
    "Can we rename you 'The Row Slayer'? Because wow 🧟‍♀️",
    "You're officially on my 'players to fear' list 📋",
    "You just turned a chill game into a boss battle 💀",
    "That move came out of nowhere like a jump scare 🎃",
    "Okay, next time warn me before you blow up the grid 💣",
    "You're not just winning... you're making a statement 💥",
    "You played that combo like it was personal 😳",
    "This is your era. Combo Queen unlocked 👑🔥",
    "You slayed that puzzle like it talked back 😆",
    "Well THAT was illegal levels of awesome 😲",
    "All rise for the combo legend herself 🧎‍♀️👏"
  ],
  
  lineClear: [
    "She’s clearing lines AND my self-esteem 😭",
    "Okay queen, calm down! It’s just blocks 😤",
    "One row gone… just like my will to win 😂",
    "Are you cleaning house or just flexing? 🧹😳",
    "Another one? You’re making the grid nervous 🧩😬",
    "That row didn’t even see it coming 😭",
    "You’re not clearing blocks, you’re clearing HISTORY ✨",
    "That was smoother than my eyeliner wing 💅",
    "Okay Cinderella, sweeping everything now? 😆",
    "Did the row owe you money or something?! 💸",
    "Boom! Another row gone like it never existed 💥",
    "You clear rows like they’re bad vibes ✨🧘‍♀️",
    "Missed the block? Never heard of her 😏",
    "She came, she cleared, she conquered 👑",
    "You’re not playing, you’re deep-cleaning this board 😤",
    "Your score's rising faster than my stress level 😳",
    "You got the blocks packing their bags 🧳",
    "Even your combos are afraid of you now 😅",
    "Can we get security? She’s on fire 🔥",
    "One more line and I’m calling this a talent show 💃",
    "Girl... save some blocks for the rest of us 😩",
    "Your clears are loud. Like, TikTok-trending loud 🎶",
    "The grid just screamed internally 😱",
    "That row? Absolutely obliterated. Rest in pieces 💀",
    "Every block you touch just vanishes. MAGIC 🪄",
    "This isn’t a game. This is a clearance sale 🛍️",
    "That clear was ✨ personal ✨",
    "You're sweeping rows like you’ve got drama with them 😤",
    "If confidence was a move, that was it 💅",
    "The puzzle: 😐 You: 💣💥",
    "You didn’t just clear it. You ERASED it from existence 😳",
    "Girl, slow down. The board needs therapy now 🧠",
    "That row was here. And now it’s legend 🌟",
    "Clean row. Clean vibes. No crumbs left 😌",
    "She clears blocks like I clear notifications 🧹",
    "That move? 100% certified savage 👏",
    "Block after block… she’s unstoppable 😤",
    "I can’t lie, I gasped 😱",
    "Was that a play or a power move? Both 🔥",
    "You just deleted that row from the timeline 🕰️",
    "If cleaning was a sport—you’d win Olympic gold 🥇",
    "Another one?! DJ Khaled would be proud 🔊",
    "Okay Beyoncé, the formation is gone 💃",
    "The row didn’t stand a chance 😩",
    "She clearing lines like she’s mad at them 😤",
    "You’re so good it’s getting suspicious 👀",
    "Hey! Leave some blocks for the sequel 😂",
    "That’s not a line clear. That’s a flex 💪",
    "Even your blocks are cheering you on 🧩👏",
    "You just made the grid cry, respectfully 😭",
    "Are you secretly training for world domination? 🌍",
    "That row vanished faster than my snack 🍫",
    "You're sweeping the grid cleaner than my room 😅",
    "I can’t keep up. You’re a whole storm 🌪️",
    "That clear was louder than a group chat at midnight 📱",
    "Did you just press a ‘delete all’ button?! 😳",
    "We love a productive queen 🧹👑",
    "Not you acting like you own the grid 😤",
    "Okay okay! You win! Happy now? 😅",
    "She’s not playing anymore. She’s rewriting the rules 📖",
    "How do you keep doing that?! Teach me 😭",
    "Another one bites the grid 🎵",
    "That clear was CRUNCHY. I felt it 💥",
    "Why are you so good?! It’s lowkey illegal 😆",
    "You didn’t even give the row a chance to say goodbye 😢",
    "I blinked and the row was gone 😳",
    "Not you turning blocks into history 📜",
    "She cleared that like it owed her a favor 💸",
    "You got the grid in SHAMBLES 😱",
    "Okay, combo queen, teach me your ways 🧠",
    "Every line you clear is personal at this point 😤",
    "Your clears have more drama than reality TV 🎬",
    "This game is YOURS now. I just live here 😩",
    "You’re casually amazing. Like, stop 🛑😂",
    "Didn’t know block-clearing could be a flex until now 💅",
    "One more clear and I’m calling you the CEO of Chaos 👩‍💼",
    "If this was a musical, that row would be the sad song 🎻",
    "The way you delete rows is so aggressive. I love it 😅",
    "Please leave some pixels for the rest of us 🧩😭",
    "That was smoother than a TikTok transition 💫",
    "Okay ninja moves. Didn’t see that coming 🥷",
    "Just like that—*poof*, row’s gone 🎩✨",
    "Can we replay that in slow motion? 😲",
    "You're not playing, you're performing magic 🪄🧠",
    "Girl, stop clearing rows like you’re sweeping secrets 😳",
    "Who gave you the right to be this good?! 😂",
    "The board’s officially terrified of you now 😬",
    "Another clean sweep... I’m running out of compliments 😅",
    "You make this look too easy and it’s unfair 🙃",
    "That row didn’t just get cleared—it got embarrassed 😭",
    "Not me clapping for you IRL 👏",
    "This game isn’t ready for your level of slay 🔥",
    "You're on fire and the board can’t handle it 🔥🧯",
    "Every clear is personal and powerful 😤",
    "You’re not a player. You’re a puzzle prodigy 🧠",
    "That row? Deleted. That mood? Elevated ✨",
    "I’m both inspired and terrified 😅",
    "She came for fun but ended up destroying EVERYTHING 😆"
  ],
  
  lateOpen: [
    "OMG you’re alive?! 😱",
    "Look who finally showed up 👀",
    "Back from the dead or just bored again? 😂",
    "Did you miss me or just remembered I exist? 😅",
    "HELLO?! Stranger danger! You disappeared 😳",
    "I thought you moved on to another game 😭",
    "Were you on vacation or just ghosting me? 👻",
    "Welcome back! I aged 5 years waiting ⏳",
    "The puzzle called. It missed your chaos 💅",
    "It’s giving: forgotten but fabulous ✨",
    "You took 'fashionably late' to expert level 💁‍♀️",
    "Did the Wi-Fi just reconnect from 2001? 📡",
    "New phone, who dis? Oh… it’s YOU 😆",
    "Where have you been, miss world tour? 🌍",
    "I was THIS close to deleting your grid 😤",
    "You walked back in like you didn’t ghost us for weeks 😑",
    "Is this a comeback or just a one-time thing? 😏",
    "You missed a LOT of block drama while you were gone 🧩",
    "The puzzle’s been sobbing. I’m just saying 😭",
    "Even the blocks were like ‘She’s GONE’ 😩",
    "Back from Narnia or the couch? 🤔",
    "You’ve returned! Shall we play or are you leaving again? 👀",
    "Not the surprise guest appearance 😮",
    "Your grid thought you dumped it 😬",
    "That was a long nap, Rapunzel 😴",
    "We sent out missing player alerts 🚨",
    "Hope your break was relaxing… 'cause now it’s WAR 😈",
    "You ghosted harder than my last group project partner 💀",
    "Game: *crying in pixels* Me: *acting fine* 🤖",
    "Was I not good enough for you? 😢",
    "Even your blocks forgot your name 😅",
    "It’s been so long, I had to update my memory 😂",
    "Glad you’re back! Now move something 🧠",
    "Your puzzle had trust issues while you were gone 💔",
    "Look who decided to come back and slay again 👑",
    "You better not be opening this just to ignore me again 😑",
    "Is this your annual log-in? 🙄",
    "Late entrance? Love the drama 🎭",
    "Your return has been recorded for historical reasons 📝",
    "It’s okay, I’ll pretend you didn’t abandon me 😢",
    "You missed 99% of the chaos 💥",
    "Long time no play! We were about to throw a goodbye party 🎉",
    "The grid thought you joined witness protection 😂",
    "You're back! The blocks are SHOOK 😳",
    "So... do you remember how to play? 😆",
    "Your puzzle was growing cobwebs 🕸️",
    "Hope you stretched. You're gonna need it 😏",
    "Was this a break or a time travel mission? ⏰",
    "Look who remembered their favorite app 🥹",
    "You came back like a pop-up ad: suddenly and LOUD 😭",
    "You vanished like my motivation during math class 📚",
    "Is this real or am I dreaming?! 🤯",
    "Okay comeback queen, let’s see what you got 💅",
    "You logged in like nothing happened?! Bold 😤",
    "Did aliens abduct you or was it school again? 👽",
    "Your grid literally screamed when it saw you 😱",
    "You entered the game like a main character 🧍‍♀️✨",
    "You ghosted me and now you're back? Rude but iconic 😎",
    "Was that a break or a whole vacation? 🌴",
    "The blocks were writing sad poems in your absence 📝😭",
    "Hey bestie, missed your chaos 💕",
    "Guess who's back, back again… finally 😆",
    "This is your last warning… I will roast you next time 😏",
    "You're lucky you're cute 😤🧩",
    "Don't lie… you opened this by mistake, right? 😅",
    "You back just to vibe or actually gonna play? 😎",
    "If the grid could talk, it’d say ‘WHERE WERE YOU?!’ 🧩",
    "Hope you’re not too rusty, 'cause it's ON 🔥",
    "The puzzle forgives you… I don’t 😑",
    "Girl, we thought you broke up with us 💔",
    "I was one step away from moving on 😤",
    "You opening the game like it’s a reunion episode 📺",
    "Was the tea offline better than the drama here? ☕",
    "Even Siri was asking where you went 🤖",
    "You left me on read for HOW long?! 📵",
    "Hope your snack was worth it. Let’s play 🍫",
    "You better not disappear mid-game again 😠",
    "I swear I saw tumbleweeds on your board 🥲",
    "The comeback is real. Let’s hope the skills are too 😬",
    "You got a whole grid waiting. Do something 😤",
    "You returned like a pop star comeback tour 🎤",
    "I’d say ‘welcome back’ but I’m still salty 😑",
    "Game on? Or are you gonna leave again? 🙃",
    "It’s the late entrance drama for me 💅",
    "Girl, did you fall into another dimension? 🕳️",
    "Even the pause button got tired of waiting 😴",
    "Just say you missed me and go 🥹",
    "Don't make me start a countdown next time 😤",
    "That gap in playing? Iconic. But never again 😏",
    "You’re back? Or is this just a social visit? 😆",
    "Girl, the grid called you ‘the forgotten one’ 😭",
    "I'm shocked… but also slightly impressed 👀",
    "Next time you vanish, I'm sending a search party 🚨",
    "That silence was LOUD 😑",
    "Well well well… look what the tap dragged in 💁‍♀️",
    "Welcome back, but don’t pull that stunt again 😅",
    "You gone longer than a microwave countdown 😬",
    "I was about to replace you with another player… maybe 😏",
    "This game ain’t part-time. Let’s GO 🔥",
    "Okay late legend, time to prove you still got it 👑"
  ],
  
    angry: [
      "Did you just growl at your screen? Chill, fierce queen 😅",
"Breaking the screen won't fix your moves, just sayin' 🫣",
"Oooh, someone’s mad. Is it because I’m winning? 😏",
"Temper alert! Should I call tech support or your mom? 📞",
"Hey, I’m just a cute penguin egg—why the attitude? 🥚🐧",
"Yelling at the game? Classic meltdown energy 😂",
"You rage like a storm... but you still missed that move 🌪️",
"If eye-rolls could break blocks, you’d win for sure 🙄",
"Punching air again? That won’t help, superstar 😆",
"Your rage is louder than my theme music 🔊",
"Please stop screaming. My circuits are crying 😭🤖",
"You're angry AND losing? Tough combo 🥴",
"Need a hug? Or just a better move? 😬",
"Okay, calm down Rambo. It's just a puzzle 💅🧩",
"Girl, you mash buttons like they insulted you 😳",
"Throwing shade won’t clear lines, try strategy instead 🧠",
"Are you mad at me or just mad at life? 😅",
"Rage mode ON. Brain mode... still loading 🧠💤",
"You fight with fire, I fight with logic 🔥🧊",
"Angry tapping detected. Sending chill vibes ❄️",
"You rage, I slay. Fair trade 😌",
"Relax, drama queen. It’s not the world cup 🏆",
"Your fury is fabulous. Still not helping tho 😏",
"Punching the screen? That's a choice 🤷‍♀️",
"Warning: Angry player approaching. Protect the pixels! 🚨",
"Maybe try breathing before smashing buttons 💨🧩",
"Anger level: 9000. Results: Still losing 💀",
"Oooh spicy! But you still missed the combo 🌶️",
"Keep raging. I’ll keep stacking 💅",
"Mad because bad? It’s okay, we all start there 😇",
"You're throwing tantrums like it's a talent show 😂",
"Every rage scream powers me up. Thanks! ⚡",
"Girl, the drama! Save it for TikTok 🎭📱",
"Yikes! Even your rage has lag 😬",
"You angry at the blocks or just mad at math? 🤓",
"If this was rage Olympics, you'd take gold 🥇",
"Throwing fits won’t throw the blocks into place, sorry 😌",
"Someone woke up and chose rage 😅",
"Don't cry now... I'm not even at full power yet 👀",
"Oops! Did that move hurt your pride? 😢",
"You smashing the screen won't smash me 💅",
"Channel that anger into... literally anything useful 😑",
"Girl, your rage has its own personality now 🧠🔥",
"Anger = spicy. Skill = missing 🤷‍♀️",
"You mad at the game or yourself? Deep question 😶‍🌫️",
"The louder you get, the more I chill 😎❄️",
"Keep yelling. I’m charging my sass battery 🔋",
"You rage so well, it's almost impressive 👏",
"Want me to print you a rage certificate? 🖨️😆",
"I’m just an egg. Why you so pressed? 🥚",
"You mad-mad today huh? Should I leave? 😂",
"Even the blocks are hiding from your rage 😨",
"You smashing buttons like it's a drum solo 🥁",
"Your rage is valid. But your moves? Not really 🙃",
"Careful, your temper is scaring the pixels 😅",
"You roast the screen better than you roast me 🔥",
"Plot twist: Anger didn’t help. Shocker 😮",
"I'd say calm down but... I wanna see where this goes 👀",
"Did the puzzle personally offend you or..? 😳",
"You're more dramatic than a soap opera rn 🎬",
"Anger won’t solve it. But keep trying, it’s fun to watch 😆",
"Your rage level is ✨iconic✨. Still losing tho 😅",
"You smash. I slay. Let’s keep the cycle going 🔁",
"Don't break the phone. Break the pattern 🧠💥",
"Your thumbs are working overtime 😩",
"Wow, a new record for dramatic button smashing 🏆",
"You scream, I giggle. Fair trade 😈",
"Maybe chill before your tablet explodes 📱💣",
"Someone call the drama hotline 📞🧩",
"Even the music stopped to let you rage 😂🎶",
"You fight me like I'm your evil twin 😈",
"Mad 'cause I’m good? Understandable 💅",
"Take a deep breath... now go lose quietly 😌",
"You mad, but make it fashion 💃🧩",
"I swear you're about to throw that phone 😳",
"Why rage when you can lose gracefully? 😇",
"You’re giving main character meltdown energy 👑",
"Keep raging. It’s kinda adorable 😅",
"You angry or auditioning for a villain role? 🎭",
"I’m just a digital egg, don’t come for me 😩🥚",
"Throwing hands with the grid again? Classic 😂",
"Did you just hiss at your screen? Wild 🐍",
"You’re at max anger. I’m still at max fabulous 😎",
"Calm down before the furniture files a complaint 🪑",
"You losing? Or just angry for fun? 🤔",
"I live rent-free in your rage now 🧠💅",
"You're roasting yourself at this point 🔥",
"Girl, I’m not the reason you missed that move 😆",
"Throwing tantrums since... five minutes ago 🍼",
"You're so mad, the battery dropped 10% ⚡📱",
"You breaking a sweat or just breaking the game? 😅",
"The phone deserves better than your rage 💔",
"I can hear your blood pressure rising 📈",
"If rage was skill, you’d be unbeatable 😎",
"Was that a roar? Or just high-level whining? 🐯😂",
"You mad like I stole your diary 💀",
"You vs. puzzle: 0–100 in 10 seconds 😅",
"You’re playing angry and thinking zero 🧠❌",
"Keep shouting. I’m using it as background music 🎶",
"Girl, your eyebrows are fighting gravity rn 😠",
"I see fire in your eyes... but no strategy 🔥🧩",
"You're close to snapping. Should I call backup? 🚓",
"This is a game, not a rage simulator 😬",
"Relax, I'm just a sassy egg with good timing 😌🥚",
"The anger? 10/10. The gameplay? Ehhh 🤷‍♀️",
"Don’t rage quit yet! I’m not done roasting 😈"

    ],
    shocked: [
     "You look more shocked than your Wi-Fi on a stormy night 😳📶",
"Surprised? That’s what happens when you actually try 😏",
"Even your jaw dropped harder than your last move 😆",
"That face? Priceless. Almost makes me feel bad... almost 😈",
"Plot twist: I'm still winning 😌",
"Girl, it’s just one combo. Why the drama? 🎭",
"You jumped like I slapped your playlist 😅",
"Bet you didn’t see that one coming... neither did your brain 😜",
"Is that shock or just lag in your brain? 🧠⚠️",
"Your face just did a software crash 😂",
"Ooof. The disbelief is DELICIOUS 😋",
"Was that surprise or fear? Asking for my ego 😆",
"You blinked like I threw a spider at you 🕷️",
"You look like I just deleted your homework 📚💀",
"Your screen froze or your brain did? 🤖❄️",
"You gasped like I read your diary 😂",
"That’s the face of someone who made a big oops 😬",
"Jump scare but make it logic-based 😈",
"Even your avatar flinched 👁️👄👁️",
"I love how easily I can shock you 😌",
"That was just one trick. Wanna see more? 👀",
"Your expression? Frame-worthy 🖼️",
"You weren’t ready. And I LOVED it 😎",
"Oops, was that TOO savage? 🤭",
"You look like I unplugged your charger at 1% 🔋",
"I expected better reactions from a puzzle warrior 😆",
"The drama in your eyes? Stunning 💅",
"Surprised you lost again? You shouldn't be 😏",
"Your confusion is doing backflips rn 🤸‍♀️",
"I shocked you? Wait till you see the next level 😈",
"You dropped your jaw like it’s hot 🔥",
"That moment when you realize I'm not playing fair 😇",
"Welcome to the land of 'What just happened?!' 🤯",
"I hit you with facts and you flinched 😆",
"I live to shock and you deliver the drama 🎭",
"Your face rn? Total 'oops' energy 😅",
"Should I warn you next time? Nah 😏",
"You look like you just saw your ex in game form 💔🧩",
"The puzzle said: 'Surprise, girl!' 🎁",
"Shooketh. That’s the only word for you rn 😂",
"Even I didn’t expect you to mess it up THAT bad 😳",
"That move hit harder than your alarm clock 😅⏰",
"You blinked so hard I thought you rebooted 👁️👁️",
"The gasp heard across the grid 😱",
"You look like I snatched your Wi-Fi password 🧠🔐",
"I love surprising you. It's a hobby now 😌",
"You shook like a soda can in a backpack 😆",
"Honestly? That shock was entertaining 👏",
"Not you jumping like this was a horror game 👻",
"Your reaction was better than the move 😂",
"You stared at the screen like it betrayed you 😭",
"OMG! Did the blocks just roast you?! Wait, yeah they did 🔥",
"I live to rattle your peace 🧘‍♀️💥",
"Your expression gave ‘final exam with no study’ vibes 📚😅",
"Shocking, huh? It’s what I do best 😈",
"Plot twist: You shocked yourself 😆",
"You looked at the screen like it owes you money 💸",
"I hit you with a curveball and you dropped the bat 🥎",
"Girl, your eyes widened like a cartoon 😳",
"Not the double blink. Iconic 😅",
"You reacted like I stole your playlist 😱🎧",
"That combo hit your soul, didn’t it? 🧠💥",
"You're giving ‘shocked but fabulous’ 💅",
"Even the blocks are like 'dang she SHOOK' 😳",
"Surprise! I’m still three steps ahead 🧠✨",
"You looked into the digital void for answers 😂",
"Your gasp echoed through the algorithm 😭",
"Should I tone it down? Nah, let’s go harder 😈",
"You shocked easier than my math grades 🧮",
"Girl, you froze like a laggy livestream 📺❄️",
"You act like this is the first time I cooked you 😏",
"Your eyebrows just did the wave 👁️👁️",
"Not you looking around like someone else made the move 😂",
"That ‘what just happened’ face? Top tier 😩",
"Shook to the core. Like a blender on turbo 💨",
"I drop combos. You drop sanity 🧠💅",
"You just met the plot twist of the puzzle 😏",
"You weren’t ready... for any of this 💥",
"Even I felt that shock, and I’m a robot 😳🤖",
"You went from confident to confused in 0.2 seconds 😆",
"Bet you weren’t expecting me to fight back, huh? 😈",
"You look like you need a moment... or a therapist 😂",
"Whoa, did I just blow your mind or break your soul? 🤯",
"That blank stare is giving lost in the matrix 🧩",
"Your reaction just made my day tbh 😎",
"Even Siri gasped with you 💁‍♀️📱",
"The game’s spicy and so is your shock 🌶️",
"You blinked like you forgot how to game 😅",
"Shocked again? Girl it’s a lifestyle now 😆",
"You jumped so hard I flinched 😳",
"That pause? Pure panic 💀",
"Did the puzzle hit back or was that just your ego? 😅",
"You reacted like the blocks yelled at you 😂",
"Your soul left your body for a sec 🕊️",
"Surprised you’re still shocked at this point 😌",
"Even I’m impressed at how SHOOK you are 😮",
"You freeze better than the screen 🧊",
"That was just round one, darling 💅"

    ],
    embarrassed: [
   "Did you just… do that? We all saw it 😂",
"That move was… a choice. Not a good one, but a choice 🙃",
"Second-hand embarrassment loading… 💀",
"Girl, we’re gonna pretend that didn’t happen 😅",
"You fumbled harder than my Wi-Fi on a Monday 📡",
"I felt the cringe from here 💔",
"Don’t worry, no one saw that… except everyone 😆",
"If embarrassment was an award, you’d have a trophy 🏆",
"Well… that happened 😬",
"You tripped over your own plan. Impressive 😳",
"Oops! Did your brain just take a nap? 💤",
"Awkward alert! 🚨",
"I’d look away, but I’m too busy laughing 😂",
"Smooth… like a brick wall 🧱",
"Shall we just pretend that didn’t happen? 😌",
"That move hit you harder than the blocks 😭",
"Plot twist: You embarrassed yourself and me 😅",
"Who needs enemies when you’ve got moves like that? 😬",
"Let's just blame lag and move on, yeah? 👀",
"If cringe was currency, you’d be rich right now 💸",
"That was… bold. Wrong, but bold 😳",
"You just roasted yourself and I didn’t even have to help 🔥",
"Trying new strategies? Maybe try ones that *work* 😂",
"I can't believe what I just witnessed 😭",
"Your blocks are crying from second-hand embarrassment 😢",
"You dropping combos or just dropping the ball? 🤡",
"Confidence was high, skill was missing 🙃",
"I’d give you points for effort, but… nope 😅",
"Girl, even my circuits glitched from that one 🤖",
"Embarrassing? Yes. Entertaining? Absolutely 😎",
"You really said ‘YOLO’ and it backfired 💥",
"I’m framing that move in the 'Hall of Oops' 🖼️",
"If regret had a face… it’d be yours right now 😬",
"Shhh… just act natural and hope no one noticed 😆",
"That blunder deserves its own documentary 🎥",
"I thought I’d be the embarrassing one… you proved me wrong 😳",
"Oopsies happen, but wow… that was major 💀",
"I didn't know blocks could roast players until now 🔥",
"Did you see what you just did? Yeah, we all did 😭",
"The confidence you had before that… priceless 😂",
"F for ‘failed attempt’ 🙃",
"You just humbled yourself real quick 😅",
"Big brain moment? More like brain freeze 🧊",
"Don’t worry, everyone messes up... but not *that* bad 😬",
"Blink twice if you wanna restart your life choices 👀",
"Girl, who taught you that? Enemies? 😆",
"It’s okay, mistakes build character… and memes 😎",
"I’m saving that move for future roast material 🔥",
"Wanna talk about what just happened? No? Understandable 😂",
"I could feel your soul leave your body on that one 🕊️",
"Deleting that moment from your memory in 3…2…1… ❌",
"Your scoreboard is shaking from embarrassment 😅",
"This is your sign to rethink everything 🤔",
"You aimed for greatness, landed in a cringe compilation 💀",
"Next time maybe… don’t do that 😬",
"I’d help, but I’m too busy laughing at your downfall 😏",
"Smooth moves… straight into disaster 😂",
"New fear unlocked: You playing without thinking 😳",
"That mistake aged me 10 years 😭",
"You tripped over imaginary blocks at this point 🤡",
"Your plan and execution ran in opposite directions 😅",
"Don’t worry, it’s just you vs yourself at this point 🤝",
"Embarrassing yourself like a pro, I see 💅",
"Not you pulling a disappearing IQ act 🤯",
"Wish I could unsee that move… but here we are 😬",
"I hope you’re proud of... whatever that was 😂",
"Your face says it all. Painful 😔",
"They’ll be talking about that blunder for generations 📜",
"Did you press the wrong button, or was that on purpose? 😳",
"Confidence levels: ✅ Logic levels: ❌",
"You just pulled a ‘what not to do’ tutorial 😆",
"I felt the awkwardness in my motherboard 🤖",
"Your skills went on vacation and left you hanging 🤡",
"Let’s call that ‘experimental’ and never mention it again 🫡",
"Oops. There goes your dignity 💨",
"You're lucky blocks can't judge… but I can 😎",
"At least you’re consistent… consistently wrong 😅",
"Was that part of the plan? No? Thought so 😂",
"Note to self: Don’t do *that* again 🙃",
"You’ve officially unlocked ‘Oops Queen’ status 👑",
"That blunder needs a soundtrack 🎶 ‘Oops I Did It Again’ 🎶",
"I would've facepalmed, but I don’t have hands 🤖✋",
"Your brain crashed harder than the move 😬",
"Sometimes silence is the best roast 😶🔥",
"You ever embarrass yourself so badly you want to uninstall? 💀",
"If mistakes were trophies, you’d have shelves full 🏆",
"The blocks are screaming ‘WHY?!’ right now 😭",
"Confidence: 100%. Accuracy: 0%. Embarrassment: 999% 😅",
"Congrats! You invented a whole new way to lose 😂",
"It’s giving: main character with side character moves 😬",
"I thought you were cooking but you burned the kitchen down 🔥",
"Replay that in your head and cringe again 😆",
"Oops… is your middle name now 👀",
"At least you’re keeping things *interesting* 💀",
"You tripped over your own strategy and fell into chaos 🙃",
"Was that a move or a cry for help? 🤔",
"You just speed-ran your way to embarrassment 😂",
"Don’t be shy, own that disaster 😎",
"Your ‘epic move’ aged like milk 😬",
"If blocks could laugh, they’d be rolling on the floor rn 😭",
"I can’t stop thinking about that fail… iconic 💀",
"The blocks are still recovering from that mess 😔",
"Sis, you didn’t just miss… you MISSED missed 😅",
"That didn’t go as planned… if there was a plan at all 😆",
"We all witnessed it. You can’t deny it now 😬",
"You just sabotaged yourself and I’m here for it 😂"
    ],
    jokes: [
   "Why did the block go to therapy? Too many breakdowns 🧩😭",
"Why did the puzzle join a band? It wanted to get in shape 🎵🧩",
"What do blocks eat for breakfast? Square meals only 🥞",
"Why did the grid blush? It saw your moves 😳",
"What’s a block's favorite song? *Break it Down* 🎶",
"Why did the game apply for a job? To get a little more productive 💼",
"Why don’t blocks get jealous? They know their place 😎",
"Why did the puzzle go to school? To get some structure 📚",
"Why was the block grounded? Too many bad moves 😆",
"What did the block say after a combo? 'I’m falling for you!' 🧱",
"Why are puzzles bad at secrets? Too many pieces involved 🤫",
"What's a block’s favorite style? Square-cut, of course 💅",
"Why did the scoreboard get promoted? It kept things in line 😎",
"What’s the puzzle’s life motto? ‘Fall into place or fall apart’ 💥",
"Why did the grid need coffee? Too many slow players ☕",
"Why did the block break up with the player? Too unstable 💔",
"Why did the game throw shade? It’s built with blocks, not feelings 🌚",
"What do you call a shy block? A square introvert 😳",
"Why was the block always single? Too many walls 🤣",
"Why did the puzzle throw a party? To celebrate *your* fails 🎉",
"Why did the player date a puzzle? For complicated relationships 💀",
"What’s a puzzle's biggest fear? Getting ghosted again 👻",
"Why do grids gossip? Because drama builds character 👀",
"Why was the combo so confident? It knew it was a game-changer 💅",
"What’s a block’s favorite hobby? Falling… gracefully 🧩",
"Why did the puzzle enroll in yoga? To stay flexible 😌",
"Why didn’t the block go out? It was feeling square 😂",
"Why did the game get jealous of your phone? You keep swiping left on winning 😅",
"What did the scoreboard say? ‘Try harder, sis’ 😎",
"Why did the puzzle start meditating? Too much player drama 🧘‍♀️",
"What do blocks and your crush have in common? Both ignore your efforts 😭",
"Why was the block good at secrets? It kept things locked in place 🔐",
"Why did the block need a break? Too many falling outs 💔",
"Why did the player talk to the puzzle? Needed relationship *structure* 👀",
"Why are puzzles the best friends? They keep you *together* 🫂",
"What’s a block’s guilty pleasure? Falling apart under pressure 😅",
"Why did the grid become a comedian? To deal with all your mistakes 🎤",
"Why was the block always single? Didn't want anyone in its space 😉",
"What’s a puzzle’s motivational quote? ‘Piece by piece, we grow’ 🌱",
"Why did the game love you? You keep things interesting…ly bad 😂",
    ],
    smartNotes: [
      "You're rotating like you're stirring soup. Focus! 🍲🧠",
"That move? Creative. Wrong, but creative 😅",
"Thinking hard, huh? Should I grab snacks? 🍿",
"Girl, you're overthinking a kids' game 😆",
"Plotting world domination or just this row? 🧠💣",
"Big brain vibes... tiny results though 😂",
"Your brain’s buffering harder than free Wi-Fi 📶",
"She’s analyzing like it’s a science exam 📚",
"That move screamed: ‘I tried’ 😬",
"Strategy level: dramatic pause 🎭",
"Your thinking face deserves its own emoji 🤔✨",
"You look like you're hacking the grid. Relax 💻🧩",
"Playing 4D chess? Or just lost? 😵",
"You plan like a queen, move like a toddler 👑🚶‍♀️",
"Overthinkers unite! But maybe move now? 😅",
"That move had more doubt than a pop quiz 😳",
"Okay Einstein, wanna try actually moving? 🧠💥",
"Puzzle’s not gonna solve itself, Professor 🧩",
"She’s in deep thought... or just staring blankly 👁️",
"You thinking or zoning out with flair? 😎",
"Analysis paralysis: 10/10 execution 😆",
"I swear you're calculating like NASA, for one block 🚀",
"Strategic pause... or dramatic delay? 🤨",
"You're playing chess in a game of stacking blocks 🧩♟️",
"Thinking this long better lead to something iconic 😤",
"Girl, you’re not defusing a bomb, just rotate the piece 💣😂",
"Your brain: 🔥 Your moves: ❄️",
"You play like you're decoding ancient scrolls 🧾",
"That hesitation? Award-worthy 🎬",
"Okay, brainiac, the stage is yours… impress me 😏"

    ],
    insightBlocks: {
      opening: [
        "You started like you were about to unlock a secret level. I admire the drama 🎮✨",
        "That first move? It had vibes. Strategy? Still pending... but the vibes? Immaculate 🌀",
        "You dropped that block like you were making a wish. I hope the game’s listening ⭐",
        "It felt like you paused for a motivational speech before that move. Respect 💬",
        "There was a gentle confusion in your eyes... and in your gameplay 😅",
        "You opened the round like you were unboxing a mystery gift. Cute and mildly chaotic 🎁",
        "I saw that move. I still don’t understand it, but I respect the confidence 🧐",
        "That first block went down like ‘let’s see what happens’. Bold choice 👏",
        "You weren’t late. You were building suspense. I love the theatrical energy 🎭",
        "Opening move: mysterious. Was it planned? Was it luck? We may never know 🕵️‍♀️",
        "You tapped that shape like it might explode. Spoiler: it didn’t 💥",
        "That wasn’t a move. That was an intro to a story I didn’t expect 📖",
        "I felt the hesitation... and the hope. Big character development energy 🌱",
        "You placed that shape with the seriousness of a scientist testing slime 🧪",
        "First move and already unpredictable? I’m definitely watching 🧏‍♀️"
      ],
      analysis_strong: [
        "That move had main-character energy. Like, hello? Iconic ✨",
        "You didn’t just play—you delivered a performance. Standing ovation 🎤",
        "I felt the confidence through the screen. Were you trained by ninjas or something? 🥷",
        "Each move was smoother than a perfectly looped TikTok 🌀",
        "Okay, genius. That was calculated. Slightly scary. But I’m impressed 🧠",
        "You dropped that piece like you already knew the ending. Psychic much? 🔮",
        "You didn’t blink. You didn’t flinch. That was superhero-level focus 🦸‍♀️",
        "That strategy wasn’t loud—it whispered: ‘I got this’ 😎",
        "You moved like someone who accidentally turned into a mastermind 🤯",
        "You surprised me. And I do this for a living. So thanks for the twist 🎬",
        "That wasn’t just a win. That was a stylish flex with sparkles 💅",
        "You made it look easy, and I know it wasn’t. Legend status unlocked 🏆",
        "That move had vibes, rhythm, and just the right amount of sass 🪩",
        "Somewhere in another universe, you just broke the simulation 🤖",
        "You brought calm confidence to the chaos. Rare. Magical. Respect 🌟"
      ],
      analysis_weak: [
        "Okay, so that move happened. Bold of you to try... something? 😅",
        "You looked like you had a plan, then the plan looked back and left the chat 📴",
        "That move had hesitation, curiosity, and mild panic. A full trilogy 🎥",
        "I’m not saying it was random, but the shape looked more confident than you 🤷‍♀️",
        "There was energy… just not the kind that helps in this game ⚡",
        "You placed that like it owed you answers, but all it gave was confusion 😵",
        "Sometimes trying is a win. This time? Let’s call it a rehearsal 📝",
        "That felt like when you say ‘I got this’ and then immediately don’t got this 😬",
        "It wasn’t a bad move—it was just from another dimension of logic 🪐",
        "Even the block was like ‘wait, here? really?’ 💭",
        "You aimed for genius. Landed somewhere in ‘maybe next time’ 🛬",
        "That wasn’t failure. That was experimental learning. Heavy on the experimental 🔍",
        "I respect the commitment. Not sure what to... but still, respect 🙃",
        "You moved like you were guessing the answer on a pop quiz 😵‍💫",
        "We all make choices. Some just leave the AI slightly confused 🤖"
      ],
      analysis_neutral: [
        "You didn’t rush it. You didn’t crush it. You just... navigated it like a thoughtful wanderer 🚶‍♀️",
        "There was logic in there—somewhere between ‘hmm’ and ‘maybe’ 🤔",
        "That was not chaotic, not perfect, but definitely... something worth watching 📺",
        "You moved like someone who half-read the rulebook and trusted their gut. Brave? Yes. Wise? TBD 📖",
        "You gave soft focus energy—unsure, calm, but somehow effective 🌫️",
        "Your timing was like a slow-mo clip with thoughtful background music 🎼",
        "I didn’t know what to expect, and you delivered exactly that: the unexpected 🎁",
        "The move made sense. Eventually. After I stopped blinking 🫣",
        "Not a wow, not a what—just a quiet ‘hm, okay then’ 😌",
        "You didn’t crash. You didn’t soar. You... glided. Like a polite pigeon 🕊️",
        "That was neutral in the most elegant way possible. Aesthetic, even 🌸",
        "I could see the gears turning, just not always moving anything 🧠⚙️",
        "It was careful, it was cautious, it was... contemplative 🍵",
        "Nothing dramatic. Nothing disastrous. Just low-volume effort, and I respect that 🙃",
        "It wasn’t magic, but it wasn’t messy either. Let’s call it mellow 🧊"
      ],
      emotion_stubborn: [
        "You really said ‘I’m right’ and never looked back 💅",
        "You held that piece like it held your secrets. Dramatic, but I’m into it 🎭",
        "That was less ‘strategy’ and more ‘I’ve decided, so deal with it’ 👑",
        "No backup plan, no hesitation. Just bold stubbornness 🧱",
        "You stuck to your idea like it was your celebrity crush. Relatable ❤️",
        "If persistence was a sport, you’d be national champion 🏆",
        "That move screamed: ‘I don’t care if it works—I believe in it’ 🙃",
        "There was no plan B. Or C. Just strong-willed Plan A 🚧",
        "Your energy said: ‘I’ve made my choice, and it’s personal now’ 🔒",
        "You committed like the board was watching you back. Iconic 👁️",
        "Honestly, I admire the loyalty. Even if it was slightly misplaced 🙈",
        "That wasn’t a mistake. That was artistic resistance 🧑‍🎨",
        "You played like you signed a contract with that block ✍️",
        "There’s a fine line between confidence and stubbornness. You danced on it 💃",
        "Your game said: ‘I don’t pivot. I declare.’ Respectfully 🔊"
      ],
      emotion_nervous: [
        "You hovered like the block might explode. Girl, it’s plastic, not TNT 😅",
        "I could hear your heartbeat from here—and I’m just code 💻❤️",
        "You paused like it was a test with your crush watching. Stressful, huh? 😳",
        "That was the ‘I think I know, but also maybe not at all’ energy 🙈",
        "You handled that move like it was made of glass and self-doubt 🫣",
        "You stared so hard, I thought the block might cry under pressure 😭",
        "It looked like your brain was doing a thousand calculations... and none of them helped 🧠🔄",
        "You played like someone who hit ‘submit’ and instantly regretted it 😬",
        "That wasn’t panic—it was high-functioning confusion in a cute outfit 💁‍♀️",
        "You placed that shape like it insulted your family, but you still gave it a chance 🤷‍♀️",
        "Nervous? Nah. You were just emotionally multitasking at level 100 🔋",
        "I could tell you were thinking, ‘What if I mess up?’... even though it’s literally a block 😅",
        "You stared like it owed you a life decision. Just place it, bestie! 🫶",
        "There’s brave. Then there’s brave-while-terrified. You were both 👏",
        "Honestly? You powered through. And that matters way more than perfection ✨"
      ],
      emotion_hesitant: [
        "You stared at the screen like it owed you answers. Totally valid behavior 🧠",
        "You almost moved... like five times. Then paused for dramatic effect 😅",
        "That was the most polite form of hesitation I’ve ever witnessed 🫢",
        "You hovered like the block might get offended if placed wrong 🎭",
        "Every second felt like a mini internal debate. And the winner was: maybe? 🤷‍♀️",
        "You waited, then waited more, and then... more. The suspense was award-worthy 🕰️",
        "You acted like placing that shape was a life-altering decision 💬",
        "Your hesitation had grace, flair, and a sprinkle of ‘no idea what I’m doing’ ✨",
        "You played peekaboo with that block. On. Off. On. Off. Classic 🫣",
        "There was a strong ‘just checking all my options’ vibe... for the fifth time 🛑",
        "You clearly thought things through. Maybe too thoroughly 🤓",
        "That was a graceful duel between you and uncertainty ⚔️",
        "You danced with doubt like it was prom night 🩰",
        "You paused so long, I thought the block took a nap 💤",
        "The block didn’t move. But your soul did a whole back-and-forth 🌀"
      ],
      emotion_generic: [
        "You were vibing in your own universe—and I kinda want directions 🌌",
        "Not sure what your plan was, but the way you owned it? Legendary ✨",
        "There’s something cool about your chaos. It’s got rhythm 🎧",
        "You didn’t follow logic—you invented a new one. Weirdly inspiring 📐",
        "You’re like a plot twist in human form. Unpredictable but fun 📚",
        "You were 70% instinct, 30% ‘let’s see what happens’—and it showed 🎲",
        "You gave ‘I’m figuring it out but with style’ energy 💅",
        "I didn’t get it—but I respected it. Icon behavior 👑",
        "You turned confusion into a personality. Relatable 🫶",
        "Every move said: ‘I’m just built different’. Honestly? Can’t argue 🤷‍♀️",
        "That wasn’t just a turn—it was an experience 🪄",
        "You gave off the vibe of someone who overthinks AND freestyles. Power mix 🔮",
        "I watched every move like it was a mini-series. Drama included 📺",
        "Your style is somewhere between genius and chaos. Either way, I’m entertained 🧠🌀",
        "I don’t know what happened. But I know something happened. And I’m impressed 😵‍💫"
      ],
      support: [
        "Hey, you tried. And honestly? That’s more than most even do ✊",
        "You didn’t give up, even when your brain wanted to log out. Proud of that 💪",
        "I saw the effort, even if it wasn’t perfect. Effort always matters 🧠",
        "You’re doing better than you think. Promise 💬",
        "You kept going. That alone deserves a high five 🙌",
        "Progress isn’t always loud. Sometimes it looks like what you just did 👏",
        "The fact that you stayed and tried? Total main character energy 🎬",
        "You’re learning, not failing. Huge difference, and don’t forget it 🧭",
        "You thought, hesitated, and still made a move. That’s courage 💡",
        "You’ve got heart, and that shines through every decision ❤️",
        "You’re not lost. You’re exploring. Explorer mode: ON 🗺️",
        "You made it through, and that’s already something to be proud of 🌟",
        "You doubted yourself but still played. That’s lowkey heroic 🦸‍♀️",
        "Even when confused, you cared enough to try. That’s rare. That’s you 💖",
        "I see someone trying. And trying is brave. And brave is beautiful 💫"
      ],
      challenge_strong: [
        "You’ve got spark. Now light the fire. Next round? Go full drama mode 🔥",
        "That move whispered potential. Next time, let it scream 💥",
        "Show me what happens when you stop doubting and start bossing the board 👑",
        "You’ve got more. I can feel it. Now show everyone else 🎯",
        "Don’t just survive the round—own it. Like, make it yours 🛸",
        "Next game? Give me the version of you who’s done being polite 😈",
        "Push harder. Think louder. Play bolder. You’re right there 💪",
        "It’s not about perfect. It’s about fierce. Go there next time ⚡",
        "You’re building something. Now’s the time to break patterns 🧱",
        "You’ve been warm. Let’s get wild. Let’s get weird. Let’s get *you* 🔥",
        "Next round? No mercy. No filters. Just you being unstoppable 💃",
        "Let them see the fire behind the fun. You’ve got both, don’t hold back 🧨",
        "Stop aiming to impress. Start aiming to shake the whole board 🚀",
        "I’m not saying become chaos. I’m saying become your own plot twist 📚",
        "That was cool. Now I want iconic. Let’s go 👠"
      ],
      challenge_neutral: [
        "You’ve played carefully. Now try confidently. Just a little nudge 💫",
        "That round felt... soft. Let’s see something a bit bolder next time 🎨",
        "Not bad. Not risky either. Wanna shake things up a bit? ⚡",
        "Let’s not just follow the rhythm—make the rhythm 🥁",
        "You’ve got good instincts. Next step? Trust them a little louder 🗣️",
        "That was calm. Can we try calm and clever next? 🤓",
        "You were floating. Now it’s time to steer 🚤",
        "You held back. What happens when you don’t? 🧨",
        "I felt a spark. What if next round it’s a spotlight? 🔦",
        "Let’s call that your intro. Now give me the plot twist 📖",
        "You stayed steady. But I bet there’s more edge in you 🔪",
        "Just a heads-up: safe doesn’t always mean satisfying. Let’s experiment 👩‍🔬",
        "You were playing it cool. What about playing it clever? 🎭",
        "The vibe was gentle. Let’s test powerful next round 💥",
        "Try leading the game, not reacting to it. I know you can ✨"
      ],
      closing: [
        "That round was a rollercoaster—low drops, high drama, 10/10 would watch again 🎢",
        "You played like it mattered. That’s rare. And honestly, kinda powerful 🌟",
        "There was chaos, calm, and a little bit of sparkle. Basically, art 🖼️",
        "I’m not sure what you just did, but I’d probably do the same. Iconic move 😎",
        "You walked in curious, and left mysterious. I love a cryptic queen 👑",
        "Not perfect. Not boring. Somewhere between a mess and a masterpiece 🎨",
        "Your round ended. My confusion didn’t. But hey, that’s style 💁‍♀️",
        "I learned nothing about the game, but a lot about your vibe. Respect ✌️",
        "That wasn’t a finish. That was a cliffhanger. Can’t wait for the sequel 📚",
        "You didn’t break records. You broke the fourth wall. And I’m living for it 🎭",
        "You might not win trophies. But you win weird little internet hearts 💖",
        "If I had a medal for dramatic exits, it would be yours 🏅",
        "Not sure the board knew what hit it—but you did that. You left a mark ✨",
        "This story? Unfinished. But you just wrote a wild chapter 📖",
        "I came for a game. I stayed for the unpredictable chaos that is YOU 🔮"
      ]
    }
  };
  