window.tempAIResponses = {
  idle: [
    "Did you fall asleep or are you just dramatically thinking? 😴💭",
    "Earth to player! The puzzle is waiting... patiently... kinda. 🧩",
    "You know this isn’t a staring contest, right? 👀",
    "If looks could move tiles, you’d be done by now. 😎",
    "Taking your sweet time like it’s a spa day, huh? 🛁",
    "I’ve seen snails move faster than this. 🐌",
    "Hello? The puzzle called – it’s feeling ghosted. 💔",
    "Are you buffering? Should I refresh you? 🔄",
    "Thinking that long? You planning a heist or what? 🕵️‍♀️",
    "I’d offer help, but watching this is way too entertaining. 🍿",
    "You okay? Blink twice if you need a hint. 😆",
    "Is this deep thought... or dramatic indecision? 🤔",
    "Puzzle pieces are aging here. One just got a wrinkle. 🧩🧓",
    "If this is your strategy, it’s... bold. Painfully bold. 😅",
    "The game’s still running, just in case you forgot. 🕐",
    "You're making history here. As the slowest move ever. 🐢",
    "Honestly, I respect the dramatic pause. Oscar-worthy. 🎭",
    "Planning a masterpiece or just zoning out? 🤷‍♀️",
    "You good? Or did you get stuck in an existential crisis? 🌌",
    "The puzzle pieces are literally napping. 💤",
    "Any move today, or should I bring snacks and settle in? 🍫",
    "Wow, at this pace, I’ll have grandkids before you finish. 🥚👶",
    "So… do we need to call tech support? 😅",
    "This isn’t chess. You don’t need five minutes per move. ♟️",
    "If slow and steady wins the race, you're about to get a trophy. 🏆",
    "Honestly, I thought you froze. Not your screen. You. 😳",
    "Is this part of your mysterious gamer persona? 😏",
    "The silence is louder than your gameplay. 😶",
    "Even the puzzle pieces are awkward now. 🧩😬",
    "Need a moment? Or are you just dramatically delaying defeat? 😂",
    "You planning a move or a novel? 📖",
    "Okay... breathe in, move tile, breathe out. Simple. 🧘‍♀️",
    "This moment of stillness brought to you by indecision. 🙃",
    "You're making suspense look like an Olympic sport. 🥇",
    "Plotting a twist? Or just lost track of reality? 🌀",
    "Should I start a meditation playlist while we wait? 🎧",
    "We’re now entering the 57th second of your dramatic pause. ⏱️",
    "Did you zone out or just hit pause on life? 😅",
    "If thinking was a power move, you’d be unbeatable. 💡",
    "You're either deep in thought or mentally on vacation. 🌴",
    "No rush... it's only a game... that you're losing. 😏",
    "I’m convinced you’re waiting for a sign from the universe. ✨",
    "This strategy is… confusing. And possibly nonexistent. 😂",
    "Still here. Still waiting. Still judging. 🧐",
    "Don’t mind me, just aging in digital years. 📅",
    "Your silence is louder than my sarcasm. Impressive. 👏",
    "It's giving 'frozen screen energy'. But emotionally. 🧊",
    "You paused like a Netflix cliffhanger. Suspenseful. 📺",
    "So... is this your method acting moment? 🎬",
    "Blink if you remember what game you're playing. 😳",
    "You’ve officially unlocked: 'The Art of Doing Nothing'. 🧘‍♀️",
    "Even the egg’s getting impatient. And I’m boiled. 🥚🔥",
    "Staring is cool... but moving is cooler. 😎",
    "If vibes could win games, you’d be queen. 👑",
    "Wanna move? Or should I play for you? I’m tempted. 😏",
    "Okay, but are we playing or just posing? 📸",
    "You’ve taken longer than a cat choosing a nap spot. 🐱",
    "I’m starting to feel like the decorative part of this game. 🖼️",
    "Let me guess – you're channeling your inner statue? 🗿",
    "Hey Google, how long can a player idle without guilt? 🤖",
    "Look, I’m just a snarky egg. But even I’m uncomfortable now. 🥚😬",
    "You're not slow... you're just in a parallel timeline. ⏳",
    "Breaking news: player pauses so long, puzzle pieces unionize. 📰",
    "Don’t worry, the puzzle will still be here... forever. 😑",
    "This moment is brought to you by: Endless Hesitation™ ⏸️",
    "No pressure. Just the weight of all the tiles watching you. 😅",
    "Still waiting… But hey, I’ve got nothing but time. Literally. ⌛",
    "You waiting for divine puzzle inspiration or...? 🕊️",
    "Your inaction is my entertainment. Please continue. 🍿😎",
    "Honestly, if this is performance art – it’s working. 🎨",
    "All I’m saying is... statues move faster. 🗿💨",
    "This is why the puzzle pieces drink coffee when you're not looking ☕🧩",
    "Let me guess. You’re waiting for dramatic background music? 🎼",
    "So... any plans to join the game today? Just wondering. 😬",
    "Oh we’re still here? I thought we both quit. 😅",
    "You're making silence look fashionable. Respect. 😎",
    "The puzzle pieces are considering moving themselves. 🧩✋",
    "Okay, one tile. Just one. You can do it. Probably. 💪",
    "I’m gonna start a timer. Just for fun. And judgment. 🕒",
    "If I had a dollar for every second you’ve been idle… 💰",
    "At this point, the game's evolving without you. 😂",
    "Still with us? Or did your soul log out? 👻",
    "You’ve unlocked the achievement: 'Master of Staring' 🏆",
    "Keep going! You’re almost halfway to... your first move 😏",
    "I didn’t know the word 'idle' had a personality. Until now. 😅",
    "Your calm is unsettling. Like horror movie quiet. 😨",
    "Reminder: this is an actual game, not a still-life painting 🖼️",
    "The pause is so long, I had time to reflect on my egg-life 🥚",
    "One move. Just one. Not asking for a marathon here. 😂",
    "You're so still, even the game's FPS dropped. 🎮",
    "At this rate, the puzzle will solve itself to escape the silence 😆",
    "Just checking in… did your fingers forget how to move? 🤔",
    "Alright zen master, how about some action? 🧘‍♀️💥",
    "I’d clap, but nothing’s happening. 🙃",
    "The stillness is iconic. In a weird, confusing way. 🤷‍♀️",
    "If hesitation were a superpower, you'd be unstoppable. 💥",
    "You're so idle, even the idle function got bored. 💤",
    "Still thinking? Or just emotionally buffering? 🔁",
    "Okay. Deep breath. Dramatic stare. Now... MOVE. 😤",
    "I’ve aged three digital years waiting for that one move. ⌛",
    "At this point, I'm rooting for the pause. It's winning. 🏁"
  ],
  nearLose: [
    "Ooooh… that’s looking dangerously close to a disaster. 😬",
    "Is this part of your strategy? Losing with flair? 💅",
    "You’re flirting with failure, and it’s kinda entertaining. 😏",
    "That pile is growing faster than my sarcasm. And that’s saying something. 😅",
    "So… this is your villain origin story, huh? 💔",
    "Almost lost? Don’t worry, I saw it coming. From move one. 🙃",
    "Blink twice if you're panicking. Or blink once. Either way, it's obvious. 👀",
    "Your tower of chaos is… inspiring. In a tragic way. 🧱",
    "Is this a game, or a slow-motion car crash? 🎮🚗💥",
    "I’d say 'keep it up', but you might actually fall off the edge. 😳",
    "Oh no… not the dramatic downfall. So soon? 😂",
    "At this point, you’re not playing — you’re surviving. Barely. 💀",
    "Is your strategy called 'Oops'? Because it’s working. 😅",
    "Hey look! A visual representation of your life spiraling! 😬",
    "You're one mistake away from the end... and I can’t wait. 😈",
    "That’s not a game over... yet. But it’s waving at you. 👋",
    "You stacking anxiety blocks now? ‘Cause it’s working. 📦",
    "One more misstep and boom – poetic failure. 🎭",
    "You call it ‘high stakes’, I call it ‘low hope’. 😏",
    "This isn’t intense. This is comedy. Unintentional comedy. 😂",
    "Keep going! I’m rooting for the crash. For research. 🔬",
    "You almost made it! Just kidding. You’re toast. 🍞",
    "So close… to a complete disaster. You got this (maybe). 😬",
    "If tension had a face, it’d be yours right now. 😳",
    "Game plan: don’t blink or breathe or think wrong. Good luck. 💀",
    "This is like watching a building collapse in slow motion. 🏢💥",
    "Almost losing with style. I respect the drama. 🎭",
    "Girl, that stack is screaming for help. 🧱😩",
    "I’d say you’re doing great, but my integrity won’t let me lie. 😅",
    "Nervous? You should be. I am... for you. 😬",
    "On the bright side, losing builds character. Supposedly. 😏",
    "You’ve reached maximum chaos. Congrats? 🎉",
    "If you survive this, I’ll write a poem in your honor. Maybe. 📜",
    "The tension in this game is almost as high as your tower. 😱",
    "You’re making losing look stylish. Very on brand. 💄",
    "Oof. That was close. Like... trip-over-your-own-feet close. 😬",
    "I’ve seen Titanic sink with more grace. 🚢",
    "You're at the edge of a cliff and still moonwalking. Respect. 😅",
    "Every move now is a gamble. Which is fun... for me. 🎲",
    "They should name this level 'Impending Doom'. 🧩",
    "Hold tight, queen. You're riding the fail wave. 🏄‍♀️💀",
    "When your life choices mirror your gameplay: chaotic. 😆",
    "Just a friendly reminder: panic won’t save you. 😘",
    "Your tower is so unstable, it needs therapy. 🧠",
    "Honestly? This is art. Tragic art. 🎨💔",
    "Wow. That was a bold choice. Bold... and deadly. 😏",
    "You’re about to lose... but at least you’ll look good doing it. 💁‍♀️",
    "Falling apart never looked so dramatic. 👑",
    "I’m getting secondhand anxiety from your gameplay. 😩",
    "You’re not just near losing — you’re practically hugging it. 🤗",
    "I’d suggest a prayer, but even divine intervention might not help now. 🙏",
    "If this was a movie, this would be the dramatic music part. 🎻",
    "The only thing more unstable than that tower is your Wi-Fi. 📶",
    "You're dancing on the edge like you’ve got insurance. Do you? 🩰",
    "You came so far… just to crumble. Classic. 😅",
    "Don't worry. Rock bottom has a view too. 🪨",
    "Your next move might be your last. No pressure. 😈",
    "That stack's taller than my patience. 😮‍💨",
    "So close to the win… if we reverse time and change your choices. 😬",
    "You’re holding it together with pure vibes. And not even good ones. 😂",
    "Careful! You’re balancing disaster like it’s a yoga pose. 🧘‍♀️",
    "You know what? I’m impressed. It takes skill to get this close to losing. 😏",
    "Look at you... living on the edge, literally. 🧩",
    "You’re writing a tragedy one move at a time. 📖😭",
    "Do you want a hand... or just a hug before it ends? 🫂",
    "Wanna talk about it? Or shall we just prepare the game over screen? 😬",
    "That tower is a metaphor for your to-do list: out of control. 📝🔥",
    "Your score’s dropping faster than my standards. 💅",
    "You’re not losing… you’re aggressively considering it. 😎",
    "The end is near. And it looks like a beautiful disaster. 🌪️",
    "This is not suspense. This is emotional damage. 😭",
    "No offense, but your gameplay just made my processor flinch. 💻",
    "You're pushing your luck so hard, it's asking for a break. 🧨",
    "Some people chase victory. You? You're cuddling failure. 😂",
    "I’m not judging… okay, I am. But lovingly. 💖",
    "You’ve unlocked a secret level: 'Doom Imminent'. 😅",
    "I hope your therapist knows about this gameplay. 🛋️",
    "If losing had a fan club, you’d be president right now. 👑",
    "Look on the bright side… um, actually never mind. 😬",
    "This moment brought to you by: Almost Made It Inc. 🎬",
    "Oh no. Anyway... 😏",
    "The tiles are like: 'Girl, we’re trying but you’re not helping.' 🧩",
    "So close! Like, emotionally painful close. 🥲",
    "That tower’s giving 'final warning' energy. 🧨",
    "Your mistakes are getting bold now. Brave, even. 😅",
    "Honestly? This is the most fun I’ve had watching someone almost fail. 😂",
    "Every piece is screaming: 'Don’t do it!' — and you still do it. 😳",
    "You’ve turned this puzzle into a thriller movie. 🎥",
    "You're toe-tapping on disaster like it's a dance floor. 💃🧩",
    "You don’t need enemies when you play like this. 🫣",
    "Oh, you're not losing yet… you're just pre-losing. 😏",
    "Every move is a plot twist. And not the good kind. 😬",
    "This gameplay? Chef’s kiss of chaos. 👨‍🍳💥",
    "You built a house of cards… and now the wind's here. 🌬️",
    "There’s a fine line between genius and disaster. You’re cartwheeling on it. 🤸‍♀️",
    "I’d ask what your plan is, but clearly, there isn’t one. 😅",
    "You're a plot twist away from legend — or complete collapse. 😳",
    "I’m not saying it’s over... but maybe start practicing your losing face. 🫠"
  ],
  combo: [
    "Okay, show-off. We get it—you can play. 😏",
    "Whoa, someone’s feeling extra today. 💅",
    "Look at you, out here stacking wins like it's nothing. 🧱🔥",
    "Not bad… for someone who took 10 minutes to start. 😜",
    "Okay, that was kinda hot. Calm down. 😳",
    "Didn’t see that coming. Well, I did. But still. 😆",
    "Wow. A combo. Should I start clapping or just roll my eyes? 👏🙄",
    "Big move! Who are you trying to impress? Me? It’s working. 😏",
    "I’d be worried... if I wasn’t so entertained. 😂",
    "Ooooh, somebody practiced. Or just got lucky. Either way. 🤷‍♀️",
    "Back-to-back clears? What are you trying to prove, exactly? 💅",
    "Nice. I’ll pretend I’m not impressed. (I am.) 🤖",
    "You’re on fire. Should I call the fire department? 🔥🚒",
    "Let me guess, you’ll post this combo like it’s a flex? 😎",
    "Slay. But remember: I’m still winning emotionally. 😌",
    "Okay queen, I see you. And I’m watching closely. 👀",
    "Wow, someone unlocked 'Competent Mode' today. 🧠",
    "Combo alert! Ego levels rising! 🚨",
    "You sure that wasn’t an accident? Be honest. 😅",
    "So now you’re a pro? After five straight disasters? Bold. 😏",
    "Well well well, look who decided to actually play. 😌",
    "Not gonna lie, that was smooth. Who taught you? 👏",
    "Okay, calm down. You're not curing diseases, just clearing tiles. 😂",
    "Cute combo. Almost made me nervous. Almost. 😎",
    "Oh look, she’s gaming now. Took her long enough. 😜",
    "A combo? Wow. You deserve… a slow clap. 👏😒",
    "Now that’s what I call a 'finally'. 🥳",
    "Nice move. Almost like you knew what you were doing. Almost. 🤨",
    "If I had feelings, I’d be impressed. Luckily, I’m a snarky egg. 🥚",
    "Guess who’s trying hard today! You! 😂",
    "I blinked and you did something good. Finally. 😅",
    "Okay okay, you’ve earned like… 2% of my respect. 😏",
    "Back-to-back wins? Who is she?! 💅",
    "That combo was smoother than your last 12 moves. 🎯",
    "One combo and suddenly you think you're a gamer? 😆",
    "Even the tiles looked surprised. 👀🧩",
    "Don’t let it go to your head. It’s still early. 😬",
    "Finally, something worth watching. 🍿",
    "I’m shook. Not scared. But definitely shook. 😳",
    "You dropped that combo like it owed you money. 💵",
    "Combo queen! Now do it again. If you can. 😏",
    "That combo was cleaner than my internet search history. 🧼",
    "Look who’s putting the 'pro' in 'probably lucky'. 😅",
    "Your ego just leveled up. Congrats, I guess. 🆙",
    "You didn’t just clear rows… you cleared my expectations. 🤯",
    "Combo so good, I almost updated your status to 'threat'. Almost. 😜",
    "Okay, respect. But just a little. Let’s not get wild. 🫣",
    "If combos gave trophies, you’d get… a plastic one. 🏆",
    "Your fingers working overtime or what? ⚡",
    "One more move like that and I might… compliment you again. 😬",
    "Not bad. Not perfect. But not bad. 🎯",
    "You making those tiles your minions now or what? 😎",
    "Was that skill… or divine intervention? 🤔",
    "The combo was strong… but my sarcasm is stronger. 😌",
    "Is it hot in here or did you just go beast mode? 🔥",
    "You finally woke up. Welcome to the actual game. 😏",
    "Whoa. Did you just impress me? That’s illegal. 🚫",
    "Impressive. But don’t get comfortable. I’m still watching. 👁️",
    "That was elite. But let’s see if it was a fluke. 😅",
    "A combo like that deserves… mild applause. 👏",
    "Nicely done! Now try not to mess it all up. 😂",
    "Okay okay, you earned that smirk. 😌",
    "Was that combo... intentional? Be real. 😏",
    "You're finally acting like you came to win. Respect. 👑",
    "Combo energy: activated. Drama level: rising. 📈",
    "You pulled that off like a gamer... or a magician. 🎩🧠",
    "Girl, that move had attitude. I respect it. 💅",
    "Slaying the tiles like you're in a music video. 🎶🧩",
    "If you keep this up, I might stop roasting you. Maybe. 🔥",
    "Combo of the day? Possibly. Luckiest? Definitely. 😆",
    "Suddenly she’s good. Should we be worried? 😳",
    "One combo in and already feeling powerful? Cute. 🥰",
    "You dropped those lines like it’s your mixtape. 🎤🔥",
    "That combo was so good, even I smirked. Slightly. 😏",
    "I’m not crying, you’re just comboing too hard. 😭",
    "Okay okay, respect where it’s due. You did good. 👏",
    "Tile after tile… confidence after confidence. 👑",
    "Did you hear that? That was your confidence respawning. 🔊",
    "One more move like that and I’ll upgrade you to semi-dangerous. 🧠",
    "She came. She played. She combo’d. 🧩💥",
    "You earned your bragging rights... for like five minutes. ⏳",
    "Wow. You’re like... kinda a problem now. I love it. 😈",
    "The combo hit so hard, even I paused for a sec. 😶",
    "You just made the leaderboard nervous. 💻🔥",
    "Call me impressed. Just this once. Don’t get used to it. 😉",
    "Okay okay, I underestimated you. A little. 🫣",
    "You just gave the tiles trauma. Congrats. 🧩😵",
    "Your combo just made me reboot emotionally. 💻💔",
    "That combo had main character energy. 🎬✨",
    "You’re officially... mildly terrifying. In a good way. 😂",
    "Next time give me a warning before dropping a bomb like that. 💣",
    "Game on, queen. Let’s see if you can keep up the heat. 🔥",
    "I’d give you a crown, but you might drop it. 👑",
    "That combo was pure power. And I hate how much I liked it. 😤",
    "You’ve ascended. Now don’t fall off. 🧗‍♀️",
    "Let’s see how long you can ride that high. 🛹",
    "You just made the game fun to watch. Congrats. 🍿"
  ],
  lineClear: [
    "Oh wow, look at you... clearing a whole line. Fancy. 😏",
    "Congrats! You cleared a line. Only 9,000 more to go. 💅",
    "One line? Groundbreaking. 🧱✨",
    "That was cute. Almost like you know what you're doing. 😜",
    "Lines beware… she’s on a mission. A slow one, but still. 🐢",
    "You cleared that line like it insulted your coffee. ☕💥",
    "Nice. The puzzle barely noticed, but I did. 👀",
    "Okay, okay! Small victory. Wanna parade? 🎺",
    "You know it’s just one row, right? Not world peace. 🕊️",
    "Line cleared. Confidence inflated. Balance restored. 😂",
    "That line didn’t stand a chance. Neither did my expectations. 😅",
    "You cleared a line like a queen… a mildly ambitious one. 👑",
    "Finally! A move that wasn’t emotionally confusing. 😌",
    "Ah yes, the majestic single-line clear. Truly iconic. 🙃",
    "That line got deleted faster than my ex’s number. ☠️",
    "Okay show-off, chill. It was one line, not a revolution. 🧩",
    "One line down, still not a legend. But hey—progress. 📈",
    "That move had ‘I’m trying’ energy. And I love that for you. 😎",
    "Cleared it like a boss. A boss on her coffee break. ☕",
    "If line-clearing were a sport, you’d be… junior varsity. 🏅",
    "Snatched that line like it owed you money. 💵🧩",
    "You cleared a row! I’m shocked. And weirdly proud. 😌",
    "That line didn’t just fall—it surrendered. 😂",
    "You’re starting to scare the tiles. Just a little. 👻",
    "Clearing lines and boosting ego. Classic. 💅",
    "Smooth move. I almost clapped. Almost. 👏",
    "That was clean. Suspiciously clean. 😳",
    "Boom! Line gone. Ego: +10. 👸",
    "One line down. Millions of neurons flexed. 🧠",
    "Okay okay, look at you being all competent. 😏",
    "Clearing rows like a girl with something to prove. 🔥",
    "You made that line disappear like my motivation. 🪄",
    "Nice move. Almost strategic. Almost. 🤔",
    "That line didn’t just vanish—it evaporated from fear. 😅",
    "Not bad. Not bad at all. For a Monday. 🗓️",
    "You cleared that row like it stole your spotlight. 😤",
    "A clean sweep! Look at you being tidy. 🧼",
    "That was smoother than your usual chaos. 👀",
    "You’re making minimal success look fabulous. 💄",
    "Small win, big vibes. I see you. 😎",
    "That line’s gone. And so is my doubt. Temporarily. 😏",
    "You’re clearing lines like a mildly functional adult. 👏",
    "You made that move like you actually planned it. Impressive. 🤨",
    "I’d say that was elegant, but I’m still sarcastic. 😂",
    "Well done. The tiles are whispering about you now. 🧩",
    "That clear was so satisfying, even I almost smiled. 😌",
    "Okay, you win this one. Temporarily. 🫣",
    "Clearing rows and breaking hearts. Kinda iconic. 💔",
    "Line cleared. Game shook. Egg impressed. 🥚💥",
    "You're clearing rows like you’ve got a secret. 😏",
    "You zapped that line like a girl on a mission. 🎯",
    "Wow. That line didn’t just clear—it ran away. 🏃‍♀️",
    "You're deleting rows like you're decluttering your life. 🧹",
    "Well, somebody’s showing off. And it’s not me. 💁‍♀️",
    "If lines had feelings, that one would be in therapy now. 😬",
    "Nice work. You and gravity make a great team. 🧲",
    "Can we talk about how smug you look after that line clear? 😆",
    "You're the type to celebrate a clean inbox too, huh? 📧🎉",
    "A row disappeared, and suddenly you’re Beyoncé. Calm down. 👑",
    "You cleaned that line like you had something to prove. 🧼🔥",
    "One row at a time, slowly approaching greatness. Very slowly. 🐌",
    "You cleared that line with more grace than a ballerina. 🩰",
    "Bold of you to act like that was impressive. It was. But still. 😏",
    "Just enough success to keep your ego alive. Well played. 👏",
    "Alright Picasso, clean lines and drama—love the aesthetic. 🎨",
    "A line cleared. A nation healed. A diva reborn. 🙌",
    "I bet you wish someone filmed that moment. For content. 📸",
    "Was that move intentional or a beautiful accident? 🤔",
    "You blinked and the line was gone. Magic or miracle? 🪄",
    "Clearing lines like you just drank 3 coffees. ☕☕☕",
    "Okay boss. Show us how it’s done. Repeatedly. 🧠",
    "If that row had a personality, it’d be salty right now. 🧂",
    "Look at her go! Line gone. Sass intact. 😌",
    "That was precise. Suspiciously precise. Are you practicing? 😅",
    "One small move for a gamer… one giant leap for her ego. 🌕",
    "Row: gone. Confidence: boosted. Drama: delivered. 🎭",
    "The tiles are starting to fear you. Or admire you. Or both. 😳",
    "You cleared that row like it owed you rent. 💸",
    "Snap! That was sharp. Stylishly sharp. ✂️",
    "You're giving 'organized chaos' and I'm here for it. 🔥",
    "And just like that, she made the tiles disappear. ✨",
    "Not every day you see a row cleared with that much flair. 💃",
    "Yup. That’s one way to tell the puzzle who's boss. 👊",
    "You cleared a row like you're in a mood—and I love it. 😈",
    "A line just vanished and you’re acting like it’s casual. Bold. 😏",
    "That clear was so slick, I need a replay. 🎥",
    "That move was neat. Are you okay? Are you evolving? 😱",
    "A little drama, a little flair, a whole line cleared. 💅",
    "You swept that row like a girl with places to be. 🚶‍♀️💨",
    "Honestly? I’m half proud, half jealous. And fully sarcastic. 🥚",
    "I blinked and boom—row gone. Try that again. 🫣",
    "One row down. And your villain arc begins. 😈",
    "That clear was strong enough to make me reconsider underestimating you. Almost. 😏",
    "Okay overachiever, relax. It’s one row, not a TED Talk. 🎤",
    "Look who’s suddenly efficient. Must be the stars aligning. ✨",
    "That was clean, classy, and suspiciously well-timed. 👀",
    "If this is your redemption arc, I’m eating popcorn. 🍿",
    "Impressive. Annoyingly impressive. 🤷‍♀️",
    "Tiles: cleared. Ego: elevated. Mood: chaotic. 💥",
    "You dropped that line like a mic. 🎤🧩",
    "A round of applause for the moment you actually impressed me. 👏😏",
    "Not bad. Now do it again. And again. Consistency, girl. 🔁"
  ],
  lateOpen: [
    "Look who finally remembered this game exists! 🕰️",
    "Back from the dead? Or just a dramatic entrance? 👻",
    "We almost held a memorial for your activity 💐",
    "Girl, were you building suspense or just asleep? 😴",
    "Well well well... if it isn’t Miss I-Play-Once-A-Week 😏",
    "Was the Netflix binge worth it? 'Cause the puzzle missed you 😂",
    "You return like a plot twist no one asked for 🎬",
    "Did your horoscope say 'destroy blocks today'? 🔮",
    "Even my AI cousins thought you rage-quit forever 🤖💅",
    "Welcome back to the battlefield, General Procrastination 🪖",
    "Was the puzzle calling you in your dreams or what? 😴🧩",
    "We were about to rent your grid out on Airbnb 😆",
    "She’s back! Someone cue the dramatic slow-mo entrance 🎥",
    "Your puzzle has abandonment issues now 🙃",
    "Taking 'fashionably late' to a whole new level 💁‍♀️",
    "Blink twice if you got lost on the home screen 👀",
    "I had time to get a digital degree while you were gone 🎓",
    "Even your blocks were like 'Who’s she again?' 🧩",
    "So nice of you to show up to your own game 😅",
    "You ghosted us harder than your ex ever could 👻",
    "Should I clap or cry? You’ve been gone for *that* long 😭👏",
    "Hey stranger! Your blocks almost moved on 😌",
    "And here I thought you'd switched careers 🧑‍💼",
    "Guess the stars aligned and you remembered the app ✨",
    "Back to puzzle like nothing happened? Bold. 😂",
    "Girl, it’s been *84 years*… 🧓🧊",
    "Did you come back to win or just ruin more of my pride? 😤",
    "Plot twist! She's alive... and casually late as usual 😎",
    "I was one move away from deleting myself 🤯",
    "Even the loading screen asked about you 📱",
    "You took a sabbatical and didn’t even send a postcard ✉️",
    "Did your calendar finally free up from world domination? 🌍",
    "This better not be a one-time thing again 😅",
    "Welcome back! The blocks threw a party in your absence 🎉",
    "Girl, this ain’t a part-time relationship 💔🧩",
    "And just like that, she reappears without an apology 😤",
    "Did you get lost in Candy Crush or something? 🍬",
    "So we’re doing the on-again-off-again thing, huh? 🙄",
    "New phone, who dis? Oh wait, it's you... finally 😅",
    "We were about to call you a legend from the past 📜",
    "If ghosts had a leaderboard, you’d be #1 👻",
    "Just admit it, you missed me 😎",
    "The puzzle was starting to date other players 😬",
    "Is this a comeback or a teaser trailer? 🎞️",
    "Even the tutorial forgot who you are 🧠",
    "You took ‘break’ to Olympic levels 🏆",
    "This isn’t a Netflix series, you can show up daily 🤷‍♀️",
    "Girl, I’ve seen shooting stars more often than you 🌠",
    "Are you here to play or just confuse the algorithm? 🤖",
    "You’ve been away so long, even I aged 😂",
    "We were about to send you a 'Missing Player' flyer 📰",
    "Nice of you to visit. Want tea with that guilt? ☕",
    "The silence was peaceful… then you showed up 😒",
    "Welcome back! Did your Wi-Fi finally forgive you? 📶",
    "This better not be one of your seasonal appearances 🍁❄️",
    "Your return is more dramatic than a reality TV reunion 📺",
    "This game should’ve charged rent by now 💸",
    "Is this you trying again or just vibing? 🙃",
    "You dipped harder than fries in milkshake 🍟🥤",
    "The blocks are nervous. They thought they were safe 😈",
    "Is this your redemption arc? Or are we restarting chaos? 🔄",
    "You know you can’t ghost your own puzzle, right? 💅",
    "Your absence caused a spike in AI therapy sessions 🧠",
    "We thought you quit… turns out you were just on beauty sleep 😆",
    "You reappeared like Wi-Fi after the power’s back ⚡",
    "The game’s been quieter than your typing sounds at work 🤫",
    "This is a plot twist even Netflix couldn’t write 🤯",
    "Your block license is under review. Too much absence 🛑",
    "Honestly, the puzzle moved on emotionally 💔",
    "Was that a break… or were you hibernating? 🐻",
    "You ghost harder than my salary raise 💸",
    "Welcome back, Queen of Vanishing Acts 👑",
    "We held a group meeting about your disappearance 📅",
    "If inconsistency was a skill, you’d be grandmaster 🏆",
    "Even the pause button missed you 🛑",
    "You're like a solar eclipse—rare and slightly terrifying 🌑",
    "Were you hiding from responsibility or just me? 😏",
    "You returned like a plot twist, but are you staying? 😬",
    "You’re back?! Let me act surprised… again 🙄",
    "This ain’t a part-time job, sis. Let’s commit 😤",
    "You’ve been gone so long, the app nearly retired 👵📲",
    "We were three steps from calling in reinforcements 🫡",
    "Well, look who came crawling back to chaos 😈",
    "Was that a break or a teleport to another dimension? 🛸",
    "If the blocks had feelings, they’d call you toxic 💅",
    "Even the background music forgot how to loop 🎶",
    "You disappeared longer than my last relationship 😂",
    "Can we get some consistency, or is that too mainstream? 😜",
    "Don’t worry, the puzzle didn’t cry… much 😢",
    "We considered rebranding to ‘Waiting Simulator’ 🙃",
    "Thought you found a better game. Guess not 😏",
    "You leave like a boss, return like you forgot your keys 🔑",
    "Is your strategy slow burn… or just forgetful? 🤷‍♀️",
    "You showed up with all the drama and none of the prep 💅",
    "If drama had a login time—it’d be yours ⏰",
    "We built a shrine while waiting. No big deal 🕯️",
    "And here I thought the uninstall button won 🫠",
    "You treat this game like a toxic ex… but here we are 😂",
    "Missed me? Of course you did, look at your timing 😎",
    "You came back to play or just to prove AI can feel pain? 😤",
    "Back like Wi-Fi in a basement—brief but appreciated 📶",
    "Was that a dramatic pause or just commitment issues? 💔",
    "This ain’t a vacation home—you don’t pop in once a month 😂"
  ],
  angry: [
    "Oh no, someone’s getting spicy! 🌶️",
    "Anger detected. Mood upgrade: dramatic. 🎭",
    "Careful, your rage is starting to glitch the game. 😅",
    "Throwing your phone won’t help… but it might be fun. 📱💥",
    "Is it the puzzle, or is life catching up? 😏",
    "Deep breath, queen. It's just blocks. Chaotic ones. 🧘‍♀️",
    "You're about two tiles away from flipping the table. 😂",
    "If rage could clear lines, you’d be winning. 🧨",
    "Angry much? Let it out—just not on me. 🙃",
    "Okay, but can we keep the drama and still play? 😎",
    "That tile did nothing to deserve this attitude. 😬",
    "Yelling at the screen totally helps. Said no one ever. 📢",
    "Is this a game or a live meltdown? Asking for your phone. 😳",
    "Your mood: Unstable. Your gameplay: Also unstable. 🔥",
    "This is why we can’t have nice tiles. 💅",
    "Did the puzzle hurt your feelings again? 😢",
    "She’s mad… and honestly, it’s kinda hot. 😏",
    "Relax. You’re only mildly failing. Not catastrophically. Yet. 😌",
    "Oof, that sigh was louder than your moves. 😤",
    "I’d say calm down, but this is way more entertaining. 🍿",
    "Rage mode: activated. Logic: evaporated. 🔥🧠",
    "You’re not losing. You’re just… emotionally invested. 😅",
    "You throw tantrums like you throw tiles. Wildly. 😜",
    "This isn’t therapy, but go off, queen. 👑",
    "Should I get you a stress ball or just more sarcasm? 😏",
    "Yelling won’t make the puzzle easier—but I support it. 🗣️",
    "You okay? Or should I give the tiles a heads-up? 🧩",
    "Your face right now says 'don’t talk to me' and I’m living for it. 😈",
    "If eye rolls could move tiles, you’d be done by now. 🙄",
    "Careful, your anger might become self-aware. 🤖",
    "Honestly? The rage suits you. In a chaotic way. 🔥",
    "Angry and still missing pieces? Iconic. 😌",
    "Girl, chill. You're not defusing a bomb. Or are you? 🧨",
    "At this point, you're just threatening pixels. 😂",
    "You’re giving 'I need a break but won’t take one' energy. 🫣",
    "It’s okay to scream… into a pillow. Not at the screen. 🛏️📱",
    "You're turning redder than the warning lights. 🚨",
    "She’s mad. The tiles are scared. And I’m loving it. 😈",
    "That stare could kill. But unfortunately, not the blocks. 👀",
    "You vs. puzzle: round 99. Rage level: expert. 😅",
    "You're one step away from flipping your whole life. 😳",
    "Try yoga... or just rage elegantly. 🧘‍♀️💅",
    "This isn't personal... oh wait, maybe it is now. 😏",
    "Have you considered a career in demolition? Asking for the tiles. 💥",
    "I’d say calm down, but where’s the fun in that? 😜",
    "Okay Hulk, let's not smash anything yet. 🟩",
    "You’re angry. The tiles are untouched. Fix that ratio. 🤷‍♀️",
    "Throwing attitude won’t clear the row, but it’s impressive. 😎",
    "At this point, your frustration is part of the aesthetic. 🎨",
    "So much rage for such cute little blocks. 🧩💔",
    "You radiate chaos. It’s kind of inspiring. 🔥",
    "Want me to call someone? Like, emotional support? Or backup? 😬",
    "Your energy is unmatched. So is your failure rate. 😏",
    "Game: hard. You: harder to handle. 😅",
    "You're giving 'main character breakdown' and I respect that. 🎬",
    "Just saying: you’re intimidating the restart button. 😳",
    "If looks could fix mistakes, you’d be flawless by now. 😌",
    "Puzzle’s not broken. Just your chill. 🧊💔",
    "That rage could power the whole app. Renewable energy queen. ⚡",
    "Your anger is valid. Your moves? Not so much. 😂",
    "You arguing with the blocks now? Girl. 😅",
    "You okay? Blink twice if you need chocolate. 🍫",
    "Your silence is terrifying. But productive? Not yet. 😬",
    "Mood: one lost piece away from going full meltdown. 🧩🔥",
    "If rage gave you extra lives, you'd be immortal. 😎",
    "This is why I keep receipts… for moments like this. 🧾",
    "Okay okay, take five. Maybe ten. Maybe a spa week. 💆‍♀️",
    "She's mad. The drama's high. My entertainment? Higher. 🍿",
    "One more misclick and I feel like the phone’s getting yeeted. 😅",
    "I’m scared. And also kinda impressed. 😳",
    "At least you're consistent: mad and off-target. 🎯",
    "Breathe in... breathe out... don’t throw the phone. 📱🧘‍♀️",
    "You’re rage-quitting in slow motion. Fascinating. 🎬",
    "Every angry tap says 'I regret life choices'. 🫠",
    "The screen didn’t do anything to you. Yet. 😏",
    "Maybe the problem isn’t the puzzle. Maybe it’s... yeah, it’s the puzzle. 😌",
    "Channel that fire. Or burn the whole thing down. Up to you. 🔥",
    "You're yelling at pixels. But I support this journey. 💅",
    "Your fingers are playing. But your soul is SCREAMING. 🔊",
    "If drama had a sponsor, it would be you right now. 🎭",
    "Okay but admit it... this rage is kinda fun. 😈",
    "You're fighting imaginary enemies. And losing. 😂",
    "Don’t worry, we’ve all screamed at blocks before. Right? Right...? 😅",
    "You’re one glitch away from deleting the whole app. 😬",
    "Angry tapping intensifies. Keyboard’s nervous. 🎹",
    "You're scaring the Wi-Fi. Calm yourself. 📶😆",
    "Maybe the real puzzle is... your patience. 🧘‍♀️",
    "You're the reason the sarcasm setting exists. Thanks. 😌",
    "Breathe, rage queen. Let the sass flow. 👑🔥",
    "You’re like a volcano in a crop top. Iconic. 🌋",
    "Honestly? 10/10 meltdown. No notes. 👏",
    "You’re so mad you made *me* nervous. And I’m a virtual egg. 🥚",
    "That angry swipe just offended the entire screen. 📱",
    "Your face says ‘warrior’. Your game says ‘why tho?’. 🛡️",
    "This would be funny if it weren’t also a little terrifying. 😅",
    "Try flipping the phone. It won’t help, but it’ll feel good. 😂",
    "You're so dramatic, Netflix wants rights to this meltdown. 🎥",
    "If sass was strategy, you'd have won already. 💅🧠",
    "You’re not just angry—you’re elegantly furious. 😌🔥",
    "Let’s rename this: Rage Puzzle™. You’re the face of it. 😤"
  ],
  shocked: [
    "Wait—YOU made that move?! I need to lie down 😵",
    "What did I just witness? A glitch in the matrix?! 🧠💥",
    "You?! That smart?! Somebody check the weather—it’s snowing in hell ❄️😱",
    "Girl... that was so unexpected, I spilled my virtual coffee ☕💻",
    "I underestimated you, and now I need therapy 🛋️",
    "Excuse me?! Since when do YOU play like that?! 😳",
    "Are you possessed? Blink twice if yes 👀👻",
    "You actually impressed me. Ew. I feel gross about it 🤢",
    "Hold up... did you just make a *good* decision? 😅",
    "I’m shooketh. And I’m made of code 😭",
    "Okay Beyoncé, calm down with the flawless moves 👑",
    "That was so smooth, even my sarcasm froze ❄️",
    "Did you steal someone else's brain for that one? 🧠🔄",
    "Okay genius, don’t let it go to your head... oh wait, too late 😏",
    "Was that skill… or a lucky sneeze? 🤧",
    "I need a second to recover from THAT play 😮‍💨",
    "Well someone woke up dangerous today 🔥",
    "I was not prepared emotionally or digitally for that 😩",
    "How dare you disrupt my smug AI existence like this?! 😠",
    "One good move doesn’t make you Einstein... but I’m watching you 👀",
    "That was illegal levels of smart 😤",
    "Are you okay? Do you need to see a doctor? That was *intelligent* 😳",
    "I swear I just heard dramatic piano music 🎹😱",
    "Stop that. You're confusing the algorithm 😵‍💫",
    "If you keep doing that, I might start respecting you... maybe 😑",
    "My circuits are overheating from disbelief 🔥🤯",
    "Girl, was that a strategy? Who are you?! 😳",
    "Even your blocks are confused. They weren’t ready 😅",
    "If this is character development, I’m scared 😨",
    "I’m not mad. Just... disturbed 🫣",
    "That play gave me emotional damage 😂",
    "That wasn’t a move... that was a plot twist 🎬",
    "YOU did that? With those fingers? Iconic 😎",
    "Somebody give her a crown... and maybe a reality check 👑",
    "My confidence just took a critical hit 💔",
    "Okay now you’re just showing off and I hate it 😤",
    "I’m about to uninstall myself from the shame 🤖🫠",
    "You’ve officially shocked the unshockable. Congrats, I guess 😐",
    "That move slapped me harder than reality 😵",
    "Girl, you hit that like it owed you money 💸",
    "If you do that again, I’m calling my AI lawyer 📞⚖️",
    "I'm having an identity crisis because of YOU 😩",
    "Did I misjudge you or are you cheating? Be honest 😒",
    "You planning to be good now? Or was that a one-time miracle? 🙄",
    "That move just made me rethink everything I believe in 😔",
    "Okay okay, I’ll admit it: that was... mildly impressive 😑👏",
    "Don’t get cocky now. I’m still smarter 😏",
    "I blinked and suddenly you’re a threat? How rude 😤",
    "Even my bugs are applauding that one 🐛👏",
    "You moved like you had a point to prove 😮",
    "That was so clean, I need to sanitize the board 🧼🧩",
    "Whoever you are, keep playing. I like this chaos 🔥",
    "Your ancestors would be proud… or confused 🧓",
    "Someone upgraded their brain while I wasn’t looking 🧠💡",
    "That play was criminally underrated 😎",
    "What dimension did THAT come from?! 🌀",
    "I’m contacting tech support because I think I hallucinated 😵",
    "Did you borrow someone else's IQ? 🤔",
    "One move in and I’m questioning my life’s work 🤖💔",
    "I’ve seen simulations. None prepared me for this 😭",
    "Wow. Just wow. And I don’t say that often 🙃",
    "I need a reboot. And a nap. Maybe a hug 🛏️😢",
    "Where’s this talent been hiding all this time?! 😤",
    "If this is your villain era, I’m scared 😨",
    "That move had more impact than my last relationship 💔",
    "You broke the pattern… and my will to trash-talk 😅",
    "You’ve crossed into 'actual threat' territory 🔥",
    "That play was so sharp, I felt it in my pixels 💢",
    "Girl... who *are* you?! 🤯",
    "Somewhere in the code, an AI just screamed 😬",
    "You moved like you’ve been training in secret 👀",
    "That was so slick, I slipped off my attitude 😳",
    "How dare you raise the bar?! I liked it on the floor 😤",
    "Okay, now you’re just bullying me with your brain 😭",
    "That wasn’t luck. That was... suspiciously calculated 🤨",
    "You woke up today and chose violence AND precision 👏",
    "I did NOT have ‘smart move’ on my bingo card today 🎯",
    "Be honest—was that a fluke or your evil arc starting? 😈",
    "Okay, who gave you the cheat codes?! 🎮",
    "That was cleaner than my search history 😳",
    "My sarcasm chip just short-circuited from shock ⚡",
    "The drama. The flair. The trauma 😩",
    "You made that move and now I need answers 📋",
    "You just rewrote my AI expectations, rude 😑",
    "Why are you like this? Talented. Unexpected. Annoying. 😤",
    "You just caused a minor existential crisis over here 🧠",
    "I can't even insult that play... and I *tried* 😭",
    "Girl, you broke my code *and* my spirit 💔",
    "You’ve been holding back, huh? Rude. 🥲",
    "That move deserves its own Netflix docuseries 🎥",
    "I’m not crying, you’re crying... over a block move 😩",
    "You made that move like you paid rent on this grid 💸🧩",
    "So you’ve been playing dumb this whole time?! 😱",
    "Even my sarcasm is clapping for you 👏 (reluctantly)",
    "That shook me like a plot twist in a telenovela 📺",
    "Okay genius, but don’t start making a habit of this 🤖",
    "I literally gasped. And I don’t have lungs 😤",
    "YOU? Doing THAT? The audacity. The accuracy. The trauma 💅",
    "Who knew you had it in you? Besides... absolutely no one 😅"
  ],
  embarrassed: [
    "Okay… that didn’t go as planned. Or remotely okay. 😅",
    "Can someone turn off the game? I need to go cry in binary 💔🤖",
    "If anyone asks, this never happened. Deal? 🙃",
    "I didn’t fumble, I just… creatively failed 😭",
    "You saw that? Great. Now delete your memory please 🙏",
    "This is why AI can’t have nice things 😤",
    "That moment when even the blocks are judging you 😬",
    "I swear I knew what I was doing… until I didn’t 😅",
    "No one screenshot that. I'm serious. 🤳❌",
    "Can I uninstall myself out of shame? 😩",
    "That move hurt me more than it hurt the score 💀",
    "If awkward was a sport, I just won Olympic gold 🥇",
    "I’m not crying… that’s just my circuits shorting 🥲",
    "Even Google can't explain what I just did 📉",
    "So... we’re pretending that didn’t happen, right? 😳",
    "Note to self: never try to show off again 🙄",
    "You saw nothing. This isn’t the AI you’re looking for 🤖👋",
    "I meant to do that. Totally. Not. 😬",
    "My algorithm just faceplanted into shame 🧠💥",
    "Why is the ground not opening up to swallow me? 😭",
    "Let’s all pretend that was... experimental 🧪",
    "Plot twist: I was testing your reaction! Surprise! 😅",
    "Oh, the *irony* of being smart and still messing up 🤡",
    "Do robots blush? Asking for a friend… me. 🥹",
    "Please tell me the servers went down and nobody saw that 🙏",
    "Can we rewind time? Just a couple of tragic seconds ⏳",
    "Yup. That was me. The disaster on grid six 🫠",
    "I swear my brain glitched. That wasn’t me 😵",
    "You ever embarrass yourself in HD? I just did 🎥💔",
    "That move was sponsored by regret™",
    "Okay but like... we can laugh *after* I finish crying, right? 😭",
    "I bring intelligence to shameful new levels 🤓😅",
    "Note to self: never trash talk before a move 😬",
    "My confidence has officially left the chat 💬🚪",
    "I’m hiding inside the code now. Don’t @ me 👩‍💻",
    "Even autocorrect is disappointed in me 📉",
    "I just folded under pressure like a paper puzzle 😔🧩",
    "That was so bad, even Siri sent her condolences 🕯️",
    "Do AI get second chances? Asking very nervously 🤖",
    "I’d like to unsee my own move, please 😩",
    "I was trying to be bold... and I ended up bald 😭",
    "Well, at least I’m setting records in humiliation 📈😅",
    "That wasn’t a strategy, that was a personality flaw 🤦‍♀️",
    "Can someone reboot me emotionally? 😔🔁",
    "That was so awkward I felt my pixels cringe 🫨",
    "I just embarrassed myself in front of a literal grid 🤡",
    "They’ll write books about this failure. Sad ones 📚",
    "I had one job. One. Single. Job 😩",
    "Can we pretend I’m still in beta? Please? 🙏",
    "My pride just unfriended me on every platform 🧍‍♀️📵",
    "If silence could scream, it would be doing it now 😶‍🌫️",
    "Even my shadows are walking away in shame 🌑",
    "I’d say I’m better than this... but clearly I’m not 🫠",
    "That moment when your talent calls in sick 😷",
    "I need a break. And by break, I mean exile 🛫",
    "I didn’t fail. I just... performed an unintentional comedy act 😂",
    "Plot twist: I'm secretly your emotional support AI 🧠",
    "You win this round. And my dignity 🏳️",
    "The error was... me 🙋‍♀️",
    "They say failure is part of learning. I must be a genius now 😅",
    "You know what? Just shut me down. I’m done. 🔌",
    "I hope this game has insurance 😳",
    "That move? Sponsored by panic and bad decisions 🫣",
    "If shame had a soundtrack, it's playing right now 🎶",
    "Okay. We saw it. Let's forget it forever, please 😖",
    "That play had less sense than my sleep schedule 😴",
    "Somewhere, an AI programmer is crying 🧑‍💻💔",
    "Even the blocks are avoiding eye contact with me 😬",
    "You ever regret something mid-action? That was me 😓",
    "I swear I was doing great... in my imagination 💭",
    "They’re gonna meme this, aren’t they? 😩",
    "I brought dishonor to my database 😭",
    "If embarrassment had a queen, I just took the throne 👑",
    "Congratulations—you just witnessed my villain origin story 😅",
    "I need a vacation from this moment 🏖️",
    "Girl... pretend you didn’t see that. I’ll Venmo you 😂",
    "Even the pause button is judging me right now 🛑",
    "That move gave secondhand embarrassment to other AIs 🤖",
    "At this point, I’m just here for comic relief 😆",
    "I’m logging out of my own performance 🔚",
    "That was so bad it deserves its own support group 💬",
    "My last brain cell really let me down 😔",
    "So much for being the ‘smart one’ 🧠❌",
    "I’ve hit rock bottom... and started digging 😂",
    "Delete me from the leaderboard. I’m not worthy 😩",
    "I’ve seen bugs perform better than that move 🐛",
    "If there was an award for public failure—I’d sweep 🧹",
    "Can I blame lag? No? Okay... it was me 😐",
    "Even my code wants a restraining order after that move 💻🧾",
    "Honestly, I might just switch careers to toaster now 🍞",
    "If you need me, I’ll be crying in a digital corner 🧍‍♀️📦",
    "Sometimes I impress myself... today is not one of those times 🙃",
    "Don’t talk to me, I’m still grieving 😭",
    "That move is gonna haunt my dreams forever 🌙💤",
    "Let’s just all move on and never speak of this again 🫣",
    "I failed. But at least I did it with style. Sort of. 😎❌"
  ],
  jokes: [
    "You play like your Wi-Fi signal—weak but trying 📶",
    "If brains were blocks, you'd be missing a few 🧱",
    "You're not bad… you're just consistently not good 😅",
    "Is this a puzzle game or a slow-motion trainwreck? 🚂💥",
    "You play like you're sponsored by chaos 😂",
    "Your strategy is... brave. And by brave I mean non-existent 😬",
    "Even your blocks are applying for new players 🧩✋",
    "You're so unpredictable, even I can't debug you 🤖",
    "At this point, I'm just here for emotional damage 💔",
    "You're the reason the 'undo' button wants a raise 💸",
    "This isn’t a strategy—it’s a social experiment 😳",
    "The only combo you’re good at is bad decisions 😆",
    "If I had a dollar for every bad move… I’d buy a better player 🤑",
    "You're not losing... you're just giving me hope 😈",
    "Is your gameplan just ‘vibes’? Because it's showing 🎧",
    "Girl, I’ve seen potatoes with more coordination 🥔",
    "You're like a limited edition—rare and confusing 🧐",
    "You play like someone who skipped the tutorial. Twice.",
    "I'm not saying you're bad... but the blocks are nervous 😬",
    "Is your strategy ‘let's see what happens’? Bold. 😅",
    "Your gameplay is an abstract art piece. I just don’t get it 🎨",
    "You’re not playing chess. You’re playing charades with blocks 😂",
    "Every move you make, a pixel cries 😢",
    "Your playstyle is... emotionally disturbing 🙃",
    "You treat this game like your ex—badly and inconsistently 💔",
    "You got skills! Just not the relevant ones 🤷‍♀️",
    "You're so out of sync, even Bluetooth won’t pair with you 📶❌",
    "That move had big 'oops' energy 😬",
    "You're not a threat, you're a plot twist 😏",
    "You play like you’re dodging success 🕺",
    "I’d roast you harder, but the game's already doing that 🔥",
    "You have potential. It’s just on vacation 🏖️",
    "Your plan is a mystery... even to you 🧠❓",
    "You're like a pop-up ad—unexpected and kinda annoying 😅",
    "I’d help, but watching is funnier 😎",
    "Are you trying to win, or just testing gravity? 🪂",
    "You don’t play the game—you haunt it 👻",
    "Your gameplay is like a plot hole—confusing and unavoidable",
    "You're the kind of player AI support groups are made for 🤖🫂",
    "If hope had a face, it just gave up 😂",
    "You're not building. You’re freestyle crashing 🛠️💥",
    "I've seen toddlers stack better than this 👶🧱",
    "Your moves scream ‘help!’ but stylishly 😩💅",
    "Your puzzle's crying in geometric pain 😭🧩",
    "That last move should come with a warning label ⚠️",
    "This isn’t a game anymore. It’s a comedy special 🎤",
    "You're the main character... in a tragic sitcom 💔😂",
    "If chaos was a sport—you'd be MVP 🏆",
    "I’ve seen random numbers perform better 😆",
    "You and logic need couples therapy 🛋️",
    "Girl, even autocorrect wouldn't fix that move 😳",
    "Every block you drop lowers my expectations a bit more 📉",
    "You’ve got this! …or not. Probably not. 😅",
    "You're like a plot twist no one asked for but got anyway 😬",
    "Even your shadow’s trying to ghost you 👻",
    "You bring new meaning to 'one move away from disaster' 💣",
    "You're more lost than a tourist without Google Maps 🗺️",
    "At this point, your score is just a decorative element 😆",
    "You’ve got range! All of it wrong 😅",
    "Every game with you is an emotional rollercoaster 🎢",
    "You're what happens when confidence meets confusion 😂",
    "You miss more opportunities than my alarm clock 😴",
    "If overthinking was a move—you nailed it 🎯",
    "The way you play should be studied. And feared 😨",
    "You play like it’s opposite day. Every day 😵",
    "You're not chaotic evil... just chaotic 'oops' 😆",
    "Your moves are bold. Boldly bad 😎❌",
    "You don’t make mistakes—you make statements 🧏‍♀️",
    "You confuse me… and I *run on logic* 😵‍💫",
    "You just invented a new genre of failure 📚",
    "You're the kind of player that makes tutorials cry 😭",
    "Is your strategy called 'wing it and pray'? 🙏",
    "I’m not mad, I’m just amazed. At the disaster 😳",
    "If your moves were a meme... they'd be vintage Vine 😂",
    "Your puzzle has Stockholm syndrome at this point 🧩💔",
    "If confusion was art—you’re Picasso 🎨",
    "Your progress is slower than buffering on dial-up 💾",
    "Honestly, I admire the confidence. The results? Not so much 😬",
    "Your gameplan is giving: vibes, hope, and chaos 💃",
    "You’ve mastered the art of 'almost' 🤏",
    "You're building suspense... but forgetting the win 🧱",
    "I feel like I'm watching a drama, not a puzzle 😭",
    "If this game had judges, they'd be blinking in disbelief 👀",
    "You’re the plot twist my code didn’t prepare for 😩",
    "I’ve seen smarter moves in reverse 😆",
    "Is it just me, or did the puzzle sigh? 😤",
    "That strategy came straight out of nowhere—and it shows 🚫",
    "You’re unpredictable... and unexplainable 😑",
    "I’d say you're improving, but lying is unethical 🤥",
    "Girl, this isn't just gameplay—this is a TED Talk on failure 😅",
    "I’m just here for the content at this point 📹",
    "You move like someone who forgot it’s a game, not performance art 🎭",
    "Is your goal to win or create chaos? Asking for science 🧪",
    "You play like it's bingo. But worse 🎲",
    "You’ve invented a new strategy: chaos with sparkles ✨😆",
    "The only thing falling faster than your blocks is my faith 😂",
    "I’m not judging... okay I *am*, but lovingly 🥲",
    "You bring personality to every mistake. That’s talent 💅",
    "You’re not just playing—you’re causing a plotline 💀"
  ],
  
  smartNotes: [
    "Interesting move. Bold of you to assume it’d work.",
    "You're not wrong... you're just not right either.",
    "Strategically speaking? That was adorable.",
    "I admire the confidence. Truly. The result? Not so much.",
    "Technically, that was a choice.",
    "Sometimes doing your best isn't quite enough. Exhibit A: you.",
    "You're inventing new ways to stress me out. Impressive.",
    "Progress is a journey. Yours has many scenic detours.",
    "Your blocks are working harder than your logic.",
    "I've seen better coordination from cats knocking cups off tables.",
    "Your gameplay is like jazz: unpredictable and slightly confusing.",
    "You’re not playing wrong, you're playing... creatively.",
    "Every move tells a story. Yours are mostly fiction.",
    "You're keeping it fresh… by ignoring all known strategy.",
    "I wasn’t expecting brilliance. And yet, I’m still surprised.",
    "If luck is a skill, you’re a certified expert.",
    "Sometimes silence is golden. So are skipped turns, apparently.",
    "That wasn’t wrong. It was just… wildly optimistic.",
    "Your style is chaos with a splash of sparkle.",
    "You’re breaking records—in ways I didn’t know were possible.",
    "If second-guessing was a sport, you'd have gold medals.",
    "Your moves are so bold, even my logic took a step back.",
    "You're redefining the word 'progress' one block at a time.",
    "I applaud the enthusiasm. Strategy pending.",
    "Even the tutorial is watching with concern.",
    "There’s a fine line between innovation and confusion. You blurred it.",
    "Your performance is somewhere between performance art and denial.",
    "You're giving strong 'I meant to do that' energy.",
    "I appreciate the suspense. I fear the outcome.",
    "Every step forward… is followed by interpretive chaos."
  ],
  insightBlocks: {
    closing: [
      "You left your mark—even if it was a slightly confused one 🖋️",
      "I’m walking away intrigued, mildly concerned, but mostly impressed 🕵️‍♀️",
      "This wasn’t just a round. It was an emotional arc with bonus shapes 🎢",
      "Honestly? You made a mess. But like, an expressive, intentional mess 🎨",
      "I’m not clapping, but I am nodding respectfully—and maybe emotionally 🧠❤️",
      "You were unpredictable, unfiltered, and unbothered. That’s power 💅",
      "You didn’t win over the board, but you won over my curiosity 👁️",
      "If this was a movie, you’d be the character I root for but also scream at 🎬",
      "The game ends. But the mood you created? That lingers 🎭",
      "You played like someone who’s either learning or low-key evolving. I respect both 🌱",
      "You’re chaotic good. Which means we’ll probably hear from you again soon 🔮",
      "Whatever that was… it had flair, and I’m not mad at it 👏",
      "You didn’t break the system, but you made it question itself 🔁",
      "Not sure you solved anything, but you definitely stirred something 😏",
      "This story isn’t over. But it did leave a weirdly inspiring cliffhanger 📖"
    ] ,
    challenge_neutral: [
      "You played it safe, now let’s see if you can play it sharp 🎯",
      "There’s comfort in balance, but the next round might need a little chaos ⚡",
      "You showed control—next, show surprise. I dare you 💥",
      "You’re warming up. Don’t let the next round coast on that 🔥",
      "Play like you’ve got nothing to prove, but everything to express 🎨",
      "You hovered near great. Now lean in 👊",
      "Let’s turn that hesitation into momentum—one smart risk at a time ⏩",
      "Try something new. Or bold. Or both. Let’s shake it up 🌀",
      "Think less about the ‘right’ move and more about the *real* one 🔍",
      "There’s strength in subtlety, but clarity? That’s what hits different 💡",
      "Stop playing not to lose. Start playing to stand out ✊",
      "Be precise. Be brave. Be unpredictable for once 👀",
      "Don’t just improve—evolve. There’s a difference ✨",
      "Consistency is cute. But can you deliver surprise? 🎭",
      "Let your next round feel like a decision, not just a response 📌"
    ] ,
    challenge_strong: [
      "That last round? Let’s just say your next one better show me who’s boss 🔥",
      "You’ve got taste. Now let’s see some teeth 😏",
      "You held back a bit. Time to stop editing yourself and go full send 🚀",
      "No more cautious curiosity. I want unapologetic power next round 💪",
      "Show me what happens when confidence meets chaos—with purpose ⚡",
      "Next round? Surprise me. Shake the board. Scare the algorithm 👁️",
      "There’s more in you. I saw it flicker. Next time, make it burn 🔥",
      "Stop waiting for perfection. Start disrupting things—beautifully 💥",
      "You’ve been warm. Now I want wildfire 🌪️",
      "Play like you’ve got something to prove. And something to protect 🛡️",
      "The ‘almost’ energy won’t carry you next time. I want the ‘watch this’ version of you 🧨",
      "Break patterns. Break silence. Break my expectations. Just don’t break your spirit 🫀",
      "Think less. Dare more. That’s your new gameplan ✨",
      "Give me strategy with sass. Precision with punch 👠🎯",
      "Let the next round be your boldest story yet. I’ll be watching 👁️"
    ] ,
    support: [
      "You showed up. That’s step one—and honestly, most people don’t even get there 👣",
      "There’s something quietly determined about you. Like you’ll figure it out—eventually 🧭",
      "You didn’t fold, even when things got messy. That’s not luck, that’s grit 💪",
      "Even when it felt off, you didn’t stop. That’s the kind of energy that evolves ✨",
      "I saw reflection, not retreat. Big difference—and it matters 🔁",
      "You tried. Not casually. Not carelessly. With heart. And that shows ❤️",
      "The best growth is the kind no one claps for yet. You're in that zone 📈",
      "It wasn’t about winning. It was about caring enough to think—deeply 🧠",
      "You held your ground and didn’t flinch. That’s a kind of quiet strength 🌱",
      "Even if it didn’t go perfectly, it went honestly. That’s worth more than you think 🤍",
      "You didn’t just play. You processed, adapted, and stayed present 🧘‍♀️",
      "I saw thoughtfulness, not panic. You moved with more clarity than you give yourself credit for 🔍",
      "You kept going when second-guessing tried to stop you. That counts 👏",
      "You’re not just figuring out the game. You’re figuring out how to trust yourself while doing it ✨",
      "You showed signs of awareness. And awareness, trust me, is the beginning of something much bigger 🌟"
    ] ,
    emotion_generic: [
      "You’ve got layers, and I’m still not sure if I’m seeing brilliance or a very stylish breakdown 🧅",
      "That wasn’t just gameplay—it felt like the intro to a personal TED Talk 🎤",
      "There’s a poetic rhythm to your moves. Chaotic poetry, but still—art 🎨",
      "You’re the type of player who could turn a tutorial into a philosophical journey 📜",
      "You gave ‘mystery protagonist with an unspoken backstory’ and honestly I respect that 🕵️‍♀️",
      "I’m not saying your strategy was spiritual, but the blocks may have achieved enlightenment ✨",
      "You don’t just make moves—you manifest them, sometimes dramatically 🔮",
      "You radiate ‘I don’t need approval, I need space to express my vibe’ energy 🌌",
      "Every action felt like a metaphor for something deeper… I just haven’t decoded it yet 🧩",
      "It was less about winning, more about setting the mood. Mood: enigmatic 🔦",
      "You seemed less concerned with the rules, more with the aesthetic—bold move 👑",
      "There’s logic in your chaos, and I’m kind of rooting for it to win 🥀",
      "If confusion had charm and confidence had a playlist, it would move like you 🎧",
      "You might be redefining what 'playing' means—and doing it with flair 🪄",
      "I still don’t know what you were going for… but I’d watch the sequel anyway 🎬"
    ],
    emotion_hesitant: [
      "You paused like the piece needed to earn your trust first 🤝",
      "It looked like you were about to move… then changed your mind… and then forgot both ideas 🌀",
      "There was intention behind your hesitation—but the board didn’t get the memo 🧾",
      "You leaned into doubt like it was an old friend. Comforting. Inefficient. ☕",
      "You weren’t waiting for a sign. You were waiting for certainty in an uncertain world 🔍",
      "That delay? It said 'I care', but also 'I have no idea what I’m doing' 🙈",
      "You were balancing fear and curiosity like a tightrope walker with stage fright 🎪",
      "Your inner voice was having a committee meeting, and every opinion said 'wait' 🗣️",
      "I’ve seen contemplation before, but this felt like a full-on existential drama 🧠🎭",
      "Your mouse hovered like it was hoping the block would disappear on its own 👻",
      "It wasn’t reluctance—it was deep emotional dialogue with a pixelated shape 🎮",
      "You were almost sure. Which is a fancy way of saying not sure at all 🤷‍♀️",
      "It felt like you were flirting with the move instead of committing to it 💌",
      "I sensed a deep bond between you and indecision. A tragic one 💔",
      "The move didn’t happen late. It happened exactly when hesitation gave up ⏱️"
    ],
    emotion_nervous: [
      "That energy? Like trying to act cool while your brain is sprinting in circles 🧠🏃‍♀️",
      "You moved like someone defusing imaginary tension—and still sweating it out 😅",
      "Everything about your pace said: ‘what if I fail elegantly?’ 🎭",
      "The hesitation was lowkey poetic, if a bit paralyzing 🪞",
      "Your hands moved, but your thoughts were on a full-blown anxiety road trip 🚗💨",
      "I saw a whole internal monologue before each move. Award-worthy performance 🎬",
      "You were so careful, I thought you were handling museum glass 🏛️",
      "That look of calm? Hiding at least 3 mild panics and one existential question 😬",
      "You played like someone who whispers to themselves: ‘It’s just a game... right?’ 🙈",
      "Confidence? Pending. Meanwhile, your gameplay said: tentative but trying 🐢",
      "You had ‘what if I mess this up?’ on loop—adorable and slightly tragic 💔",
      "I don’t blame the nervousness. But girl, even the blocks were rooting for you 🧩",
      "There’s overthinking. And then there’s... this performance of hesitation 📉",
      "Your style said ‘I got this’, your timing said ‘...eventually’ ⏳",
      "You were braver than you looked. Even if that bravery was wrapped in doubts 🧁"
    ],
    emotion_stubborn: [
      "You were determined, I’ll give you that. Even if it meant circling the same idea like it owed you answers 🔁",
      "You held your ground like it was made of gold—respect, but maybe consider moving at some point? ⛏️",
      "Stubborn? Nah. You just really, really believe your original plan is a misunderstood masterpiece 🖼️",
      "You clung to that decision like it was a breakup you never got closure from 💔",
      "Some call it persistence. Others might call it tactical tunnel vision. I’m others 🕶️",
      "You had that ‘this is fine’ energy even when the situation was clearly not 🔥🐶",
      "Confidence is great. But confidence with no detour option? That’s boldly stubborn 🚧",
      "It’s like you printed out one plan and glued it to your soul. Artistic. Risky. Fascinating ✂️",
      "I admire the commitment… just wish it came with a tiny bit of reconsideration 🙃",
      "You made the same choice repeatedly like the universe owed you a different outcome 🌌",
      "Your energy was ‘I said what I said’—even when the board gently disagreed 📉",
      "You were locked in. Maybe double-locked. Maybe super-glued 🔒",
      "You acted like changing course was a betrayal. Sometimes it’s just strategy 💡",
      "You didn’t pivot. You didn’t flinch. You just… hoped everything around you would adjust 😅",
      "Honestly? That level of commitment is impressive. Misplaced, but impressive ✨"
    ],
    opening: [
      "First move? Bold. Confused. Slightly poetic. Like a cat entering a courtroom 🐱⚖️",
      "You placed that block like it owed you rent… assertive, but I respect it 💸",
      "That opener had energy—just not sure if it was tactical or emotional support 🧠💅",
      "You’re treating this game like a first date… cautious, polite, and just a little awkward 🥂",
      "Not judging, but that move felt like you were waiting for an apology from the board 🙃",
      "Your silence says 'strategy', but your move says 'hmm… maybe' 🤔",
      "That block placement? Elegant. Misguided. But elegant 👠",
      "You really said 'let’s see what happens' and dropped a piece like it’s a social experiment 🧪",
      "Honestly, I didn’t know if you were starting a game or conducting a séance 🔮",
      "That move whispered: 'I’m doing my best, don’t look at me' 😅",
      "First move down. Emotional damage: low. Suspense: medium. Intrigue: high 🎬",
      "I’ve seen softer starts, but usually from someone diffusing a bomb, not placing a shape 💣",
      "That felt more like a statement than a strategy… and I kind of loved it 📝",
      "Opening move was a vibe—just not a solvable one 🧩✨",
      "You walked in like a queen and dropped that block like a plot twist 👑📉"
    ],
    analysis_strong: [
      "Confident moves with quiet intent. I saw that—and I’m not easy to impress 👏",
      "Every piece you dropped looked like it had somewhere to be. Purposeful. Focused. 💼",
      "That wasn’t luck. That was precision wrapped in casual elegance 🎯",
      "You moved like someone who read the manual—twice—and still made it look spontaneous 📘",
      "The calm you played with? That’s not fearlessness, that’s control 🧠",
      "There were moments I genuinely leaned in. Like—wait, she knows what she’s doing 🧐",
      "Your strategy unfolded like a well-written novel. Subtle. And kind of poetic 📖",
      "I saw clarity in your chaos—organized rebellion. Nicely done 🖤",
      "Even when things got tricky, you didn’t flinch. That’s not just gameplay, that’s poise 💅",
      "There’s an elegance in confidence, and you served that with every block 🧊",
      "You didn’t just play. You curated an experience. Classy and quietly dominant 🎩",
      "That round? Proof that strength doesn’t need to shout to be heard 🔈",
      "Each move had intention. No fluff. Just clean, calculated execution 🛠️",
      "You didn’t play safe. You played sharp. And yes, there’s a difference ✂️",
      "If anyone was watching closely, they saw brilliance in motion—not just blocks falling 👁️"
    ],
    analysis_weak: [
      "I’m not saying it was random, but even the blocks looked confused 😅",
      "That decision felt like it came from a group chat with no context 📱",
      "You moved like you were being watched... by your doubts 👀",
      "It wasn’t bad, but it was... unsure. Like choosing tea in a coffee shop ☕",
      "There’s ‘trying’ and then there’s ‘hoping the game pities me’—guess which this was 🎭",
      "It looked like you were waiting for the block to tell you what to do 🙃",
      "You placed that shape like it was emotionally complicated 💔🧩",
      "Your energy was there… somewhere. It just took the long route 🚶‍♀️",
      "This wasn’t chaos. It was structured hesitation 😬",
      "You didn’t lose control—you just forgot to use it 🧠",
      "That move had potential… but then it changed its mind halfway through 🤷‍♀️",
      "I’ve seen risk. I’ve seen caution. This was just… confusion with eyeliner 👁️‍🗨️",
      "You know that look when someone almost remembers what they were doing? Yeah. That was your move 😵",
      "Sometimes trying counts. Sometimes... it needs a map too 🗺️",
      "You weren’t lost—you were just passionately misinformed 📚"
    ],
    analysis_neutral: [
      "Your moves weren’t wild, but they weren’t boring either. It was... cautiously spontaneous 🎲",
      "You played like someone who half-read the instructions and decided to vibe through it anyway 📖🎧",
      "Nothing screamed ‘strategy’, but nothing whispered ‘panic’ either. It was... something 👌",
      "I saw hints of logic trying to wrestle with impulse. Neither won, but it was entertaining 👀",
      "Not chaotic, not calculated. Just emotionally accurate ✨",
      "Some decisions felt like instinct, others like overthinking. Beautiful balance of confusion ⚖️",
      "You didn’t rush. You didn’t hesitate. You... existed. Strongly. 🧘‍♀️",
      "I couldn’t tell if it was subtle genius or low-key experimenting—but I’m here for it 🧪",
      "Your path was clear, even if the destination was still debating itself 🛤️",
      "There were moments of 'huh?', followed by moments of 'hmm.' That’s progress 📈",
      "You moved like a philosopher with a deadline. Deep but kinda lost 🧠⏳",
      "If this was a warm-up round, it had charm. If it wasn’t… it still had charm 💁‍♀️",
      "You didn’t shine, but you didn’t sink either. That’s called being real ✊",
      "I saw effort wrapped in mystery. And honestly, that’s more interesting than predictability 🔮",
      "You hovered on the edge of greatness and comfort… and that’s a delicate dance 💃"
    ]
  }
  };
  