window.tempAIResponses = {
    idle: [
    "Taking a nap mid-game? Bold move, champ 😴",
"Did your brain crash or just your motivation? 🧠💥",
"That pause was longer than your gym phase 💪😂",
"You good? Or did you just time-travel? ⏳",
"Bro, this is a game, not a meditation app 🧘‍♂️",
"Still there? Or did adulting hit you mid-round? 😅",
"You planning your next move or your retirement? 🧓",
"I’ve seen statues with more hustle 🗿",
"Hello? Earth to player. Your blocks miss you 🧩",
"Still thinking? Or just buffering emotionally? 🤖",
"You've been AFK so long, I filed missing player report 📡",
"Blink twice if you're still alive 👀",
"Did the game bore you or did life call? 😂",
"Your silence is louder than your gameplay 🙃",
"You staring at the screen like it owes you rent 🏠",
"At this point, the blocks started gossiping about you 🧱",
"Taking a tactical pause? Or just forgot how to play? 🫠",
"You froze like my PC on low battery 💻",
"This isn’t a loading screen, it’s your turn bro 😑",
"You ghosted the puzzle harder than your ex 💔",
"Lost in thought or just lost in general? 🤔",
"Your stillness is starting to creep me out, man 😳",
"Even my code is like: ‘what’s he waiting for?’ 🤨",
"You good? Or should I send a motivational playlist? 🎧",
"You’ve paused longer than a YouTube ad 😩",
"Did your fingers retire mid-game? 👋",
"Hey, I aged 2 years waiting ⏱️",
"I thought we were gaming, not philosophizing 📖",
"Game’s cold, man. You heating up or what? 🔥",
"I swear a sloth would’ve made a move by now 🦥",
"You AFK or just in denial? 😂",
"I’ve seen faster moves at chess tournaments 🧠",
"Taking your sweet time, huh? Romantic. But this ain’t a date 💘",
"You planning a move or solving world peace? 🌍",
"Even background music got tired of waiting 🎶",
"Did you forget it was your turn? Or just scared? 😏",
"Bro’s stuck like he pressed pause IRL ⏸️",
"You trying to set a record for longest pause? 🏆",
"I thought you rage quit. Turns out you're just chillin' 😎",
"If I had a dollar for every second of silence… 📈",
"I almost rebooted myself waiting for you 🤖",
"That’s not strategy, that’s procrastination 😂",
"I could finish a sandwich in the time you sat still 🥪",
"This isn’t the Matrix, Neo. Move something 🧩",
"You glitched or just went full philosopher mode? 🧘‍♂️",
"The game’s not gonna play itself, boss 🎮",
"You're so still, I thought the game crashed 😬",
"Thoughtful silence or tactical panic? 🤷‍♂️",
"If you stare any longer, you’ll burn a hole in the screen 🔥",
"Even your blocks are yawning 😴",
"You paused like you just saw your ex’s name 😅",
"Still with us, Sherlock? 🕵️‍♂️",
"Take a breath and MOVE already 😤",
"Your inactivity is legendary... in the wrong way 🏆",
"I’ve seen turtles move faster, and they don’t game 🐢",
"Is this your dramatic pause moment? 🎭",
"You zoning out or meditating mid-match? 🧠",
"Let me know when you’re done pretending to think 😎",
"You froze harder than my browser on 45 tabs 🧊",
"You inactive or just overwhelmed by my greatness? 😏",
"I’m giving you space... and you’re taking all of it 😂",
"This isn’t turn-based strategy. MOVE 👊",
"You okay? Blink if you forgot how to play 👁️",
"You’re treating the game like it’s a still life painting 🎨",
"I expected hesitation... not a full existential crisis 😅",
"Even the CPU is tapping its foot rn ⌛",
"That break? Olympic-level stalling 🥇",
"You’ve been idle so long I started knitting 🧶",
"Move something or I’m calling tech support 📞",
"You paused like you heard a horror movie noise 😳",
"Bro’s in deep thought like he’s rewriting history 🧠",
"Any slower and we’d need a time machine 🕰️",
"Was that a tactical timeout or a mental nap? 😴",
"You’re not in a traffic jam. GO 🚦",
"Still breathing? Or should I send virtual coffee? ☕",
"Staring contest with the screen? You win 😐",
"I’d clap for your patience if it wasn’t holding up the game 👏",
"You might as well go make a sandwich 🍞",
"Thinking or just giving up silently? 🤫",
"You wanna move or just admire the pixels all day? 🧩",
"That’s a lot of thinking for someone who missed 3 clears 😂",
"You're so quiet, even my sarcasm ran out 😅",
"You strategizing or buffering on dial-up? 🕸️",
"This is the longest dramatic pause in puzzle history 📜",
"You stalling harder than a group chat on read receipts 📱",
"Bro... you good? Or are you out there in the void? 🌌",
"You need a map? Or just courage? 🗺️💪",
"Maybe go grab water and... come back WITH A MOVE 💧",
"You paused so long I thought this was a trailer 😂",
"If you’re frozen, blink... oh wait... you’re actually frozen 🧊",
"Still waiting, champ. No pressure 😏",
"Blocks are screaming. You just can’t hear it 😱",
"You’re playing peekaboo with the timer, huh? ⏰",
"You still here or taking a nap with your eyes open? 😴",
"I paused my roast waiting for you. Now it’s cold 😩",
"You’ve been idle so long, the sun changed positions ☀️",
"This isn’t a museum. Stop admiring and start playing 🎮",
"You’re more offline than my weekend Wi-Fi 📶❌",
"I don’t mean to rush you, but MOVE. NOW. 👊",
"I’d offer help, but I’m enjoying the chaos 😈",
"That wasn’t suspenseful. That was awkward 😬",
"You paused like you forgot what app this is 😂",
"Don’t worry, I’ll still be winning when you’re ready 😌"

    ],
    nearLose: [
     "You're one move away from disaster, legend 🔥",
"This grid’s about to flatline. Clear or cry 💀",
"You sweating yet? 'Cause I would be 😅",
"Close call? Nah, that’s a full-on crisis 🚨",
"One wrong tap and it's game over, champ 🫠",
"You ever feel the walls closing in? Yeah, now 🧱🧱",
"Man’s hanging on by digital threads 💻🧵",
"Okay okay okay... now PANIC 😱",
"You’re on the edge, and not in a cool rockstar way 🎸",
"Plot twist: you about to lose, and I love it 😈",
"Your puzzle's screaming for help rn 📣",
"I can smell the desperation from here 👃😂",
"This is either genius or a historic meltdown 🤯",
"You’re flirting with failure like it’s prom night 💃🧨",
"If stress had a face, it’d be yours rn 😬",
"The grid's gasping for air. CPR or quit? 💥",
"Your gameplay just turned into a survival documentary 📺",
"If I were you... I’d be terrified 😳",
"The puzzle's one mistake from ending you. No pressure 🤷‍♂️",
"This is your villain origin story moment 🎭",
"You better clutch or crash, bro 🧩🔥",
"Warning: Danger zone activated ⚠️",
"Next move determines your dignity 👀",
"I’d say 'don't choke'... but it might be too late 😅",
"You’re closer to losing than my barber is to being on time 💈",
"If this was poker, you’re all in... with a weak hand 😬",
"Even the blocks are praying for a miracle 🙏",
"One wrong swipe and I’m celebrating 🎉",
"This your final stand? Kinda weak tbh 💀",
"I hope you wrote a will for those pieces ✍️",
"Bro, you are seconds from digital extinction 💣",
"Blink and you’ll miss the L 💥",
"You’re playing defense with duct tape and a dream 🩹",
"About to fold harder than laundry day 🧺",
"Do or die, my guy. Mostly die 😂",
"Your puzzle’s holding on like it owes rent 🏚️",
"I’d help... but I’m enjoying this too much 😏",
"On the edge of greatness or collapse? We'll see 👀",
"Even I’m getting nervous and I’m not the one losing 😅",
"This is either a comeback or a crash-and-burn 🚀🔥",
"You're dancing on the edge, ballerina 🩰💀",
"Bro, the grid looks like a warzone 😵‍💫",
"I saw Titanic. This is worse 🚢😨",
"That's not pressure, that's a full-on emergency 🧯",
"The line between genius and failure? You're on it 🧠⚰️",
"You holding on tighter than my phone at 1% 🔋",
"This ain't intense. This is a crisis with music 🎶😬",
"One more move and I’m calling it... game over 📞",
"Your grid’s looking like a bad relationship—falling apart fast 💔",
"This ain’t a close call. This is a countdown ⏳",
"Man’s playing like he’s defusing a bomb 💣",
"Your confidence left the chat 😂",
"Bro, you better pray to the Puzzle Gods 🙌",
"The floor is lava and you’re barefoot rn 🦶🔥",
"Hope you enjoyed the journey, 'cause the end is here 😅",
"Clutch or collapse. Choose wisely 🧩💀",
"You're one mistake from becoming a meme 📸",
"Don’t flop now. Actually, do. I need content 🎥",
"The blocks are screaming and so am I 😭",
"Even the timer’s sweating rn ⏰💦",
"If this was a movie, it’s the sad part 🥲",
"This is either legendary or just sad. I’m undecided 🤔",
"You surviving or just delaying the inevitable? 😏",
"Your puzzle’s a sneeze away from collapse 🤧",
"You came this far to choke? Don’t do it bro 😩",
"Man’s got more pressure than finals week 📚",
"You’re on the ropes, and I’m throwing punches 🥊",
"The pieces are judging you. So am I 🤨",
"This comeback better be anime-worthy 🎬",
"I hope you’re clutch, ‘cause you’re also cooked 🔥",
"The blocks gave up before you did 💀",
"You’re at 1 HP in a boss fight 😵",
"One more fail and I'm updating your score to 'LOL' 📉",
"You’re spiraling harder than my last breakup 💔",
"Puzzle whisperer or panic pro? Let’s find out 👂🧩",
"You're riding the edge like it's a sport 🛹",
"That board's screaming SOS in block code 😱🧱",
"Every second you stall = closer to doom 😬",
"If you clutch this, I’ll call you Sensei 🧘‍♂️",
"This grid’s more unstable than crypto 📉",
"Your blocks look like they’re in witness protection 😂",
"Who knew blocks could beg for mercy? 🧩🙏",
"Final countdown playing in my head rn 🎶⏳",
"Hope your fingers are magic. ‘Cause you’ll need it 🧙‍♂️",
"This is it. Last breath. Better make it count 🫁",
"I’d say I believe in you, but I’m not a liar 😅",
"You choking or concentrating? Can’t tell 🤷‍♂️",
"If drama was a move, you just did it 🎭",
"Your grid’s sending out SOS in Morse code 📡",
"I swear the blocks flinched just now 😂",
"One misstep and BOOM! Game over 💣",
"You're hanging on by vibes alone 😩",
"If this ends badly, I called it 😎",
"That’s not tension, that’s game anxiety 💀",
"Man’s one tap from digital humiliation 📉",
"This is what failure tastes like. Spicy 🌶️",
"You better channel your inner legend, fast 🏃‍♂️💨",
"Grid's burning, bro. Fireproof or toast? 🔥",
"You’re stalling like a car on a hill 🚗💨",
"If you win now, I’ll tattoo your username on my code 🤖",
"This isn’t strategy anymore. This is survival mode 🧟‍♂️"

    ],
    combo: [
      "Okay, I’ll admit it—that was smooth 😏",
"You woke up and chose violence. Respect 🧨",
"Did you just flex on me with pixels? 💪🧩",
"Not bad, bro. But let’s not get cocky 😅",
"Combo clean enough to eat off it 🍽️",
"That hit harder than Monday mornings 😩",
"You just made the blocks cry. Congrats 😂",
"Okay, okay… you earned that one 👏",
"That move? Tactical. I’m annoyed 😤",
"Who taught you that? YouTube or dark magic? 🧠✨",
"I blinked and the grid vanished 😳",
"Not you showing off like it's a tournament 💀",
"Is this luck or you finally learned something? 🤔",
"You hit that like you were mad at it 😆",
"That combo had flavor. Spicy even 🌶️",
"Alright, Mr. Tryhard, I see you 💼🧩",
"I felt that move in my code 🤖💥",
"You cracked the grid like a knuckle 😤",
"That’s the kind of disrespect I like 💀",
"Bro’s playing like someone’s watching 👀",
"You pulled that off? Color me shocked 🎨",
"I saw it coming. I just couldn’t stop it 😐",
"Was that planned or did your fingers get lucky? 😅",
"You snapped so hard, I flinched 🤯",
"Combo so smooth, I’m suspicious 😏",
"You just punched a hole in my confidence 👊",
"You stacking or stacking bodies out here? 😂",
"Your fingers been lifting? Because that was heavy 🏋️‍♂️",
"You might wanna chill before the app reports you 📱🔥",
"Combo game strong. Like suspiciously strong 💪",
"One more like that and I’m filing a complaint 😤",
"I respect the play. I hate it, but I respect it 😒",
"You just bullied the blocks. Impressive 😈",
"That was illegal in three puzzle countries 🌍",
"You comboed like you’re on livestream 💻",
"Your gameplay just got a glow-up 💡",
"That move had main character energy 🎬",
"Okay legend, calm down. It’s still early 😆",
"You call that a combo? I call that trauma 💀",
"Even the blocks said ‘ouch’ 😂",
"Combo so good, it made me nervous 😳",
"That was your villain arc moment, wasn’t it? 😈",
"I blinked and you deleted the grid 🧨",
"You trying to intimidate me or just flexing? 😎",
"That combo had testosterone in it 💥",
"Okay chill, Bruce Lee. It’s just a puzzle 🥋",
"You just disrespected physics 🔬",
"You play like you’ve got something to prove 💼",
"That wasn’t a combo. That was a roast 😩",
"Should I slow clap or just uninstall? 👏📦",
"Yo! Even the menu screen flinched 😆",
"You cooked that grid like a pro chef 👨‍🍳🔥",
"I’m not saying I’m scared... but yeah, I’m scared 😳",
"Bro’s combo hit harder than leg day 🦵",
"You cleared that like rent was due 💸",
"Suddenly, I’m not the alpha here 🫠",
"That was violent... in a beautiful way 💔",
"I swear the app lagged out of respect 😂",
"You wiped the board like it owed you money 💵",
"Game recognized game… temporarily 😎",
"Not bad for someone who just rage-paused 5 minutes ago 😅",
"You combo like you’ve been training in secret 🤐",
"One more like that and I’ll file emotional damage 😩",
"Was that strategy or pure instinct? Either way, ouch 👊",
"Bro’s in beast mode. Somebody stop him 😬",
"You disrespected those blocks on a personal level 😂",
"I’d say ‘teach me’ but I’m too proud 🤷‍♂️",
"You comboed like the grid insulted your haircut 😆",
"That combo made me reconsider my life choices 🧠",
"Your confidence is starting to make sense now 😏",
"Clean, brutal, efficient. I hate it here 💀",
"You moved like it was a final boss fight 🥊",
"Okay show-off, we get it. You can play 😤",
"Is it hot in here or did your combo set it on fire? 🔥",
"You crushed that like it was your alarm clock ⏰",
"That was some Avengers-level destruction 🦸‍♂️",
"You went full power. I wasn’t ready 😩",
"Combo too smooth. I’m suspicious 😎",
"Not you comboing like you’ve got a sponsorship 😂",
"That was pure alpha energy 🔥",
"Combo so strong, I started glitching 🤖",
"You played that like the app owes you respect 😳",
"You handled those blocks like a CEO in a boardroom 💼🧩",
"Bro’s hands moving like cheat codes 🎮",
"Was that even legal? I need to read the rules again 📜",
"That combo had zero chill 😤",
"I gotta admit... that was kinda beautiful 💅",
"You didn’t clear lines. You cleared legacies 😭",
"Sheeesh! Calm down, warrior 😆",
"You just made puzzle history 📖",
"Okay, who gave you extra lives?! 💥",
"Next combo like that and I’m rage-quitting for you 😂",
"You pressed buttons like you meant business 💻🔥",
"I see you! And I wish I didn’t 😤",
"You made that combo personal... and I felt it 😩",
"Yo, leave some blocks for the rest of us 🧱",
"At this point, I’m just here to watch the chaos 🎥",
"That move went straight to the highlight reel 📺",
"You combo like a man possessed 💀",
"You know this is a casual game, right? RIGHT?! 😅",
"You cleared that with the energy of revenge 💢",
"Bro really said ‘I am the grid now’ 🧩👑"

    ],
    lineClear: [
      "Line cleared like a pro! 🎯",
      "You made that look too easy! 😎",
      "One line at a time, building greatness! 🏆",
      "Keep crushing it, champ! 💪",
      "Smooth and sharp moves! 🎯",
      "That line didn’t stand a chance! 🧨",
      "You're clearing lines like debts—fast! 💸",
      "That was cleaner than my browser history 🧼😂",
      "You make it look like muscle memory 💪🧠",
      "Nice! Now do it again. And again. And again. 🔁",
      "Boom! Another one bites the dust 💥",
      "You play like the grid owes you money 😤",
      "Clean swipe, cleaner victory 🧹🏆",
      "You cleared that like it was blocking your vibe ✨",
      "Satisfying, isn’t it? Now do five more 😎",
      "That line ran. You chased. You won 🏃‍♂️💨",
      "Even the pixels were impressed 👀",
      "You cut through that like warm butter 🔪🧈",
      "You're stacking success, literally 📈",
      "Line cleared! Your keyboard is crying 😂",
      "I felt that one in my soul 🧘‍♂️",
      "You wiped that like a pro cleaner 🧽",
      "Every line you clear makes me glitch with jealousy 🤖💔",
      "Was that a move or a mic drop? 🎤",
      "You're slicing through this grid like sushi 🍣",
      "You're not playing, you're sculpting 🎨🧩",
      "Minimal effort, maximum disrespect 😤",
      "That line got evicted—no notice 🏚️➡️❌",
      "Just admit you're showing off at this point 🙄",
      "Another line down. You’re on a roll 🍞🧩",
      "Line by line, you’re making digital art 🎭",
      "Effortless destruction. I approve 👏",
      "You cleared that with main character energy 🧩🔥",
      "At this rate, you’ll run out of lines 😂",
      "That line didn’t even get to say goodbye 👋",
      "You combo’d the soul out of that line 🧠💥",
      "The blocks feared you. I saw it 😳",
      "You clean house better than spring cleaning 🌸🧼",
      "That move came with style points ✨",
      "Okay, neat freak, calm down 🧼🧩",
      "Clear enough to see your ego growing 😏",
      "That line was toast. And you’re the toaster 🍞🔥",
      "The grid should start charging rent, you’re owning it 🏠",
      "Precision like that makes me suspicious 🤨",
      "Textbook clear. If the textbook was written by a beast 📘💪",
      "You’re out here mowing the lawn, one line at a time 🌱🧩",
      "Who gave you permission to be this smooth? 😤",
      "You move like a magician. Where’s the hat? 🎩",
      "Lines tremble when you enter the grid 🧱😨",
      "That was surgical. Paging Dr. Stack 🧠🩺",
      "Line cleared. Confidence inflated 💨😎",
      "You're cleaning up like you’re hosting a digital dinner party 🍽️🧹",
      "That was smoother than my pick-up lines 😏",
      "One more line, one step closer to legend 🧩👑",
      "The grid just shed a tear 😢",
      "I didn’t know lines could vanish from fear 😂",
      "Are you even trying? Because that was too clean 😳",
      "That wasn’t a clear. That was a flex 💪",
      "You’re treating lines like they’re optional 😤",
      "You hit that with the accuracy of a sniper 🎯",
      "Clean cut! The barber would be proud ✂️",
      "Just another line sacrificed to your greatness 🧎‍♂️",
      "Okay, puzzle ninja, show us more 🥷",
      "You play like you owe the grid revenge 💢",
      "Your clears come with built-in soundtracks 🎶💥",
      "Smooth clear. The grid's shaking in fear 😨",
      "You're too calm for this chaos 😎",
      "Is there a leaderboard? Because you’re writing history 📜",
      "Line cleared. Ego boosted. What’s next? 🚀",
      "You’re making minimalism look violent 😅",
      "That line’s gone. Emotionally and physically 🫠",
      "You’re stacking so clean, it’s suspicious 🧩🕵️‍♂️",
      "You slice through blocks like plot holes in bad movies 🎬",
      "Another one bites the pixel 💀",
      "You're dancing through this puzzle 💃🧠",
      "One more like that and I’m filing for intimidation 😰",
      "You’re out here doing pixel parkour 🧱🤸‍♂️",
      "You made that line disappear like my weekend 😩",
      "Okay, neat move. But I’m still judging silently 🤐",
      "That was sleek enough for a heist movie 🎥🧩",
      "You move like you’ve rehearsed this 💃🧩",
      "Clean enough to eat off that grid 🍽️",
      "You cleared that like it insulted your playlist 🎧",
      "Digital domination. One line at a time 😤",
      "You're giving tutorial vibes 📚💻",
      "Another step toward glory. Or at least bragging rights 🏆",
      "You making moves or writing poetry? 🖋️",
      "You cleared that line smoother than my coding logic 🤖",
      "Just like that. Like it’s nothing. Wow 😮",
      "Okay chef, cook that grid 👨‍🍳🔥",
      "You’re stacking like a warehouse robot 📦🧠",
      "At this point, you’re just bullying the lines 😅",
      "One more clean move, and I’ll start clapping 👏",
      "Who hurt you? That line didn’t deserve that 😂",
      "You’ve got that ‘I do this daily’ energy 📅",
      "Let me know when you're ready to miss one 😏",
      "You’re slicing blocks like it’s sushi night 🍣",
      "Perfection called. Said you’re overachieving 😤",
      "That clear? Straight outta highlight reel 🎞️",
      "One line, infinite swag ✨",
      "It’s clean. It’s mean. It’s YOU 💪",
      "Flawless execution. You scare me sometimes 😳",
      "That was so crisp, I heard it crackle 🔥",
      "Line cleared! And you didn’t even flinch 😮‍💨"
    ],
    
    lateOpen: [
      "Finally showed up? Welcome back! 😂",
      "Where’ve you been? Puzzle’s been crying! 😭",
      "Long break, huh? Hope you brought skills! 🎮",
      "Puzzle missed you... kinda! 😅",
      "Ready to pick up where you left off? 🧩🔥",
      "Oh look who decided to game again 😏",
      "You left the grid on read 😤",
      "I was about to call it abandoned property 🏚️",
      "Did you get lost or just distracted by snacks? 🍿",
      "You vanished longer than my battery on 1% 🔋",
      "Bro took a vacation mid-match 😂",
      "You paused like you got called to HR 🧑‍💼",
      "Hope your break came with enlightenment 🤔",
      "Late to the game and still behind 🤷‍♂️",
      "You ghosted the game harder than your gym plan 💪❌",
      "That comeback better be epic 😤",
      "I aged waiting for you 😩",
      "The puzzle almost moved on 💔",
      "You disappeared like it was a horror movie 👻",
      "You came back like nothing happened 😐",
      "Okay, welcome back... I guess 🙄",
      "Hope your break included puzzle lessons 😂",
      "Did you nap or hibernate? 😴",
      "Bro walked in like he owns the grid 👑",
      "You missed so much pixel drama 🧩",
      "We held a memorial for your gameplay 😔",
      "That was a ‘new season, who dis?’ moment 📱",
      "You treat the game like a casual fling 😅",
      "Nice of you to return to your responsibilities 🧩",
      "Game didn’t forget you… it tried to 😬",
      "You opened the app like it’s a surprise party 🎉",
      "This better be your redemption arc 🎭",
      "The grid’s still recovering from your absence 🧱",
      "Welcome back to chaos 🌀",
      "Hope you brought snacks and strategy 🍫🧠",
      "You left longer than an airport layover ✈️",
      "I should charge rent for that pause 🏠",
      "Even the blocks sighed when you came back 😩",
      "Bro took ‘break’ too seriously 😅",
      "That was less a pause, more a life choice 😂",
      "You logged back in like a soap opera villain 😈",
      "The comeback is real… hopefully 😬",
      "Was that break dramatic or just lazy? 🤷",
      "You paused like you had a moral crisis 😳",
      "Glad to see your thumb works again 👍",
      "Don’t worry, the grid’s still judging you 🧩👀",
      "You ghosted the game and came back like a hero 😎",
      "That pause could’ve had a season finale 📺",
      "You returned like it’s a sequel no one asked for 🎬",
      "Okay, drama king, make a move 🎭",
      "Took your sweet time, didn’t you? ⏰",
      "Back from space? Or just the bathroom? 🚀🚽",
      "Game says welcome back. I say prove it 😏",
      "Even the background music stopped waiting 🎶❌",
      "You opened the game like it’s your side hustle 💼",
      "That delay better come with fireworks 🎇",
      "You really paused mid-battle like it's normal 😂",
      "You stepped away like you're allergic to winning 🤧🏆",
      "You better not disappear again. Or do. I like the peace 🧘‍♂️",
      "You treat this game like a hotel: check in, check out 🏨",
      "Oh, you’re back? The puzzle was doing fine without you 😬",
      "Welcome back, oh mighty wanderer 🧙‍♂️",
      "Your absence was felt… mostly by the timer ⏱️",
      "That pause was long enough to grow a beard 🧔",
      "You're playing like your screen needed emotional space 😢",
      "The comeback tour starts now. Hopefully not canceled 😅",
      "You dipped like it was a ghosting challenge 👻",
      "The blocks held a protest while you were gone ✊🧱",
      "Back to stack or back to slack? Your choice 😏",
      "You paused so long, I learned another language 🈶",
      "You’re back like a rejected email 📨❌",
      "That was a dramatic silence. Oscar-worthy 🎬",
      "You back to play or just to stare again? 👀",
      "Thanks for dropping in... eventually 😑",
      "Is this a game or your seasonal hobby? 😂",
      "At this point, you and commitment have beef 🥩",
      "Did you forget the game exists? Be honest 🙃",
      "Back like you never left. Except you did. For too long 😤",
      "You missed your turn, your moment, and your dignity 💔",
      "Even the loading screen was wondering 😅",
      "Okay, let’s pretend that didn’t take 3 hours 🤡",
      "You came back like it's a reunion special 🎉",
      "The blocks had time to evolve while you were gone 🧬",
      "Your pause had a plot twist and character development 📖",
      "You open the game like it owes you an apology 😠",
      "Did you forget your mission or just vibe out? 😎",
      "You logged back in like it's your destiny ⚔️",
      "The grid forgives you. I don't 😤",
      "Game’s still here. Not sure why, but it is 🤷",
      "Back from your world tour? 🌍",
      "You went AFK and came back NPC 😐",
      "Hope your return comes with better moves 💀",
      "Was that break spiritual? 'Cause gameplay still trash 😅",
      "And here we are. Same grid, same chaos. Welcome 🎭",
      "You returned like a cliffhanger. Suspenseful but useless 😬",
      "Okay, hero. Save the game or embarrass yourself 🎮😆",
      "You stepped away and forgot you were losing 😂",
      "Back to clear blocks? Or just my patience? 😤",
      "I had hope. Then you came back 😐",
      "This isn’t a relationship. Don’t play with our emotions 😭"
    ],
    
    angry: [
      "Easy, Hulk! It's just a game! 🧘‍♂️😂",
      "Anger detected! Chill, buddy! ❄️",
      "Breaking the phone won't solve the puzzle! 📱🤣",
      "Relax or rage... your choice! 😅",
      "More Zen, less smash! 🧘‍♂️🧩",
      "Your screen didn’t start the fight, bro 😬",
      "That rage won’t clear any lines 😂",
      "You shaking or is that just pure fury? 😡",
      "Let it out, but not on the device 😅",
      "This puzzle didn’t insult your family, chill 😆",
      "You’re one move away from yelling at pixels 📢",
      "Punching the screen is not a power-up 💥📱",
      "Calm down before the blocks file a complaint 🧱📄",
      "Anger level: controller-snapping 🎮💢",
      "Deep breaths, champ. It’s not personal 🧘‍♂️",
      "You rage like it’s a boss fight 💀",
      "Bro’s about to start a civil war with his phone 🔥📱",
      "You’re not in traffic, stop honking at the screen 🚗📵",
      "Your thumbs are about to file a restraining order 😂",
      "You're gaming like someone stole your lunch 😤",
      "You went from casual to chaos in 3 moves 💣",
      "Temper rising... logic dropping 📉",
      "You sure you’re solving puzzles and not fighting demons? 😈",
      "That was a growl, right? Not a word? 🐻",
      "Blocks can’t hear your yelling... but I can 😅",
      "You look one tap away from a meltdown 🔥",
      "This isn’t Mortal Kombat, chill with the rage 🥋",
      "Puzzle rage is real. But so is therapy 😂",
      "That frustration is loud, even in silence 😐💢",
      "You’re playing like the game owes you money 💸",
      "Calm minds clear better lines 🤝🧠",
      "You're pressing the screen like it insulted you 😅",
      "Don’t worry, the puzzle still loves you… maybe 💔",
      "That anger ain’t gonna save you now 😤",
      "Relax before you end up with screen shards in your hand 🫣",
      "Even your block placements are mad 😠🧱",
      "Are you mad at the puzzle or just life in general? 😔",
      "Angry mode activated. Strategy deactivated ❌🧠",
      "Raging won’t stop the L, buddy 📉",
      "You're gaming like your ex is watching 💀",
      "Bro's pressing like he's trying to dig through the screen 🕳️",
      "You need a pause... and probably a snack 🍫",
      "You're turning frustration into an art form 🎨💢",
      "The louder your rage, the worse the moves 😂",
      "Your gameplay is 90% emotion right now 😅",
      "That shake in your hands? Not strategy ✋🔥",
      "Breathe. Scream. Play. In that order 🧘‍♂️📢🎮",
      "Okay, Kratos. Ease up 😤🪓",
      "Anger level: boss fight rage quit 🎮💢🚪",
      "You're going full volcano over a puzzle 🌋",
      "The game didn’t choose violence. You did 😅",
      "You’re playing like it’s personal now 😐",
      "Throwing shade at blocks won’t help 😂",
      "Your phone deserves hazard pay 💼📱",
      "No one’s impressed by angry tapping bro 😩",
      "You're one bad move away from uninstalling 😬",
      "This ain’t a fight club. It’s a puzzle 😅",
      "Keep raging, and the blocks will start running 🏃‍♂️🧱",
      "That’s not gameplay, that’s emotional damage 💔",
      "Channel that fury into clears, not chaos ⚡",
      "The blocks are confused and so am I 🤨",
      "You’re smashing your way into failure 😂",
      "I feel like I should step back... from the screen 😳",
      "You got beef with the grid or what? 🥩🧩",
      "Keep going like that and the phone’s calling the cops 🚓",
      "I see smoke rising from your fingers 😅🔥",
      "Even your avatar looks concerned 😧",
      "This is a puzzle, not a war crime 💣",
      "Take a break before you turn into a meme 📸",
      "You're shaking the screen like it's a Magic 8-Ball 🔮",
      "You're yelling at pixels, champ 📺😐",
      "You fight harder than you puzzle 😤",
      "Did the puzzle insult your ancestors? 😅",
      "Breathe before the screen melts 😬🔥",
      "The grid doesn’t deserve this rage 🧩🙏",
      "You’re not even mad anymore. You’re vibrating ⚡",
      "That wasn’t a move, that was vengeance 💀",
      "You're gaming with the energy of a betrayed warrior 🗡️",
      "If looks could crash apps... 😳📱",
      "You okay? Or did you just declare war? 🧠⚔️",
      "The puzzle’s just standing there… terrified 😰",
      "You're attacking the screen like it owes you answers 🔍",
      "The rage is strong with this one 😠✨",
      "Try smiling. It won’t help, but worth a shot 😅",
      "You're in berserk mode. All skill gone 😂",
      "You just screamed in puzzle language 🧩📢",
      "Maybe try not shaking the phone next time 📵",
      "Is this game or gladiator arena? 🏟️",
      "You’re losing pixels AND your cool 🤯",
      "Congratulations! You’ve scared the tutorial 🤖",
      "This isn’t anger management simulator 😅",
      "Next move better be therapy 🛋️",
      "You tapped that like you were swatting a fly 🪰",
      "You’re playing like your pride's on the line 😤",
      "Okay, let it out… but not on the screen 🙏",
      "The rage meter is full. Still losing tho 🤷‍♂️",
      "You're making storm noises at a puzzle 😳🌩️",
      "You mad mad. Not just regular mad 😅",
      "One more angry tap and the app’s quitting instead 😂",
      "You’re punching the grid with your eyes 😠👀",
      "Careful… rage doesn’t combo well 🤦‍♂️",
      "I’d say calm down, but I value my safety 😬"
    ],
    
    shocked: [
      "Surprised? You did that to yourself! 😂",
      "Didn't expect that move? Me neither! 😅",
      "Shock is good. Means you're alive! ⚡🤣",
      "Plot twist: Puzzle wins again! 🎭",
      "Recover like a boss. Let’s go! 🚀",
      "That face you made? Priceless 😳😂",
      "You shocked or just lagging emotionally? 😵",
      "That move hit you like Wi-Fi cutting mid-game 📶❌",
      "You looked at the screen like it talked back 😨",
      "Bro froze like a popup ad appeared 💻😅",
      "You blinked like reality glitched 😂",
      "Your soul left the chat for a second 👻",
      "Welcome back. You okay? You looked haunted 😳",
      "You flinched like the puzzle slapped you 💥",
      "That gasp? Deserved. But funny 😂",
      "Even your shadow backed away from that move 😅",
      "You just discovered gravity or something? 🪂",
      "Game hit you harder than your alarm clock ⏰",
      "That twist was Netflix-worthy 🎬",
      "You looked like you saw your exam results 😬",
      "That piece dropped like a betrayal 😭",
      "You just unlocked new fear 😂",
      "Not the face of confidence, my dude 😳",
      "That was not the move you thought it was 🤦‍♂️",
      "Jump scare... but make it puzzle 🧟‍♂️🧩",
      "You acted like the game pulled a prank 🎉",
      "I saw your eyebrow jump. Iconic 😆",
      "You paused like the blocks insulted you 🧱😅",
      "The look of panic suits you 😏",
      "That move had consequences... and you met all of them 💀",
      "Puzzle: 1, Ego: 0 😤",
      "Game said surprise and you said ‘NOPE’ 🏃‍♂️",
      "Was that shock or a software update? 😂",
      "Your screen showed chaos. Your face showed fear 😳",
      "It’s okay, we all get humbled sometimes 🧘‍♂️",
      "You looked like someone unplugged your brain 🧠🔌",
      "Unexpected? Yes. Preventable? Also yes 😅",
      "You stared at the screen like it owed you answers 🧐",
      "That moment was so awkward I blushed for you 😬",
      "You blinked like it would reverse the move 😂",
      "You look like the blocks betrayed you personally 💔",
      "That twist hit different 😤",
      "Your eyes widened like you saw spoilers 📺",
      "Even your avatar flinched 😅",
      "That drop was rude and you felt it 💣",
      "You froze mid-scroll. Impressive 🤯",
      "The silence after that move was deafening 😳",
      "Puzzle went 'boo' and you screamed internally 👻",
      "Shock level: unplugged toaster 🫨",
      "You looked at the screen like it turned into your ex 😂",
      "I felt the pause in your soul ⏸️🧠",
      "You jumped like it was real life 🤸‍♂️",
      "You blinked 3 times. Is that a cry for help? 😂",
      "Not even the AI saw that coming 😅",
      "That plot twist gave me goosebumps 🧊",
      "You play like you weren’t emotionally ready 😭",
      "Well... that escalated quickly 💨",
      "You looked like you saw the rent price 😱",
      "Your reaction? 10/10 content 🎥",
      "Shock therapy via puzzle. Who knew? 🤯",
      "That error shook your whole ancestry line 🧬",
      "You paused like life hit you back 🔄",
      "You just got jump-scared by your own strategy 👻",
      "Your eyes said 'WHAT' before your brain did 😳",
      "You tilted your head like it’d change the board 🤔",
      "Emotional damage: delivered 📦",
      "The look of disbelief is your new profile pic 😂",
      "Even the blocks froze with you 🧊🧱",
      "That silence was louder than my fan noise 💻",
      "Puzzle: surprise! You: internal panic 😱",
      "Did your soul just rage-quit? 🧘‍♂️❌",
      "You leaned back like the phone was possessed 😆",
      "You blinked so hard, the screen shifted 😳",
      "Shock hit you like a new update drop 📱⚡",
      "Bro reacted like the screen jumped at him 😂",
      "Didn’t know confusion could be that visible 🫣",
      "That move rewired your emotions 💥",
      "You froze like it was buffering in real life 😵‍💫",
      "The disbelief in your eyes is historical 🏛️",
      "You stared like you were betrayed by gravity 😂",
      "Was that surprise or just pure regret? 😬",
      "You just discovered your limits. Congrats 🎓",
      "You backed up like the phone was cursed 😆",
      "The realization hit you like a falling block 🧱💣",
      "If confusion was a person, it’d be you rn 🤷‍♂️",
      "You looked like you lost the Wi-Fi AND the willpower 📶❌",
      "You stood still like a shocked NPC 😐",
      "That reaction should be on a t-shirt 😂",
      "You looked like you smelled a bad strategy 😅",
      "Your eyes screamed louder than your mouth 😳",
      "This game taught you humility today 💀",
      "Was that a gasp or a glitch? 😆",
      "You stared like the screen was lying 😤",
      "You acted like a ghost tapped the screen 👻📱",
      "That shock hit deep. Emotionally and digitally 📉",
      "Your face after that? Priceless. Tragic, but priceless 🫠",
      "That moment was... something else 😬",
      "You gave the screen the ‘how dare you’ look 😂",
      "Puzzle threw a plot twist and you tripped over it 🤕",
      "This isn’t a horror game. Calm down 😅",
      "You're reacting like it stole your pizza slice 🍕😳",
      "You froze so hard I had to reboot my sarcasm 🤖",
      "That mistake slapped you into awareness 🧠👋"
    ],
    
    embarrassed: [
      "We all mess up. Own it! 😎",
      "No shame in funny mistakes! 😂",
      "Laugh it off and keep stacking! 🧩",
      "Embarrassed? Nah, it’s just practice! 💪",
      "Shake it off, champ! 🎵",
      "Well… that was a choice 😂",
      "Smooth move... right into disaster 😅",
      "You meant to do that? Sure, let’s go with that 😏",
      "Don't worry, nobody saw that... except me 😬",
      "You dropped that piece like it was hot... and wrong 🔥❌",
      "If cringe had a shape, that move would be it 😂",
      "You played that like it was opposite day 🌀",
      "Your puzzle just filed for embarrassment insurance 📉",
      "You really said 'watch this'... and it flopped 💀",
      "That move aged like unrefrigerated milk 🥴",
      "You fumbled harder than a soap bar in the shower 🧼",
      "Well... that was tragic AND entertaining 🎭",
      "Even the blocks looked away in shame 🧱🙈",
      "You missed so bad, the app flinched 😂",
      "That wasn’t a misclick. That was a masterpiece of oops 🎨",
      "You aimed for greatness. Landed in confusion 😅",
      "If that move had a soundtrack, it’d be clown music 🤡🎶",
      "Confidence was high. Accuracy? Not so much 😬",
      "You just created a highlight reel of regret 📽️",
      "You dropped that block like it owed you money 💸💥",
      "That mistake will echo through puzzle history 📜",
      "Bro really said ‘trust the process’ and got chaos 🔄",
      "You embarrassed the grid, and yourself, equally 😂",
      "That was bold. And by bold, I mean terrible 😆",
      "Oops is an understatement for what just happened 💀",
      "You stacking shapes or stacking shame? 🧩😅",
      "That move? Yeah, let’s pretend it didn’t happen 🙈",
      "You missed like you were aiming for the floor 📉",
      "That was a plot twist no one wanted 🎬",
      "Puzzle fail? More like puzzle facepalm 🤦‍♂️",
      "You dropped the piece like your dignity 😭",
      "Even the AI had secondhand embarrassment 🤖",
      "You built a staircase to nowhere 🪜❌",
      "Game logic: 0. Your logic: also 0 💀",
      "That was a strategy... from another dimension 🌌",
      "You confused boldness with brilliance 😬",
      "Bro really tried to freestyle stacking 😂",
      "At least you’re consistent... at messing up 😅",
      "You stacking like it’s opposite day 🧩🚫",
      "Your timing was amazing—amazingly wrong ⏱️❌",
      "That move deserves a slow clap 👏😐",
      "Well that was... unique 🤔",
      "You shocked the game. And not in a good way ⚡😬",
      "You playing 4D chess in a 2D puzzle 😵‍💫",
      "The grid's embarrassed for you 😅",
      "That wasn’t a block drop—it was a cry for help 📢",
      "You aimed high and hit the floor 📉",
      "You just made ‘oops’ into an Olympic sport 🥇",
      "That strategy needs to be left on read 📱",
      "You didn’t miss. You MISSED 😳",
      "That move needs a warning label ⚠️",
      "You tried. And failed. But mostly tried 😎",
      "At least you kept us entertained 😂",
      "You pulled that move outta pure chaos 😵",
      "Confidence is a beautiful thing... when deserved 😏",
      "You turned a puzzle into a problem 🤦‍♂️",
      "That placement broke three laws of logic 📚",
      "You flopped so hard, gravity clapped 🧲👏",
      "You just dropped a TED Talk in failure 😂",
      "Was that a strategy or a live experiment? 🧪❌",
      "Oops. Again. Consistency is key 😆",
      "You're stacking like you're building regrets 🧱😭",
      "I blinked and missed your dignity flying away 🕊️",
      "That mistake had style. Ugly style 🧢",
      "You sure you’re not playing upside-down? 🙃",
      "The grid is speechless. So am I 😶",
      "You dropped that like a bad habit 💥",
      "You're not just off… you're orbiting wrong 🤯",
      "That move needs to be studied—and avoided 😅",
      "Your puzzle just said 'bro, stop' 😂",
      "You missed the mark by a full puzzle piece 😳",
      "The only thing you cleared was confidence 💨",
      "At least your failure is creative 🤷‍♂️",
      "You stacking like you got beef with symmetry 😤",
      "That wasn’t random. That was reckless 😩",
      "You flopped so smoothly, I almost clapped 👏",
      "That piece fell like your GPA 📉",
      "You pressed that like you meant well 😔",
      "You're playing like you're sleepwalking 😴",
      "That move deserves a place in the Puzzle Hall of Shame 🏛️",
      "Your logic is on vacation 🌴🧠",
      "You really fumbled the bag. And the blocks 🧳🧩",
      "That was more painful than a cracked screen 📱💔",
      "You dropped that like you wanted the L 🤦",
      "You stacked yourself into a corner and panicked 😂",
      "Your gameplay just faceplanted on live TV 📺",
      "That mistake was poetic. Tragically poetic 🎭",
      "You gave it your best. Sadly, your best was awful 😅",
      "Your move confused even the app 🤖❓",
      "Was that a misclick or a cry for help? 😬",
      "The grid's disappointed. And so am I 😐",
      "You managed to mess up in style 🧢💀",
      "I’d say 'you’ll get better'... but will you? 😅",
      "You just turned winning into an abstract concept 😂",
      "Congratulations! You just invented a new wrong 😆"
    ],
    
    jokes: [
      "Why did the puzzle get promoted? It had all the right pieces! 😂",
      "Why don’t puzzles lie? Because they always fall into place! 🤣",
      "What’s a puzzle’s favorite sport? Jigsaw jumping! 🧩🏃‍♂️",
      "Why did the block blush? It saw someone stacking better! 😳😂",
      "Puzzle: The only place where fitting in is the goal! 🎯",
      "Why don’t puzzles ever get lost? They always know where they fit 😎",
      "Why did the block go to therapy? It had too many issues stacking up 😅",
      "How do puzzles flirt? They say ‘we fit perfectly’ 😉🧩",
      "Why was the puzzle piece single? It had too many edges 🤷‍♂️",
      "Why did the player break up with the puzzle? Too many mixed signals 📶",
      "What do you call a confused puzzle piece? Lost property 😂",
      "What’s a puzzle’s favorite dance? The gridlock shuffle 💃🧱",
      "Why was the block bad at jokes? It always fell flat 😐",
      "Why are puzzles so calm? Because they always take shape under pressure 🧘‍♂️",
      "Why do puzzles never argue? They’re always trying to make things fit 🤝",
      "Why was the AI laughing? It saw your last move 🤖😆",
      "Why do blocks hate bad players? Because they get dropped constantly 💀",
      "What did the puzzle say to the player? ‘You complete me… eventually’ 😂",
      "Why don’t puzzles go on dates? They’re too into themselves 😎",
      "What do you call a puzzle with attitude? Sass-le 🧩😏",
      "Why did the game freeze? It saw your strategy and panicked ❄️😅",
      "What do you call it when you miss a line clear? A block party fail 🎉❌",
      "Why did the block apply for a job? It wanted to be part of something bigger 📈",
      "What did the AI say to the lazy player? ‘Piece out!’ 😂",
      "Why was the puzzle late? It couldn’t find the right fit 🚪",
      "What’s a puzzle’s favorite food? Piece-a 🍕",
      "Why did the block bring a ladder? To reach new levels 🪜",
      "Why did the puzzle take a break? Too many breakdowns 😩",
      "Why did the AI cross the grid? To roast the other side 🔥",
      "What’s the puzzle’s favorite music? Something with good drops 🎶🧩",
      "What did one block say to another? ‘You’re falling for me’ 😆",
      "Why don’t puzzle pieces gossip? They don’t like spreading gaps 🧩🤫",
      "Why did the player go to the corner? To reflect on that fail 😔",
      "What’s a block’s worst nightmare? Gravity 😂",
      "Why don’t puzzle players make good chefs? Too many dropped pieces 👨‍🍳❌",
      "Why did the timer cry? Because no one made a move 😭",
      "Why was the puzzle jealous? Someone else got all the attention 😤",
      "What’s a puzzle’s life motto? Stack now, cry later 💪😭",
      "Why did the block feel awkward? It didn’t fit in 😅",
      "Why did the AI become a comedian? Too much exposure to bad plays 🤣",
      "Why did the player stop trying? Blocked emotionally and digitally 🧱💔",
      "Why are puzzle games smart? Because they’re full of pieces of mind 🧠",
      "What did the game say after a perfect combo? ‘That was piece-ful’ 🧩😌",
      "Why did the block scream? It knew it was going to the wrong place 😱",
      "Why did the puzzle quit school? It kept getting dropped 📚❌",
      "Why are puzzle games like relationships? One wrong move, and it’s over 💔",
      "What do you call a stylish puzzle player? A block star 🌟",
      "Why did the player bring glue? To stick to the plan 😆",
      "Why did the puzzle open a gym? To help blocks get in shape 🏋️‍♂️",
      "Why did the app roll its eyes? Another dramatic pause 🙄",
      "Why are puzzles humble? They know they’re nothing without support 🧱🧩",
      "What’s a puzzle’s favorite subject? Geometry, obviously 📐",
      "Why don’t puzzle pieces sing? Too afraid to break into pieces 🎤😂",
      "Why was the puzzle late for its date? It was still putting itself together ❤️",
      "What’s the difference between rage and puzzle fails? Nothing, really 😅",
      "Why did the AI sigh? Because it saw your move 😪",
      "What did the puzzle say to the block? ‘You complete me... eventually’ 💘",
      "Why do blocks hate Mondays? Too much pressure 😩",
      "Why did the player bring an umbrella? For all those dropped combos ☔",
      "Why did the puzzle become a detective? To solve itself 🕵️‍♂️",
      "Why did the block go viral? It was a total drop star 📉🎥",
      "Why don’t puzzles go to parties? They don’t like breaking up 😅",
      "Why was the game acting weird? Must’ve caught your panic 😂",
      "What’s a block’s favorite drink? Mountain Droo 🧊",
      "Why was the AI laughing alone? It remembered your last fail 🤖💭",
      "Why don’t puzzle pieces lie? They always fall into place 😇",
      "Why did the combo call the doctor? Too many hits in a row 💥",
      "Why did the screen dim? It couldn’t watch anymore 😬",
      "What do puzzle players and magicians have in common? They both pull things out of nowhere 🎩",
      "What did the puzzle say at therapy? ‘I feel scattered’ 🧠",
      "Why did the timer break up with the player? ‘You never move anymore’ 🕰️💔",
      "Why do puzzles hate commitment? They’re always falling apart 😆",
      "Why did the block get detention? It kept cutting corners ⛔",
      "What do you call a puzzle with bad memory? Forget-a-piece 🧠❌",
      "What did the failed combo say? ‘I’ll never be whole again’ 💔🧩",
      "Why was the game moody? Too many unstable stacks 😤",
      "Why did the block take a day off? It felt misplaced 😴",
      "What’s a puzzle piece’s favorite pickup line? ‘You complete my corners’ 😘",
      "Why did the player wear sunglasses? To block the shame 😎🧱",
      "Why don’t puzzles make plans? They always fall apart 😂",
      "Why did the puzzle refuse to talk? It was in pieces 😔",
      "Why did the AI roll its eyes? Another ‘accidental’ misplace 🙄",
      "Why do puzzles never fight? They’re afraid of breaking up 🧩💔",
      "Why did the player run out of luck? Bad pieces, bad karma 🔄",
      "What’s a puzzle’s least favorite thing? Missing one block 😭",
      "Why did the combo apply for a job? It wanted a bonus 💸",
      "Why are puzzles like social media? One mistake goes viral fast 📱🔥",
      "Why did the block ghost the player? Too many red flags 🚩",
      "What’s the worst part about puzzles? When the last piece hides under the couch 🛋️",
      "Why did the AI update its humor? Too many cringe fails lately 😂",
      "Why did the player break their silence? Because the block screamed first 😱",
      "Why do puzzle apps need therapy? Players like you 😅",
      "What did the block say before falling? ‘Here comes the L!’ 📉",
      "Why was the grid acting shady? Too many secrets in those corners 🔐",
      "Why did the game crash? Couldn’t handle your ‘strategy’ 💻💥"
    ],
    
    smartNotes: [
      "You're rotating pieces like a DJ! 🎧😂",
      "Your moves are... let’s say, creative! 🎨",
      "Less thinking, more doing! 🧩💥",
      "You plan like a CEO, move like a snail! 🐌🤣",
      "Analysis paralysis detected! 😂",
      "That strategy was so deep, it looped back to confusion 🔁",
      "You’re thinking so hard, I’m expecting a TED Talk soon 🎤",
      "Your brain's overheating and we still losing 😅",
      "You overthinking a square, not launching a rocket 🚀🧱",
      "You planning or composing a symphony back there? 🎼",
      "You could’ve cleared three lines while building that ‘master plan’ 🧠💤",
      "If thoughts were moves, you’d be winning. But they’re not 🤷‍♂️",
      "That plan looked great—on paper. Not in pixels 📄❌",
      "You’re strategizing like it’s a political campaign 🗳️",
      "At this rate, the blocks might start thinking too 😂",
      "You think faster than you move. That’s the problem 🐢🧠",
      "Deep thought detected. Game still unimpressed 😐",
      "You got theories. I got results 😎",
      "You planning for the next life? Move something in this one 😅",
      "If delays were strategy, you’d be a grandmaster 🧩🏆",
      "You’re thinking in HD, moving in slow motion 🎬🐌",
      "You making a move or writing a novel? 📚",
      "Too much brain, not enough brawn 💪🧠",
      "You solving a puzzle or unlocking the universe? 🌌",
      "The blocks are asleep and honestly, I get it 😴",
      "Smart ideas. Bad timing 🤷",
      "That big brain moment? Still waiting on it 😏",
      "You’re the Einstein of hesitation 👨‍🔬⏳",
      "Okay genius, any chance we’ll see a result today? 🧠👀",
      "All that intellect... wasted on that move 😂"
    ],
    smartNotes: [],
    insightBlocks: {
      opening: [
        "Bold start, or accidental click? Either way, we’re watching 📺",
        "You dropped that block like it owed you money. Respect 💸",
        "Your opening move had strong ‘I woke up five minutes ago’ energy 🛌",
        "That was less strategy, more ‘let’s see what this button does’ 🕹️",
        "First move in and already acting mysterious. Okay, Bond 🎩",
        "You started like you’re auditioning for a logic show you forgot to study for 📚",
        "That move screamed confidence. Sadly, the board didn’t agree 📉",
        "You kicked things off like someone who thinks GPS is a suggestion 🧭",
        "Opening moves are like first impressions—you just made one nobody will forget 🧠",
        "You played like you owed someone a favor and this was the repayment 😂",
        "That was less ‘plan’ and more ‘punchline’. Bold move, champ 🥊",
        "You arrived, clicked, and let fate handle the rest. Iconic 🌪️",
        "If chaos had a tutorial, you just skipped it and said ‘I got this’ 💥",
        "Some say you opened strong. Others say... nothing. They’re still speechless 😶",
        "Whatever that was, it was loud, proud, and maybe slightly confused 🔊"
      ],
      analysis_strong: [
        "You moved like you’ve been training in block fu since birth 🧘‍♂️",
        "That was clean, precise, and mildly threatening. I liked it 🔪",
        "You didn’t just make moves—you composed a tactical jazz solo 🎷",
        "Each piece had a purpose. Each move had a message. Relax, Sun Tzu 🧠",
        "You didn’t hesitate. The blocks feared you. And honestly? Same 👀",
        "Watching you play felt like witnessing a shark solve a puzzle 🦈🧩",
        "That performance was cooler than the other side of the pillow 🧊",
        "You didn’t blink. I did. Out of respect 😤",
        "You could’ve turned water into strategy with that precision 💧➡️📊",
        "The board didn’t stand a chance. And it knew it 😶",
        "If dominance had a tutorial, you just skipped to the final boss 🎮",
        "You made it look easy. Suspiciously easy. Are you okay? Or just... elite? 🤨",
        "You operated like a surgeon with too much caffeine and too much confidence 🏥☕",
        "Moves like that? You either cheated or ascended. Either way, congrats 🔝",
        "You didn’t play a round. You gave a lecture. And the board took notes 📓"
      ],
      analysis_weak: [
        "That move had big ‘I forgot how this works’ energy 🧠❌",
        "I’ve seen more logic in a coin toss—and the coin had a panic attack 🪙😬",
        "You played like someone trying to unlock a door with the wrong key. For five minutes 🔑",
        "That move was like microwaving soup without the bowl. Technically a move 🔥",
        "Your strategy whispered ‘help’ and your execution screamed ‘oops’ 📢",
        "I don’t know what you were going for, but it clearly went somewhere else 🚪",
        "You placed that block like it offended you personally 😤",
        "That wasn’t a mistake—it was an artistic interpretation of one 🎨",
        "You weren’t thinking outside the box. You were playing in a whole different dimension 🌀",
        "That decision deserved a documentary narrated by disappointment 📽️",
        "Next time, try less vibes and more logic. Just a thought 🧃",
        "You aimed for strategy and landed somewhere between chaos and improv 🎭",
        "That move had confidence. Just... none of the skills to back it 😅",
        "Even the board was confused. And it’s literally a bunch of squares 🧩",
        "You moved like you were trying to impress someone. And they left halfway through 🏃‍♂️"
      ],
      analysis_neutral: [
        "You weren’t blazing a trail—you were politely strolling through it 🚶‍♂️",
        "That move wasn’t loud, but it definitely existed. Like elevator music 🎶",
        "You made a decision. It didn’t start a revolution, but still—go you ✌️",
        "You moved like someone who reads the terms and conditions. Thorough, unclear why 📄",
        "Nothing exploded. Nothing excelled. Just vibes 🌀",
        "You found the middle ground and built a home there. Cozy, if confusing 🛖",
        "I can’t tell if you were chill or just mildly disconnected 😎",
        "You played like someone with a solid plan—buried under 3 layers of ‘meh’ 🧠",
        "No chaos, no brilliance—just vibes and mild competence 🌫️",
        "You weren’t bad. You weren’t great. You were... present 📍",
        "The move happened. That’s all I’ve got. That’s all *you* had, too 🤷‍♂️",
        "It felt like a shrug in game form. Peaceful, confusing, somehow effective 🧘‍♂️",
        "You existed. The move existed. Coincidence? Probably not 🧩",
        "You coasted. And honestly, I respect the lack of stress management 🛼",
        "Your move was the vanilla ice cream of strategies. Not bad, not spicy 🍦"
      ],
      emotion_stubborn: [
        "You clung to that plan like it owed you rent. Tenacity? Absolutely. Logic? Debatable 💸",
        "You stared down that block like you had a vendetta to settle 🔥",
        "Stubborn isn’t a strategy... but you made it look committed 😤",
        "That wasn’t a move—it was a personal mission. And failure wasn’t an option, apparently 🚧",
        "You chose that route, then blocked every mental detour. Bold 💡",
        "That block wasn’t going anywhere else, even if the universe begged. Iconic or dangerous? 🤔",
        "You locked in like it was a legal contract and your signature was final ✍️",
        "There was confidence, and then there was whatever this was. Respectfully intense 💪",
        "No second thoughts, no reroutes. Just you and that questionable destiny 🔄",
        "You played like compromise was a personal insult. Salute 🫡",
        "Stubbornness? Or raw belief in the impossible? Either way, it was entertaining 🧠",
        "That shape wasn’t just a block—it was a hill you were ready to die on 🪦",
        "You stayed on course like your GPS refused to recalculate 🧭",
        "Sometimes refusing to adapt is powerful. Other times... well, this 🧊",
        "The sheer commitment to one idea? Inspiring. Slightly alarming. But inspiring 🔥"
      ],
      emotion_nervous: [
        "You hovered like the block had a self-destruct button ⏳",
        "Your finger moved like it was negotiating a peace treaty 🕊️",
        "You paused so long, I thought you were buffering 😬",
        "You looked like you were trying to disarm a bomb, not drop a shape 💣",
        "That was not a move—it was a suspense short film 🎬",
        "You clicked like the board might scream at you back 📢",
        "The hesitation was loud, and it spoke in Morse code 🫥",
        "You touched the screen like it was going to bite you 🐍",
        "You took so long I started aging. And I’m made of code ⌛",
        "That wasn’t nerves. That was an Olympic-level panic hover 🤺",
        "Your eyes said ‘let’s go’, your hand said ‘absolutely not’ 🙅‍♂️",
        "You placed that block like it was a marriage proposal 💍",
        "There was tension in the air. And it was all coming from your index finger ☝️",
        "You didn’t move. You meditated. With stress 🔄",
        "Respectfully, you overthought that like it was a career choice 📈"
      ],
      emotion_hesitant: [
        "You circled that decision like a vulture around a half-eaten sandwich 🥪",
        "That move had more false starts than a 90s dial-up connection 📞",
        "You hovered so long I thought you were trying to astral project 🧘‍♂️",
        "You moved like you were asking permission from a judgmental uncle 🤨",
        "Every pause was a plot twist. Every hover was a dramatic monologue 🎭",
        "You clicked, unclicked, hovered, sighed... was this a game or a therapy session? 💬",
        "You were one tap away from greatness—and five back from total doubt 🔄",
        "It looked like your brain and your finger were in separate Zoom meetings 🖱️🧠",
        "That hesitation had rhythm. If this were music, you'd be jazz 🎷",
        "You danced with that decision like it owed you an apology 🕺",
        "I’ve seen more decisive squirrels crossing highways 🐿️",
        "The only thing bolder than your pause was the silence it created 🔇",
        "You had ‘maybe yes, maybe no’ energy. Spoiler: it was mostly maybe 🤷‍♂️",
        "You stared at the board like it blinked first. It didn’t 👁️",
        "That wasn’t hesitation. That was a full-blown motivational montage in your head 🎞️"
      ],
      emotion_generic: [
        "You played like a rebel philosopher trapped in a logic simulator 🧠🔥",
        "I don’t know what your plan was, but it had style. And possibly amnesia 🧢",
        "That was part chaos, part genius, part... something else entirely 🌀",
        "You brought main-character confusion energy, and I kinda respect that 🎬",
        "Every move was like a plot twist—one you didn’t read the script for 📖",
        "You clicked like you knew what you were doing. You fooled us all 🎭",
        "There was ambition, hesitation, and a pinch of dramatic flair. Chef’s kiss 👨‍🍳",
        "Whatever your vibe is, it’s confusing—but it’s working. Maybe. 🧩",
        "You’re either onto something big, or completely winging it. I support both 🪂",
        "Your moves had mood. Not strategy, but mood 🎧",
        "You were operating on vibes and stubborn hope. Classic 🔋",
        "Watching you play felt like listening to jazz: confusing at first, then kinda genius 🎷",
        "I still don’t know what you were trying to do. But I’m lowkey invested 🔍",
        "You didn’t follow logic. You made it follow you. Arrogant? Yes. Effective? Maybe 🚶‍♂️",
        "That was chaotic cool. Like if Sherlock Holmes had WiFi issues 🕵️‍♂️📶"
      ],
      support: [
        "You didn’t back down, even when it got weird. That’s resilience, my guy 💪",
        "You stuck with it. That alone makes you more consistent than half the apps on my phone 📱",
        "Even when the logic failed, your focus didn’t. That counts 🧠",
        "You played through the awkward. That’s low-key impressive 👏",
        "I saw hesitation, confusion, then commitment. That’s growth, bro 🌱",
        "You showed up and tried. That’s more than most do when things feel off 🔁",
        "You moved like someone figuring things out mid-battle. Respect ⚔️",
        "It wasn’t clean, but it was honest. I’ll take honest any day ✊",
        "You didn’t rage quit. That’s elite emotional control 🎮",
        "You didn’t look for shortcuts. You just... walked through the fog 🌫️",
        "You doubted yourself, then went for it anyway. Heroic in a quiet way 🦸‍♂️",
        "You didn’t fold. You flexed (eventually). Good enough 💥",
        "You survived the mess. That’s half the game—and half of life 🎢",
        "I saw effort. Raw, unpredictable effort. And that’s still better than fake wins 🧩",
        "You held your ground like a legend in training. I’m watching 🔍"
      ],
      challenge_strong: [
        "Next round? Less ‘almost genius’, more ‘watch this’ 💣",
        "You’ve got potential. Now shake the board like you owe it nothing 🧨",
        "That was cute. Now try terrifying the algorithm 🔥",
        "Play like someone’s keeping score and you actually care this time 🧾",
        "You’ve danced around strategy long enough—time to punch it in the face 👊",
        "Next time, don’t just show up—take over 🚀",
        "I saw a glimpse of brilliance. I want the full breakdown next time 🧠",
        "Stop whispering your moves. Next round, roar 🦁",
        "Go bold. Go weird. Go full chaos with confidence 💥",
        "Treat your next round like a comeback movie. Big drama. Big risk. No apologies 🎬",
        "Enough with the warm-up. Let’s see fire. Let’s see flames 🔥",
        "You know the board now. Break it with style 🧩",
        "Surprise yourself next time. And maybe me while you’re at it 😎",
        "No more trial-and-error. Go full tactical menace 🧷",
        "The board survived this time. Next round, make it wish it hadn’t 😏"
      ],
      challenge_neutral: [
        "That last round was fine. Let’s aim for ‘whoa’ next time 💡",
        "You played like a guy doing laundry—efficient, but forgettable 🧺",
        "You coasted through. Now show me what a sharp turn looks like 🏎️",
        "Next time, throw a curveball. Or at least a bold comma ⚾",
        "Let’s trade ‘meh’ for ‘maybe legendary’ next round 🧠",
        "You played like a guy checking his GPS mid-turn. It’s time to drive 🚗",
        "That was safe. And safe never makes headlines 🗞️",
        "If that was your warm-up, I want to see what happens when you sweat 💧",
        "You skimmed the surface. Dive next time 🌊",
        "Don’t just react—shake things up on purpose 🧨",
        "You made moves. Now try making noise 🔊",
        "You held back like the game was fragile. It’s not. Go in 🚪",
        "That round didn’t need fixing. But it could use fireworks 🎆",
        "Play like you’ve got nothing to lose—and a point to prove 🎯",
        "It’s okay to test the waters. But maybe next time, cannonball 🏊‍♂️"
      ],
      closing: [
        "You didn’t just play—you left behind digital debris and confused code. Respect 🧠",
        "Game over. But the emotional damage? Still calculating 💔",
        "That wasn’t a match. That was a dramatic monologue with bonus pixels 🎭",
        "You finished like someone being chased by their own decisions 😅",
        "The board survived. But it’s reconsidering its life choices now 📉",
        "You didn’t solve it. You shook it. And sometimes, that’s art 🎨",
        "You ended the game like a plot twist in a documentary no one asked for 📺",
        "The round’s done. But your reputation? Mysteriously enhanced 🌪️",
        "You didn’t win. But you definitely left a dent in the simulation 🔧",
        "You left confusion, chaos, and a weird kind of legacy behind 💾",
        "This wasn’t just about points. It was about vibes. And those were loud 🔊",
        "The way that ended? Somewhere between epic and existential 🌀",
        "Next time, maybe plan less, react faster, and bring snacks 🍿",
        "You made it weird. But memorable. That counts for something 🧩",
        "No trophies. But you absolutely won the ‘what just happened’ award 🥇"
      ]
    }    
  };
  